### ISSUE TITLE
Bug color

### ISSUE THREAD

**Issue by EpokK** [jisaacks/GitGutter#1]
I followed the installation procedure but Git Gutter does not work. I'm on OSX and I've tried different themes.

The problem is in Packages/Git Gutter/git_gutter.py
The paths for the icons use GitGutter as part of the path, but the package is installed in Git Gutter by the Package Manager.

![Capture d e cran 2012-12-12 a 08 41 05](https://f.cloud.github.com/assets/1345786/7634/50530654-442f-11e2-9bed-5696a8d57876.png)

**Comment by Pautomagi** [comment]
Note regarding this and installing it trough the package manager. You will need to manually change the package folder name. It will download as GitGutter-Edge.

**Comment by jisaacks** [comment]
@Pautomagi that is only if you install `GitGutter-Edge`.

**Comment by Pautomagi** [comment]
Sorry about that, I forgot to comment again. But that is right. For some reason my package manager only displayed the edge version so I assumed that the package had changed name @jisaacks .

**Comment by jisaacks** [comment]
>  For some reason my package manager only displayed the edge version

The `install` command will not list packages you already have installed. :)
