### ISSUE TITLE
Icons are white boxes in ST3 Build 3043

### ISSUE THREAD

**Issue by goldfire** [jisaacks/GitGutter#102]
It does correctly mark which lines have changed, but all of the icons just show as these white boxes.

![screen shot 2013-06-23 at 9 49 25 pm](https://f.cloud.github.com/assets/882005/693208/e875aa04-dc78-11e2-9f1a-0b9ea07f1b64.png)

**Comment by brownieboy** [comment]
I've just started getting this problem.  Build 3103 on OS X El Cap 10.11.4.

I tried renaming my ~/Library/Application Support/Sublime Text 3 and starting again from scratch.  The problem still happens, even with GitGutter and Package Control as the only installed packages.  Switching between different themes doesn't help.

I have another Mac where the icons do show correctly.

**Comment by deathaxe** [comment]
The colors of the icons are defined in the color scheme. If it misses the correct definitions, the icons are show white. This is nothing which can be fixed by GitGutter.

Please edit your color scheme.
