### ISSUE TITLE
Plugin has no effect on UI (Using Windows 7 and Sublime 3)

### ISSUE THREAD

**Issue by hnsl** [jisaacks/GitGutter#109]
Plugin is loaded and Git path is configured but has no effect on the UI. Everything looks the same and there is no gutter. Works in Sublime 2.

**Comment by mazhariqbal49** [comment]
Add your git binary (.exe) path in your git settings (Preferences > Package Settings > GitGutter > Settings - Default) 

LIKE: 
// Custom path to git binary when not in PATH
"git_binary": "C:\\Program Files (x86)\\Git\\bin\\git.exe"

NOTE: Your path should have double backslashes '\\' as a directory separator.

**Comment by rchl** [comment]
Seems like a support question and looks like cause by wrong git_binary path. Closing.
