### ISSUE TITLE
sublime lags with gitgutter

### ISSUE THREAD

**Issue by aortmannm** [jisaacks/GitGutter#126]
Hi,

I'm using Sublime Text 3 Build 3047 and I have with GitGutter lags when Im typing. When I delete GitGutter it works well.

Im working on a Lenovo U330 with i5. 8GB RAM and SSD. So it should be the performance :).

Probably the post helps

**Comment by foxx** [comment]
Having the same problem today, was this fix released?

**Comment by yvess** [comment]
Had the also the same problem today, and first blamed gitgutter. But it was a wrong python interpreter setting in my .anaconda project file. I found it out with a look at "View -> Show Console"
