### ISSUE TITLE
Allow specifying commits to compare against by hash

### ISSUE THREAD

**Issue by Ajedi32** [jisaacks/GitGutter#142]
Currently, when trying to compare against a specific commit that I know the commit hash for, am unable to simply paste the commit hash into the command palette; I have to search by commit message instead.

Not a big deal, but it is a small annoyance for me. It would be great if the command palette allowed you to search by commit hash, or if there were a separate command for inputting the hash directly.

**Comment by deathaxe** [comment]
PR #354 Adds the first 7 digits of the hash to the beginning of the title of each commit. This would enable you to search by hash.
