### ISSUE TITLE
No GitGutter marks on ST3 on Linux

### ISSUE THREAD

**Issue by ivanov** [jisaacks/GitGutter#144]
I've followed the suggestions on #127 but had no luck.

There are no complains from loading GitGutter plugin in ST console. GitGutter commands appear in the Ctrl-Shift-P command palette but running them has no effect on the gutters.

Reinstalling ST3 does not help, neither does setting the full git path explicitly. I have installed and set the color scheme to   sublime-monokai-extended but that did not help, either. Neither did turning on non_blocking.

How can I help further diagnose what might be going on here?

This is on ST3 Build 3059,  with GitGutter 3909b50108302f02d8e523e0e7769e1db0a18acd

**Comment by rchl** [comment]
I doubt you still have this problem after 3 years so closing.
Feel free to open new issue if it's still the case and we can try to diagnose it.
