### ISSUE TITLE
Slow with copy and paste + huge files

### ISSUE THREAD

**Issue by JesseAldridge** [jisaacks/GitGutter#147]
I pasted a 120K line data dump into a file and Sublime slowed to a crawl.  Works fine if I disable GitGutter.  

An easy fix would be to simply disable the gutter by default for huge files.

**Comment by rchl** [comment]
It shouldn't cause GitGutter to slow down anymore as git runs asynchronously.
Should there still be a configurable limit through? I'm not sure it is needed.

**Comment by jisaacks** [comment]
@rchl if it is no longer necessary I'd like to avoid any bloat.

**Comment by deathaxe** [comment]
GitGutter 1.5.0 comes with a heavily improved algorithm to reduce the time needed to calculate the regions to add icons to from the git diff output. Benchmarks showed a decrease from ca. 10s to 0,1s for a file with 100k lines.

Please check, whether it works for you.

**Comment by JesseAldridge** [comment]
Haven't noticed any lag problems in like six months now that I think about it.  So I guess 1.4 has been good enough for me.

**Comment by deathaxe** [comment]
OK, thanks.
