### ISSUE TITLE
Add keyboard shortcut to show/hide icons

### ISSUE THREAD

**Issue by Naomak** [jisaacks/GitGutter#153]
I'm also using pylinter and those two plugins are fighting each other who will draw icons. I want the pylinter icons to be shown on top of the GitGutter's. Even though I rerun pylinter code control manualy, or show/hide them, they are still undder GitGutters. Well I don't know why it behaves like that, but it would be nice to have keyboard shortcut to show/hide GitGutters icons.

I'm using Sublime Text 3.

**Comment by rchl** [comment]
I guess `protected_regions` options should help here.
But maybe adding shortcuts to toggle GitGutter still would be of value.

**Comment by rchl** [comment]
It's essentially a dup of #161 so will resolve.
