### ISSUE TITLE
Anyway to use gitgutter with rsub

### ISSUE THREAD

**Issue by shaunpatel** [jisaacks/GitGutter#157]
I have discovered rsub for sublime text which is a nice way to edit files locally over ssh. However, I noticed that gitgutter doesn't work using this method, because the git repository is on the remote computer. 

Any suggestions on a workaround?

**Comment by mpchadwick** [comment]
:+1:

**Comment by deathaxe** [comment]
I am not quite sure how rsub works. But I guess this would require to forward the git commands via SSH to the remote machine and read the console output from the remotely located git command. This would require to open a SSH tunnel or use the rsub somehow. Don't think we'll do that.

**Comment by deathaxe** [comment]
Had a look onto rsub. It downloads the file to edit from the remote machine to a temporary local file using a special command server over SSH. As the whole working tree an git index database still remains on the remote machine this feature can't be implemented to GitGutter. It is not possible.
