### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by arsham** [jisaacks/GitGutter#160]
It seems the last merge has broken the plugin. There is no error in debug console.
Also view.run_command('git_gutter') does nothing.

I've disabled all plugins that draw in gutter in case they override, still nothing shows up in there.

[Specs: ST3 on Arch Linux]

Thanks

**Comment by rchl** [comment]
A lot has changed since 2014 and non_blocking setting was recently removed so probably this is not an issue anymore. Closing.
