### ISSUE TITLE
Option to Enable/Disable GitGutter

### ISSUE THREAD

**Issue by tgirardi** [jisaacks/GitGutter#161]
As stated by some users in issue #113, GitGutter marks, in some cases, hides icons from other packages which are important (e.g: linter, xdebug).

One fast and simple solution would be to have the ability to enable/disable GitGutter. At least until a more proper solution is made.

Notice that using "Package Control: Disable Package" is not enough, as it doesn't hide the marks actually present in the Gutter unless you restart the application.

**Comment by harshaxnim** [comment]
@jisaacks Is this something you intend to do in sometime? I find the dots on left to be too distracting when coding, but I do not want to remove your plugin. I'd like the changes to show when I hover on the gutter, or something like that. If I get some time, I'll try to implement it myself.

**Comment by tedmiston** [comment]
@jisaacks Is this feature still on the table?  I'd like to disable gitgutter in the very early stage of a project, for example, just after `git init` when I may have dozens of new files in a project though they're not committed yet.

**Comment by deathaxe** [comment]
You could set `"show_markers_on_untracked_file": false` to avoid showing markers for new files. This is my default setting, too, as I find markers on each line useless.

**Comment by tedmiston** [comment]
@deathaxe Thank you, exactly what I was looking for.

**Comment by deathaxe** [comment]
Fixed in 1.6.0-rc.1
