### ISSUE TITLE
Slow over time (memory leaks?)

### ISSUE THREAD

**Issue by bprosnitz** [jisaacks/GitGutter#176]
I noticed that sublime with git gutter slows significantly over time until I restart sublime at which point it works fine again. This occurs only with git gutter and also when i just have the git gutter plug in installed.

My ST3 git gutter config is just: 
{
    "non_blocking": true
}

I'm not sure the source of this, but I wanted to open an issue and would be happy to test things out once I know what to test.

**Comment by rchl** [comment]
If you still have the issue (unlikely after all these years), please check memory and cpu usage to see where the issue is. Are there many git processes created or sublime is using more memory than expected, or...?

**Comment by deathaxe** [comment]
Memory leaks were caused by view_collections.add(), which do no longer exist.
