### ISSUE TITLE
non blocking mode is broken

### ISSUE THREAD

**Issue by sigod** [jisaacks/GitGutter#185]
Icons showed only when I open file. If restart ST or change or save file — icons doesn't change.

My settings:
```json
{
	"git_binary": "c:\\Program Files (x86)\\Git\\bin\\git.exe",
	"live_mode": false,
	"non_blocking": true,
	"show_markers_on_untracked_file": true
}
```

Window 7, x64
Sublime Text 3, 3059

**Comment by kapitanluffy** [comment]
I have the same issue. Here's my config

```json
{

  "git_binary": "",
  "live_mode": true,
  "focus_change_mode": true,
  "non_blocking": true,
  "debounce_delay": 1000,
  "ignore_whitespace": "none",
  "show_markers_on_untracked_file": true,
  "patience": true
}
```

**Comment by bcomnes** [comment]
Everything is working here, not sure what fixed it.

**Comment by adam-beck** [comment]
I'm seeing the same thing ST3 Build 3083

**Comment by jisaacks** [comment]
If you installed the latest pre-release that pushed out yesterday, does that fix anything? It had some changes to the way non blocking mode works.

**Comment by adam-beck** [comment]
I changed packages from GitGutter to GitGutter-Edge and it does appear to be fixed now.

**Comment by jisaacks** [comment]
OK, since edge and the prelease are both pointing to the same thing currently I am going to assume that this issue is fixed. If it persists once you have 1.2 or greater feel free to reopen.

**Comment by bcomnes** [comment]
:+1: LGTM for the last few months.
