### ISSUE TITLE
changes isn't recalculated if file has been changed in another program

### ISSUE THREAD

**Issue by sigod** [jisaacks/GitGutter#186]
I have open .cs file in ST and in VS. I edit it in VS and than switch to ST. There's just a red triangle at top of the file (sometimes instead of triangle square appears, probably related to #183).

Live and non blocking modes are disabled.

Window 7, x64
Sublime Text 3, 3059

**Comment by jisaacks** [comment]
Can you confirm if d4f5a85165c10b18455d23abef46b4c2dff4698b fixed this?

**Comment by sigod** [comment]
No, it doesn't fixed this issue.

**Comment by jisaacks** [comment]
@sigod, this is off topic, but wanted to let you know I appreciate the support you have been giving git gutter for quite some time now. Would you like me to add you as a collaborator?

**Comment by sigod** [comment]
@jisaacks, thanks. I'm glad to hear it. I would like it, of course.

**Comment by rchl** [comment]
But GitGutter recalculates diff both when file is modified and when it's focused. Can you see why is that not happening for you? Are you using some non-standard settings that disable most of those actions?

**Comment by deathaxe** [comment]
Changes are evaluated on each `activated` or `modified` event. One of those is most likely be sent by ST on external file modification. Checked this with GitGutter 1.5.0.
