### ISSUE TITLE
Sublime text : cannot get Gitgutter working

### ISSUE THREAD

**Issue by ghost** [jisaacks/GitGutter#187]
Hello,

```
I've been trying to get Gitgutter to work for about two days now and still haven't succeeded.  J started all over with a blank sheet tonight but not working either.   

The editor is supposed to put a '+' sign from the moment I start adding text or do a carriage/return, right ?     
```

I'm working on version 2.0.2 on a Windows 7 platform and this is the output when I start up :+1: 
    startup, version: 2221 windows x64 channel: stable
    executable: /C/Program Files/Sublime Text 2/sublime_text.exe
    working dir: /C/Program Files/Sublime Text 2
    packages path: /C/Users/Mostie/AppData/Roaming/Sublime Text 2/Packages
    settings path: /C/Users/Mostie/AppData/Roaming/Sublime Text 2/Settings
    PackageSetup not required
    Py_GetProgramName(): sublime_text.exe
    Py_GetExecPrefi): C:\Program Files\Sublime Text 2
    Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
    Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
    Py_GetPythonHome(): C:\Program Files\Sublime Text 2
    catalogue loaded
    found 5 files for base name Default.sublime-keymap
    found 1 files for base name Default.sublime-mousemap
    found 3 files for base name Main.sublime-menu
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\git_gutter.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\git_gutter_change.py
    Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\git_gutter_compare.py

```
Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\git_gutter_events.py

Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\git_gutter_handler.py

Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\git_helper.py

Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\GitGutter\view_collection.py

Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py

Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py

Reloading plugin C:\Users\Mostie\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py

plugin init time: 0.199804

loading bindings

loading pointer bindings

found 1 files for base name Default.sublime-theme

theme loaded

app ready

pre session restore time: 0.321274

startup cache, total files: 99 cache hits: 99

startup time: 0.363478 (package setup was not run)

loaded 837 snippets

Package Control: Skipping automatic upgrade, last run at 2014-08-07 19:47:06, next run at 2014-08-07 20:47:06 or after

Regards,
```

mostie

**Comment by mazhariqbal49** [comment]
Add your git binary (.exe) path in your git settings (Preferences > Package Settings > GitGutter > Settings - Default) 

LIKE: 
// Custom path to git binary when not in PATH
"git_binary": "C:\\Program Files (x86)\\Git\\bin\\git.exe"

NOTE: Your path should have double backslashes '\\' as a directory separator.
