### ISSUE TITLE
Not working on Win7 with ST3

### ISSUE THREAD

**Issue by flybayer** [jisaacks/GitGutter#191]
I freshly installed ST3 (Build 3065) on a new Windows 7 machine and copied over the contents of my "Sublime Text 3" folder from  C:...\AppData\Roaming\ from my previous development machine (also Windows 7). Everything is working except for GitGutter.
- I tried removing and re-installing GitGutter via package control but it still does not work.
- I am setting the path to the binary in the user settings file for GitGutter.
       `"git_binary": "D:/bin/git.exe"`
- I'm also using the "Git" plugin and am setting the binary path exactly the same and that works fine.
- There are no errors showing in the console. 
- I have tried disabling other gutter plugins. 
- I'm using the default settings for GitGutter
- Toggling non_blocking (and restarting ST3) had no effect.

**Comment by mazhariqbal49** [comment]
Add your git binary (.exe) path in your git settings (Preferences > Package Settings > GitGutter > Settings - Default) 

LIKE: 
// Custom path to git binary when not in PATH
"git_binary": "C:\\Program Files (x86)\\Git\\bin\\git.exe"

NOTE: Your path should have double backslashes '\\' as a directory separator.

**Comment by jisaacks** [comment]
Is this still an issue?

**Comment by Plasmatium** [comment]
@jisaacks, I have insert several print functions in "git_gutter_events.py" "view_collection.py" "git_gutter_handler.py", when i edit these files i found that the gutter works correctly. I also found the files in Gitgutter's package directory could invoke the correct gutter display, other files not in the Gitgutter package directory all failed.

I found that a condition is not satisfied in git_gutter_handler.reset: self.git_path. When editing files in Gitgutter package directory, the value of self.git_path is the file name currently editing. When editing files not in that directory,  self.git_path is false

Could you give any suggestions? i just start learning python

**Comment by Plasmatium** [comment]
I'm sorry i misunderstand the purpose of this plugin. From watching behavior of the plugin & adding print function of the code i learned the plugin serving the code with git-utilized. At first i thought the plugin compared the disk file against buffer. i submited this github account just looking for the solution of this issue. Now i have created a git repository and the plugin worked perfectly :-)
