### ISSUE TITLE
Icons are very small on high-res display

### ISSUE THREAD

**Issue by Draknek** [jisaacks/GitGutter#199]
This computer has a stupidly large screen resolution, which means that the icons are too small to be noticeable really:

![image](https://cloud.githubusercontent.com/assets/184057/5081317/0e6c6d8e-6ec6-11e4-8052-821add4db703.png)

**Comment by bfred-it** [comment]
This might a a Windows-only issue, GitGutter works well on retina Macs. 

![gitgutter on retina display](https://cloud.githubusercontent.com/assets/1402241/5888337/bd13ee34-a3af-11e4-922a-61b88ac387ae.png)

**Comment by digitalnature** [comment]
Can we get an option to adjust icon size?

**Comment by jisaacks** [comment]
@digitalnature the icons are images, I do not think sublime supports that, so the only way would be to have multiple images at different sizes that the user can choose from, or to programmatically scale the images in python, neither of which do I really see as necessary. What issue are you having?

**Comment by digitalnature** [comment]
I think they are too small
![windows 7 @ 125% font size](https://cloud.githubusercontent.com/assets/99317/10177642/cd91c84a-6703-11e5-93bd-fcc6421fea93.PNG)

**Comment by Zanion** [comment]
Way too small (3200x1800 Win10)

@bfred-it 
-webkit-min-device-pixel-ratio: 2.0
dpi: 192
dppx: 2.0

![ss](https://cloud.githubusercontent.com/assets/3114590/10208355/a89639ca-6787-11e5-8756-5cfbc4aee7bf.png)

**Comment by bazzilic** [comment]
Same issue here. Sublime 3, Windows 10 running on a retina Macbook Pro.

**Comment by DVLP** [comment]
Same problem. I'm running on Windows 10, XPS 15 with only HD resolution(not even 4k version) and icons are tiny.

**Comment by ShirajG** [comment]
Same issue here running Arch, with the `dpi_scale` option in sublime text 3 set to 2.0

**Comment by bcrotty** [comment]
I have the same issue. GitGutter is unusable for me with icons this hard to see.

**Comment by deathaxe** [comment]
Is fixed by PR #361

**Comment by deathaxe** [comment]
GitGutter 1.5.0 comes with support for custom themes.

By default it provides two themes, which can be activated via settings.
- Default.gitgutter-theme
- Default HiDPI.gitgutter-theme

This should solve this issue until ST supports correct upscaling all resources.
