### ISSUE TITLE
How can I figure out why this isn't working?

### ISSUE THREAD

**Issue by ashmoran** [jisaacks/GitGutter#20]
I've just installed this (and restarted Sublime – not usually necessary) but it doesn't display anything. I'm definitely in a Git repo, I'm working in my project folder for this: https://github.com/ashmoran/language_implementation_patterns

I don't know how to debug the problem, can anybody help?

**Comment by DHedgecock** [comment]
Just worked through this on Windows 7 using ST3. This worked for me:
Add this to Environment Path(assuming this is where you have Git installed):
C:\Program Files (x86)\Git\bin
Love this plugin by the way! --Thanks!
