### ISSUE TITLE
Unexplained slow performance on Windows 8.1

### ISSUE THREAD

**Issue by shssoichiro** [jisaacks/GitGutter#208]
I have used ST3 with GitGutter for quite some time, on multiple platforms (Windows, Mac OS X, and Linux including in VMs) and in general have no issues with performance. However, on my Windows 8.1 box, about a month ago, I began experiencing unresponsiveness from typing in Sublime Text. I would only have 2-3 files open at a time, with 1-2 projects being tracked in the sidebar. Last night I had two files open (one HTML, one JS, neither being more than 150 lines), both of which were tracked in a Git repo, and Sublime Text would take up to 2 minutes to respond whenever I tried typing or even clicking in the window. Restarting Sublime Text and deleting the ST session file did nothing. After uninstalling GitGutter, however, Sublime Text is running smoothly again. I don't have this issue on my Mac OS box that I use regularly with GitGutter, and I didn't have this issue on my Windows box until 1-2 months ago.

**Comment by danielpall** [comment]
Getting input lag on ST3 with GitGutter on Windows 7, same behavior as @shssoichiro describes above. Input lag fixed when GitGutter plugin was removed.

**Comment by rvdkooy** [comment]
I have 2 windows 8.1 boxes with the same problem. everything worked fine again when removing the plugin

**Comment by pecigonzalo** [comment]
Have the same performance issue on 8.1 and 10

**Comment by last1here** [comment]
having the same issue as above on windows 10 preview, even when `non_blocking` is set to `true`

**Comment by Stibbons** [comment]
Same here

**Comment by lovebear** [comment]
ST3 3065, Windows 8.1
Same issue with input lag

**Comment by Sleigh7** [comment]
Can confirm, same issue as above with ST3 3065 & Windows 8.1.

**Comment by rwod** [comment]
st3, win8.1 

  "non_blocking": true,
  "live_mode": false

same issue.

**Comment by DavidLGoldberg** [comment]
maybe something to do with the tempfile code (not sure that's still in the code base)

**Comment by hiepnhl** [comment]
GitGutter and GG-Edge didnt even work on my system: Windows 8.1 x64, Sublime Text 3083. 
No debug console error:
![gitgutter](https://cloud.githubusercontent.com/assets/5542627/7295097/1fc5a734-e9dd-11e4-8929-7c359252147c.png)

Git binary was set: "C:\\Program Files (x86)\\Git\\bin\\git.exe". Default setting.
And there is no effect at all :(. What should I do?

**Comment by rbialon** [comment]
OS X 10.10.3 with ST 3 Build 3083 and latest GitGutter via PackageControl here, having the same settings as @rwod and the same issue: There is a delay of about one or two seconds when typing, moving the cursor or deleting letters.
Typing in the Console or Command Palette works as expected (no delay).
Also there is no output on the Console giving any hints whatsoever.

**Comment by michaeljonathan** [comment]
+1
ST3, Windows 8.1, non_blocking is true and live_mode is false
HP HDX 16
Typing lag is occassional (hence not a big deal), but whenever I click my mouse, the click registers a fraction of a second late, usually after the position of the cursor has actually moved since, which causes me to begin typing in the wrong places, experience weird ST3 UI quirks... :(

**Comment by rchl** [comment]
Dup of #230.
