### ISSUE TITLE
GitGutter does not show up

### ISSUE THREAD

**Issue by xenidev** [jisaacks/GitGutter#211]
Hello,
I am new to Sublime I installed GitGutter but it does not show up on ST3 ( Windows). 
How can I fix it?

**Comment by jisaacks** [comment]
Have you tried setting the git path?

**Comment by xenidev** [comment]
No. As far as I understand I have to install msysgit first. Is this correct?  I just read this: http://blog.countableset.ch/2012/06/07/adding-git-to-windows-7-path/

**Comment by jisaacks** [comment]
Take a look at the READ ME, there is a section on setting the [git path](https://github.com/jisaacks/GitGutter#git-path)

**Comment by xenidev** [comment]
>>GitGutter assumes that the git command is available on the command line. If it's not, add the directory containing git.exe to your PATH environment variable. Then clone the repo...>>>

How can I try a git command? And where should I clone it?

cd "%APPDATA%\Sublime Text 2\Packages"
git clone git://github.com/jisaacks/GitGutter.git

 At the moment my User Settings is empty.

**Comment by jisaacks** [comment]
@xenidev you are referencing the instructions for installing GitGutter on windows. You previously have said that git gutter is already installed though. I think you should be reading the part about adding the get_binary to your git gutter settings. Read this part [here](https://github.com/jisaacks/GitGutter#git-path). Also you do not want to set it in your user settings, but your settings specifically for git gutter. Read [this part](https://github.com/jisaacks/GitGutter#settings).

**Comment by sigod** [comment]
> Could you recommend something to read?

http://git-scm.com/doc

> 1. I have to install Git but in order to do it I need to install msysgit first.

You can download Git here: http://git-scm.com/. I always choose `Use Git from Git Bash only` and everything is working fine.

> If git is not in your PATH
> How do i know?

You may examine PATH variable. Or just open Window's console and type `git`. You should know by output of this command whether Git is in your PATH or not.

> Where can I do it? Preferences-Package Settings-GitGutter-Settings User?

Yes. Don't forget to replace `\` with `\\`.

> to the location of the git binary, e.g. in a portable environment;
> Where is it?

Apparently, where Git is installed. In my system it is `c:\Program Files (x86)\Git\bin\git.exe`.

**Comment by xenidev** [comment]
Thank you! Git is installed. In my system it is c:\Program Files\Git\bin\git.exe. 
I added git binary code into my git gutter-user settings but it is still not working.

![15-01-2015 15-40-10](https://cloud.githubusercontent.com/assets/10789312/6026453/2646f95c-abec-11e4-8e30-904f7081d2ae.jpg)

Does this look right?

**Comment by sigod** [comment]
Yes. There's only one moment left: you have to use Git. GitGutter shows you the difference between current edited version of the file and the version that is stored in the Git repository (version which corresponds to the HEAD pointer, since there's can be a lot of versions of the same file). Therefor files must be tracked by Git.

You can use `"show_markers_on_untracked_file": true`, which I find very handy. Note that it works only if file is inside of the Git repository.

**Comment by xenidev** [comment]
Thank you! I have started learning Git. What I have done:
1.installed Git.
2. created my website’s folder  repository
3. Added <em>"show_markers_on_untracked_file": true” </em> to my sublime settings file.

![preferences sublime](https://cloud.githubusercontent.com/assets/10789312/6047620/e8e65ae6-acbb-11e4-91f7-d536b58e58b2.jpg)


It is still not working but I do no know what the HEAD pointer is and how to work with it. So, I need to read about it to frame my questions.

**Comment by sigod** [comment]
> Added "show_markers_on_untracked_file": true” to my sublime settings file.

It's a GitGutter's option, so you must place it into GitGutter's settings file.

> It is still not working but I do no know what the HEAD pointer is and how to work with it.

What I meant was "version of which Git thinks that it is a current version (i.e. version you currently work with)". Read something like [this][0], it should help you to start with Git.

Also, I noticed little yellow dots on your screenshot. Do you have some plugin installed that draws them? There's a slight chance it's conflicting with GitGutter. 

[0]: http://backlogtool.com/git-guide/en/

**Comment by xenidev** [comment]
Actually, the dots color is  white. I have the following packages installed: Bracket Highlighter, Color Highlighter, Emmet, GitGutter, PYV8 (this one was per-instaled), Style Token, Package Resource Viewer. I think this white dot is coming from the Bracket Highlighter. Thank you for the link!

**Comment by xenidev** [comment]
Done! Thank YOU so much!

**Comment by greengerong** [comment]
@xenidev   How to resolve it? remove  Bracket Highlighter?

Thanks.

**Comment by genius00xp** [comment]
Thanks. This thread helps me.

**Comment by usumoio** [comment]
Thanks guys this thread helped me fix pretty much the same issue.

**Comment by felipebadaro** [comment]
Hi guys,

Im having a similar problem. Im trying to install git gutter on sublime text 2, Windows 10. 
I already make the cmd recognize git commands using the path of a portable version of git. But, when I install the package a message shows saying that "path problem". Since cmd is already running git commands, what more I have to do to make git gutter work? I tried to edit the package settings and nothing works. Everything I do seems wrong, I get an error message, and sublime wont open anymore. I always have to end the task, delete the folder of the package and open sublime again. Can somebody help me?
