### ISSUE TITLE
GitGutter isn't working on OSX Sublime Text 3

### ISSUE THREAD

**Issue by daniisco** [jisaacks/GitGutter#215]
Hey!

I'm a new MAC owner and installder Sublime yesterday. I've installed Gitgutter and the mac fix path but it still doesn't work. What do I do?

**Comment by daniisco** [comment]
Anyone?

**Comment by jisaacks** [comment]
Have you installed git? Did you try setting the `git_path` directory?

**Comment by daniisco** [comment]
I've installed Git yeah, I dont know what git_path is to be honest. I'm all new with MAC, Sublime and programmaring overall.

**Comment by daniisco** [comment]
Anyone who can give me a really complete guide what im gonna do to make this work. I really want this useful plugin :)

**Comment by daniisco** [comment]
Please help me :)

**Comment by jisaacks** [comment]
Ok first thing you want to do. Read the [read me](https://github.com/jisaacks/GitGutter) for this repo. It has some help. It explains the git path. Then if you are still stuck. Comment again and let me know what you have tried so that I may have some idea how to help you.

**Comment by daniisco** [comment]
I have read everything several times and in different forums. I'm n00b in computers, sublime and in mac so i don't understand. What I can tell you is I've installed Git, Gitgutter and MAC path and it doesn't work. I dont seem to have a Gitgutter folder in the Sublime directory. 

When i type "which git" inte terminal I get /usr/bin/git. I don't understand what "git path" is, where i'm gonna copy/paste different things and so on. I would appreciate every help I can get.

**Comment by TSiege** [comment]
Had this same issue with my computer running Sublime Text 3.  Manually setting the git path variable in the `GitGutter.sublime-settings` file.  This file can be accessed via clicking on the top navbar `Sublime Text` > `Preferences` > `Package Settings` >  `GitGutter` > `Settings - User` and adding
```json
{
  "git_binary": "/usr/local/bin/git"
}
```
running `which git` in terminal will give you the path you need to replace `"/usr/local/bin/git"` if it's different (be sure to use double quotes).

@daniisco: See above for steps.
@jisaacks: You were right; this fixed it for me. You could probably close this issue.

**Comment by daniisco** [comment]
@TSiege I have copied that in user-settings but it still doesn't work for me. It's still /usr/bin/git in terminal :/

**Comment by TSiege** [comment]
@daniisco your system git might be too old or something.  Install [homebrew](http://brew.sh/) by running this command `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` in your terminal and then run `brew install git` when that's done create a new tab in your terminal and run `which git` again.  That should say `/usr/local/bin/git` and you should be good to go.

**Comment by daniisco** [comment]
@TSiege It's still /usr/bin/git ohhh i'm getting so frustraded.

**Comment by TSiege** [comment]
@daniisco it needs to be `/usr/local/bin/git` not user `/usr/local/bin`.  That's a directory not a binary. Restart your sublime after you make that change.

**Comment by daniisco** [comment]
@TSiege Okey, it is /usr/local/bin/git now. But I don't see any icons when i change my code ini Sublime with Gitgutter.

**Comment by Nannooskeeska** [comment]
I'm also having this issue on my Mac. I've changed the appropriate setting and I don't see anything in the gutter when I change a file. Do my files have to be pushed to my repository before it will work?

**Comment by iq-dot** [comment]
I also have the same, could this be related to themes? For reference I use Oceanic Next

**Comment by CaptainVincent** [comment]
Do you try to git init your project and commit the file you edit.

**Comment by blainefricks** [comment]
I changed the `git_binary` to `/usr/local/bin/git` and that seemed to fix the problem. However, there is some lag while waiting for the icons to show up.

**Comment by rchl** [comment]
Issue with wrong `git_binary` path. Readme also mentions to install a package that should fix it without modifying `git_binary` setting.
Closing.

**Comment by luxueyan** [comment]
I use this way to fix the problem. When you update xcode, you can use cmd 'sudo xcodebuild -license' and then agree it.
