### ISSUE TITLE
gitgutter-edge empty default preferences file

### ISSUE THREAD

**Issue by JeanMertz** [jisaacks/GitGutter#220]
It looks like the default preferences file for `gitgutter-edge` is missing. When opening through the preferences menu, a new (empty) file is created.

Uninstalling and installing non-edge version shows the preference file existing for that version. I presume edge is looking in the wrong directory?

**Comment by deathaxe** [comment]
This is hard to fix as the path in the Main.sublime-menu is fixed. This would require to dynamically create a Main.sublime-menu file for settings.

**Comment by jisaacks** [comment]
I don't want to support gitgutter edge. It doesn't follow any releases. It just points directly to master. It's a way to try out new features. If you want something more solid, install regular gitgutter.

I am also fine with just deprecating gitgutter-edge all together and use pre-releases which sublime text supports.
