### ISSUE TITLE
Git submodules break git gutter

### ISSUE THREAD

**Issue by chrisdopuch** [jisaacks/GitGutter#221]
If you are coding in a repo that has a submodule, changes to the files in the submodule will not work correctly with git gutter. Steps to reproduce:
1. Clone a git repo that relies on git submodules
2. Run git submodule init && git submodule update
3. Modify a file in the submodule
4. Check sublime text, there will be no gutter icons for your change

**Comment by rchl** [comment]
Please comment in #290 if you still see this issue.

**Comment by oferei** [comment]
Re #290 I want to add that the behavior is different. As I noted there, I see gutter icons on the entire file.
