### ISSUE TITLE
Invalid Sign text in AIX

### ISSUE THREAD

**Issue by sivaswami** [jisaacks/GitGutter#224]
Hi I am trying vim with AIX with Gitgutter plugin
I am getting the error message:
Error detected while processing function gitgutter#highlight#define_signs..gitgutter#highlight#define_sign_text:
Line 4:
Invalid sign text:@
Any suggestions ?

**Comment by jisaacks** [comment]
Please open an issue with **vim-git-gutter**. This is the _Sublime_ version.
