### ISSUE TITLE
lines with Emoji is always marked as changed

### ISSUE THREAD

**Issue by timdream** [jisaacks/GitGutter#225]
I have not yet look into the code to see how `git` is called from the plug-in, but it looks like to be a similar issue to http://stackoverflow.com/a/28260108/519617

**Comment by rchl** [comment]
With what content do you reproduce that and what encoding the file is in?

I've tried with this content in a file encoded with utf8:
```
# $ git log --oneline
# 93a1866 <U+1F43C>

# $ git --no-pager log --oneline
# 93a1866 🐼
```
After committing no lines appear as changed.

**Comment by timdream** [comment]
This bug has been fixed already on the latest version of GitGutter! Thanks.
