### ISSUE TITLE
Distinguish untracked and ignored files

### ISSUE THREAD

**Issue by maliayas** [jisaacks/GitGutter#226]
`show_markers_on_untracked_file` setting affects both untracked files and ignored files. I think there should be another setting for ignored files like `show_markers_on_ignored_file`. Because you usually (if not always) don't want to see markers on ignored files. Status bar notification maybe, but not gutter markers.

Thanks.

**Comment by sigod** [comment]
+1 for idea

**Comment by jisaacks** [comment]
I think if you don't want to see markers on ignored files, odds are you don't want to see them on untracked files either (since in both these cases they do not tell you anything about your edits just that the file is in fact ignored/untracked.) I don't see any compelling reason to make the user have to change 2 settings.

**Comment by maliayas** [comment]
Agreed. So maybe we should put a statusbar indicator for both.

On the other hand, I think "untracked" indicator should be more noticeable than the "ignored" indicator in some way. But I don't know how.

**Comment by jisaacks** [comment]
@maliayas I would not be opposed to adding it to [show_status](https://github.com/jisaacks/GitGutter/blob/master/GitGutter.sublime-settings#L43-L49).

**Comment by maliayas** [comment]
Makes sense. But with its current string based style, it may become inflexible. Maybe there should be an array like this?

    status_info: ["diff_stats", "branch", "ignored_flag", "untracked_flag"]

**Comment by jisaacks** [comment]
@maliayas I would prefer an object:

```javascript
"status_info" {
  "lines_changed": true,
  "branch": false,
  // etc. 
}
```

**Comment by maliayas** [comment]
I love the discussion :) Is object ordered in python? With array, users may change the order of the items.

**Comment by maliayas** [comment]
Hi. Is there any improvement on this?

`[UNTRACKED]` and `[ignored]` badges could be added to the status bar for this purpose. Note the emphasis via case.

**Comment by jisaacks** [comment]
This isn't something I have had time to work on. It's not high on my list of priorities. However, it shouldn't be a very difficult thing to do if you (or anyone else) want to take a stab at it.

**Comment by maliayas** [comment]
Ok, thanks. I may give it a try.

**Comment by deathaxe** [comment]
GitGutter 1.5.0 shows file status in the status bar, if jinja2 library is available.

So I set `"show_markers_on_untracked_file": false` to hide the icons and use the status message.

Is that ok?
