### ISSUE TITLE
Cursor not placed correctly when giving panel focus with click

### ISSUE THREAD

**Issue by KrunchMuffin** [jisaacks/GitGutter#231]
Please see [this thread](https://github.com/SublimeTextIssues/Core/issues/833) on the Sublime Text issue tracker as I thought it may have been a core issue.

**Comment by jisaacks** [comment]
Hmm, It works the same for me when I disable/enable git gutter. It always makes me make an extra click. The first click will activate the window, the next will position the cursor. However I am using `OSX` not Windows.

**Comment by rchl** [comment]
I can't reproduce this problem on Windows but I wonder if it might have been a problem with GitGutter blocking the UI on tab focus and blocking cursor placement due to this. #321 should help if it is still a problem.

**Comment by rchl** [comment]
I'll assume that async invocations fixed this for those users who had the problem. At least in ST3.
For ST2 I don't think it's worth spending time on it.
