### ISSUE TITLE
Donate to project

### ISSUE THREAD

**Issue by wjdp** [jisaacks/GitGutter#237]
Spotted the latest changelog with a link to "Sublime Text Power User" book discount in order to support this project.

I'd like to support development, but would rather do so directly. A donate link or some other service (I'm not very clued up on these) would be nice.

**Comment by jisaacks** [comment]
Thanks so much for wanting to support git gutter. I am thrilled that people enjoy it that much. If you want to make a donation, you can use [square cash](https://cash.me/) my username is `$jisaacks`. However, I do not want to obligate you to in anyway. I love open source and I love giving to the community and I do not expect anything back in return. I would also be just as happy with you making your donation to any charity of your choice! :)

Thanks again, cheers!

**Comment by jisaacks** [comment]
Hey @wjdp, I was tired when I wrote that last night and I hope I didn't come across the wrong way. I didn't mean to sound like a donation wouldn't be appreciated. It would. I just didn't want to come across as *asking for* donations. I hope that makes sense.
