### ISSUE TITLE
Performance degradation in 1.2.1

### ISSUE THREAD

**Issue by printercu** [jisaacks/GitGutter#238]
Hi! After last update gitGutter became a little slower. There are gutter refresh delays up to 1sec. It's noticeable when changing branches and then switching between tabs.

Does anybody else faced this?
Is there any config option to tune this behaviour?

**Comment by Lochlan** [comment]
+1 I have noticed this as well.  At first I thought it was an issue localized to my own box, but I've seen this across every device/platform I've used so far.

**Comment by jisaacks** [comment]
Yes, git gutter was switched to have non blocking on by default. This causes gitgutter to not run while you are typing but waits until you are finished typing to run. You can turn this off in the settings by setting `"non_blocking": true`

**Comment by printercu** [comment]
Thanks, this works for me!

PS. I need to restart sublime after changing this setting, to make it work.
