### ISSUE TITLE
Indicator in file into sidebar

### ISSUE THREAD

**Issue by alfredobarron** [jisaacks/GitGutter#241]
Folder color indicating whether a line has been inserted, modified or deleted into sidebar

**Comment by jisaacks** [comment]
Is this a feature request? I am not aware of an API in sublime that would allow it.

**Comment by jiayihu** [comment]
+1 Would be even nicer if file names have a different color when they are new or modified, but I don't know if that is possible.

**Comment by jisaacks** [comment]
I am going to close this as not possible. If someone discovers an API that would allow that, or if a new API gets added that would allow this, feel free to reopen. I would like it as a feature as well. It was an original goal but could not find an API that would allow it in a sensible way without resulting to major hackery of theme files.
