### ISSUE TITLE
Live_mode isn't working on Windows7 ST2

### ISSUE THREAD

**Issue by LoicTouzard** [jisaacks/GitGutter#245]
Hi,
I just installed the plugin, and keeping the default settings (so live_mode = true) doesn't work.
Each character I type generate an error in my ST2 console : 

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 205, in on_activated
  File ".\sublime_plugin.py", line 154, in run_timed_function
  File ".\sublime_plugin.py", line 204, in <lambda>
  File ".\git_gutter_events.py", line 61, in on_activated
  File ".\git_gutter_events.py", line 81, in debounce
Boost.Python.ArgumentError: Python argument types in
    sublime.set_timeout(function, NoneType)
did not match C++ signature:
    set_timeout(class boost::python::api::object, int)
```

The diff works when I call it manually. But doesn't refresh when I type.
Does someone have any clue about where it could be from ? And how to solve this ?

**Comment by switz** [comment]
+1 for ST2 on Mac

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 205, in on_activated
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 204, in <lambda>
  File "./git_gutter_events.py", line 61, in on_activated
  File "./git_gutter_events.py", line 81, in debounce
Boost.Python.ArgumentError: Python argument types in
    sublime.set_timeout(function, NoneType)
did not match C++ signature:
    set_timeout(boost::python::api::object, int)
```

**Comment by asetGem** [comment]
+1 for ST2 on Mac too
same output in my console as the 2 previous posts

**Comment by spademan** [comment]
cuz your git in setting file don't be set in correct way 

preferences-->PackageSettings-->git gutter -->setting defualt 

 
set 
```
"git_binary":  "/usr/local/bin/git"  // the  path of git  
```

**Comment by nickgnd** [comment]
The git folder location may change. Use `which git` command from shell to locate it, in my case: 
```bash
~  which git
/usr/bin/git
```

and then update gitgutter settings as @spademan said: 

```json
{
  "git_binary": "/usr/bin/git"
}
```

**Comment by rchl** [comment]
The error suggests that None was passed to set_timeout. The code just passes `settings.get('debounce_delay')` there so if that returns None it can probably only mean that default settings from `GitGutter.sublime-settings` were not found. Can you investigate a bit? Maybe check if Git gutter settings menu item opens the right file? Also you can check using `sublime.active_window().active_view().settings().get('debounce_delay')` in the console if it returns expected value. Also same for other settings that plugin supports.

**Comment by rchl** [comment]
Although it would be pretty easy to make the code more resilient to such breakage by providing a default value in that case.

**Comment by JohnEmhoff** [comment]
`>>> print sublime.active_window().active_view().settings().get('debounce_delay')`
`None`

Looks like it's not getting the settings? The path to the settings file seems to be `Library/Application Support/Sublime Text 2/Packages/GitGutter/GitGutter.sublime-settings`

**Comment by deathaxe** [comment]
The debounce timer value is read from settings with default value provided. This way a valid value is passed to the timer under all circumstances.
