### ISSUE TITLE
Every time I save in ST3, a git.exe terminal pops up quickly then disappears

### ISSUE THREAD

**Issue by mmcintyre123** [jisaacks/GitGutter#246]
While not a huge problem, it is rather annoying and for some reason does not happen on my other Windows machine, which as far as I can tell has the same setup and the same PATH configuration (except C:\Program Files\Git\bin is the only thing in my user PATH on that machine).

I just did a fresh install of Git for Windows 64-bit (Latest source Release 2.5.0) at
https://git-scm.com/downloads  
Release Notes: https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.5.0.txt

and I am using Sublime Text 3

The other strange thing, is that when GitGutter automatically checks for changes in the file (which I notice after committing and pushing changes, then going back to the file, as the change marks in the sublime gutter disappear), it does NOT cause the git.exe terminal to pop up.  It only does that when saving.
  
Here is the "About" associated with my Git Bash terminal in case it sheds any light on this.  I had the same problem with Git 1.9.5.
  
![gitabout](https://cloud.githubusercontent.com/assets/12388285/9339237/e8a779d6-45b6-11e5-97c0-726f3501c375.png)
  
Any fix to this including not letting the git.exe terminal popup every time I save would be much appreciated!  
  
(Note... I use ST3 in Ubuntu as well ... same machine in a VM ... and this doesn't happen there).

**Comment by dscho** [comment]
Isn't the problem this line: https://github.com/jisaacks/GitGutter/blob/be3d2037baf653e1ed158880bd4f1a5f878fe822/git_gutter_handler.py#L259

It should use `CREATE_NO_WINDOW` as `creation_flags` parameters in the [`Popen`](https://docs.python.org/2/library/subprocess.html#popen-constructor) constructor, I guess.

**Comment by mmcintyre123** [comment]
So change 
   startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
to
   startupinfo.dwFlags |= subprocess.STARTF_CREATE_NO_WINDOW

?  I'll try it and see what happens...

**Comment by mmcintyre123** [comment]
Great, thanks dscho!  If someone who is an admin could make that change to the repo, that would be great - and I'm sure many would appreciate it!  I would clone the repo and try it myself, but I have only been able to get the package to work properly via Package Control.

Thanks in advance!

**Comment by dscho** [comment]
@mmcintyre123 you should first test the suggested change, and if it works, craft a commit message and make a Pull Request. This is Python, you should be able to edit the file in place.

**Comment by mmcintyre123** [comment]
@dscho 
Once again thank you for your help here.  I am new to Github and coding generally, so not exactly sure how this worked.

I was able to fork the project so I can edit the file and hopefully test it out... 

So based on your suggestion my research turns up the following...

http://stackoverflow.com/questions/2935704/running-shell-commands-without-a-shell-window
http://bytes.com/topic/python/answers/757271-subprocess-popen-spawning-cmd-shells

This is a bit of a stab in the dark but here's what I plan to try (not at the right machine at the moment to test it out)...
Using the bytes.com construction but the actually Microsoft value 0x08000000, change https://github.com/jisaacks/GitGutter/blob/be3d2037baf653e1ed158880bd4f1a5f878fe822/git_gutter_handler.py#L255-L262

from        
    def run_command(self, args):
        startupinfo = None
        if os.name == 'nt':
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        proc = subprocess.Popen(args, stdout=subprocess.PIPE,
                                startupinfo=startupinfo, stderr=subprocess.PIPE)
        return proc.stdout.read()
to
    def run_command(self, args):
        CREATE_NO_WINDOW = 0x08000000
        startupinfo = None
        if os.name == 'nt':
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        proc = subprocess.Popen(args, stdout=subprocess.PIPE,
                                startupinfo=startupinfo, stderr=subprocess.PIPE, 
                                creationflags=CREATE_NO_WINDOW)
        return proc.stdout.read()

Will report back with the results!

**Comment by dscho** [comment]
@mmcintyre123 this looks exactly how I would have changed it. Since you already have Sublime Text installed, maybe you can find the file `git_gutter_handler.py` in the installation somewhere? If you can, it would make sense to change it in-place (after making a backup copy, of course :smiley:) and then test it directly in Sublime Text, probably it will only be effective after restarting the editor. :+1:

**Comment by mmcintyre123** [comment]
So I managed to manually clone my fork into the \AppData\Roaming\Sublime Text 3\Packages directory (uninstalled my old version), and after rebooting it's working like before, but the save behavior is still the same :-(  
  
Yes that would be nice! Unfortunately though in ST3 packages installed via package control are encrypted(?) - they come in .sublime-package files and look like
504b 0304 1400 0000 0800 1974 1447 2a5d
e88f c700 0000 2f01 0000 0a00 0000 2e67
6974 6967 6e6f 7265 354f bb6e c330 0cdc
.....

Now that I have the pckg working (minus this issue) I can try some things. is there anything here you would recommend?
http://bytes.com/topic/python/answers/757271-subprocess-popen-spawning-cmd-shells

I tried a bunch of different things here.. about all I can think of.  I tried removing everything from my PATH except for C:\Program Files\Git\mingw64\bin; tried the following as well:

```Python
    def run_command(self, args):
        # CREATE_NO_WINDOW = 0x08000000
        startupinfo = None
        if os.name == 'nt':
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        # proc = subprocess.Popen(args, stdout=subprocess.PIPE,
        #                         startupinfo=startupinfo, stderr=subprocess.PIPE, creationflags=0x08000000)
        proc = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, creationflags=0x08000000, shell=False)
        return proc.stdout.read()
```
tried with and without shell=False, tried putting shell=False, creationflags=0x08000000, as the first arguments after "args", tried using 0x08000000 directly in the Popen constructor .... all to no avail.  Mrown at that link uses something different than "args"... could there be something there?

**Comment by mmcintyre123** [comment]
Strangely the shell does not pop up on my machine at home.  No idea why.  It's also Windows 7, although Home Edition whereas this is Professional.

**Comment by sigod** [comment]
@mmcintyre123, same Git version?

**Comment by mmcintyre123** [comment]
Nope, I have 1.9.5 at home -- BUT I had 1.9.5 here until just a few weeks ago, and had the same problem with that.

**Comment by mmcintyre123** [comment]
I do have some other developer-ish things installed here, like chocolatey, pear, phantomjs, PHP, Python, all of which (except Python) add to my PATH.  However I did try removing everything from the user PATH except for Git (which is at the front), as that is my home setup, but still the same problem.

I am looking into doing a totally clean install of Windows soon anyway, so if there is no obvious solution I'll see if that solves it.

**Comment by mmcintyre123** [comment]
So finally I found the source... sorry for the confusion here!  This seems to have been caused by GitStatus.  I've removed that and my issue seems to be solved.  I will comment in GitStatus so people who use it can see the suggestions here.  Thanks to all for the help!
