### ISSUE TITLE
Temporary files are not removed

### ISSUE THREAD

**Issue by borntyping** [jisaacks/GitGutter#247]
The temporary files created to compare the buffer against the file in git are never removed, resulting in `/tmp` being filled with multiple copies of files that have been edited.

**Comment by jisaacks** [comment]
What OS are you using?

**Comment by borntyping** [comment]
Linux Mint 17.2, Sublime Text 3083, Git Gutter 1.2.1.

**Comment by Wintaru** [comment]
This happens to me in Debian Jessie. Very annoying, I don't close Sublime Text or reboot my machine very often and my sysadmin brought it to my attention that there were hundreds of source files littering my /tmp folder.

**Comment by rchl** [comment]
Will mark as dup of #284 as that one has more information.
