### ISSUE TITLE
Does not support Worktree from Git 2.5+

### ISSUE THREAD

**Issue by nj** [jisaacks/GitGutter#248]
When editing code in a [worktree](https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows), all lines appears as "new" (`+`'s) and not the actual changed lines within a file.

`git status` shows the expected value, so it's only wrong within Sublime.

Tested on `Sublime v3 build 3083` and `GitGutter v1.2.1`

**Comment by jisaacks** [comment]
Thanks for pointing this out.

> Please note that the worktree feature is experimental. It may have some bugs, and its interface may change

I think I may wait for it leave it's experimental phase and lock in it's interface before adding code to support it.

**Comment by vsimon** [comment]
The worktree feature has rounded out since the git 2.5 days. Would this be a better time to support this? (I've found the feature itself to be super useful).

**Comment by deathaxe** [comment]
I prepared a fix to run all git commands from within the working tree, which is published as soon as all required PRs are accepted.

This implicitly enables work-tree support.

**Comment by deathaxe** [comment]
Should work with GitGutter 1.5.0 Please check

**Comment by deathaxe** [comment]
As submodules work work-trees also do. It's the same mechanism.
