### ISSUE TITLE
Annoying error message in a non-git project

### ISSUE THREAD

**Issue by Thomasdezeeuw** [jisaacks/GitGutter#251]
I sometimes don't work with git, for example in a folder where I'm just testing some smalls things. Because of this GitGutter places a very long error message in the bottom bar, along the lines of: `git branch: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.`. This error message pushed other, more useful, information away. This error message is probably from git itself and GitGutter simply passes it on, but it's very annoying.

Would it be possible to detect if git is not used and turn GitGutter off?

**Comment by jisaacks** [comment]
> Would it be possible to detect if git is not used and turn GitGutter off?

So there is already a [function](https://github.com/jisaacks/GitGutter/blob/master/git_helper.py#L14-L23) that checks looks for the root of the git repo and returns false if not found.

I thought there was code in place someone to stop executing if that were the case, but I am not seeing it now.

I do not get that error when I just tried it out myself though.

**Comment by Thomasdezeeuw** [comment]
I've since restarted my editor and it seems to work.
I might know what caused the problem. I was first working in a git directory, then added a non-git folder to the Sublime project (outside of the initial git directory). Then when editing within that non-git directory I got the error. Does that function work for two root directories within a single project? That might have caused the problem.

**Comment by jisaacks** [comment]
> Does that function work for two root directories within a single project?

@Thomasdezeeuw that shouldn't effect it, it searches for the git repo on a per file bases, it does not care about projects. 

If you are able to reproduce this error or do any more digging I would appreciate it! :)

**Comment by Thomasdezeeuw** [comment]
Well it seems to work again, so I'll close the issue and open it once I've seen it again, thanks.
