### ISSUE TITLE
Sublime Text 3 lags with Git Gutter Enabled

### ISSUE THREAD

**Issue by KroniK907** [jisaacks/GitGutter#257]
Hello,

Have been trying to figure out what has made Sublime so slow recently and pinpointed GitGutter as the problem. It seems that when GitGutter is running there is about a 1 second lag where Sublime freezes completely when I switch between two or more tracked files. This can be very annoying as it sometimes screws up my clicks or when I try to drag a tab to a new column etc. I tried disabling live mode, but that did nothing. Sometimes I will find it also freezes when adding a new icon to the gutter

Thanks for a great plugin but I would love to see this fixed. Am disabling for now.

**Comment by sigod** [comment]
Hi. You might want to try changes from this PR: #240.

**Comment by KroniK907** [comment]
This does indeed appear to be what I am experiencing. Due to the weird windows error, im not sure I am willing to jump onto that version quite yet, but it does look promising. I might give it a try in a separate environment

**Comment by bofm** [comment]
It really makes my Sublime behave like PyCharm

**Comment by mgansler** [comment]
Any update on this? Anybody found a workaround?

**Comment by rchl** [comment]
Dup of #230.

**Comment by rootwork** [comment]
That issue is about lags when editing files over a network. I don't know about the other folks in this thread, but I was not editing files over a network. I was editing them locally, and there was still a lag -- so as far as I'm concerned, this was not a dupe of #230. In fact it was so bad I've abandoned GitGutter for now.

If others were also experiencing the lag locally, maybe this issue is worth reopening.

**Comment by rchl** [comment]
I think it's most likely the same. The lag exists also when using GitGutter locally. It's less noticeable typically, but it both depends on file system, size of repository and platform so mileage may vary.

**Comment by jisaacks** [comment]
I agree. I think we should leave this closed for now and once #230 is fixed, if this is still a probably it should be reopened then.

**Comment by atstockland** [comment]
This seems to be still relevant in v 1.11.3.  I had to remove GitGutter due to how laggy it made ST3.
