### ISSUE TITLE
Git Gutter not working on Win 7 SB3

### ISSUE THREAD

**Issue by roccomuso** [jisaacks/GitGutter#259]
I've installed the Git Gutter from the Package Control. This is the error I'm having in the console:

    Traceback (most recent call last):
      File "./subprocess.py", line 1112, in _execute_child
    FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

But I'm able to see GitGutter in the Command Palette..

I'm running SB3 with the Material Theme on Windows 7.

**Comment by sigod** [comment]
Probably same as #223.

**Comment by roccomuso** [comment]
Yeah, solved thanks.
It was a Path issue.

I've putted in Preferences > Packages Settings > GitGutter > Settings - User: 

        {
      "git_binary": "C:\\Program Files (x86)\\Git\\bin\\git.exe"
    }
