### ISSUE TITLE
ignore_whitespace with value "eol" ignores any symbol at the end of line

### ISSUE THREAD

**Issue by zimenskiy** [jisaacks/GitGutter#261]
If I add or remove 1 symbol at the end of line or replace last symbol with another single symbol than no marker added to the gutter if `ignore_whitespace` is set to `eol`. If I change the `ignore_whitespace` value to `none` then I can see the diff-marker.

**Comment by deathaxe** [comment]
Bug no longer exists with 1.5.0.

If I set `"ignore_whitespace": "eol"` and remove the last character of a line or modify it, the gutter icons show correctly.

**Comment by zimenskiy** [comment]
Still have the issue even with 1.5.0 (Sublime build 3126).  
I've tried to reinstall the plugin via Package Control and restart SublimeText with no effect.

**Comment by deathaxe** [comment]
Can you provide any examples, please?

I tried to remove a letters from the last word of of lines and also replaced them by other ones. Both result in gutter icons being displayed as expected.

The `ignore_whitespace: eol` setting is translated to git command-line arguments and passed to `git diff -U0 --no-color --no-index --ignore-space-at-eol ...` which actually does the job of diffing.

GitGutter then parses the unified diff output to extract the changed hunks.

So I am really interested in what may cause this issue?

**Comment by zimenskiy** [comment]
I made a gif showing how it does work on my editor:
![gitnodiff](https://cloud.githubusercontent.com/assets/1793381/23941925/a8cfae8e-097b-11e7-951f-3bf41e6c186c.gif)

As you can see adding, removing and editing lines works pretty fine but when I try to edit the only last symbol then no diff is shown.

**Comment by deathaxe** [comment]
I can't reproduce. Works great for me here.

What OS and git are you using?

I checked on Win10 x64 / Linux x64 using git 2.10.0+ I am on git 2.12.0 at the moment. Works for ST2 and ST3.

GitGutter creates 2 temp files per view. One with content of the view and one from git. They are named like _git_gutter_xe342_ and live within the default temporary folder. 

Could you copy those 2 files with one symbol replaced at the end of line and do the follwing 2 checks?

1. Compare manually to check, whether the replaced symbol is within one of the files.
2. Run `git diff -U0 --no-index --ignore-space-at-eol --patience <file1> <file2>` to check, whether your git diff returns the line as modified?

Considdering the change after 'ru': the output should contain something like this:

```
@@ -10 +10 @@
-				case 'ru':
+				case 'ru';
```

**Comment by zimenskiy** [comment]
That `git diff ...` command doesn't work for me. Simple `git diff` shows the changes.
Anyway, I was using git version 2.6 and upgrade to 2.12 version solved the issue.
Sorry for disturbance and thank you!
