### ISSUE TITLE
Broken Menu File

### ISSUE THREAD

**Issue by wbond** [jisaacks/GitGutter#264]
https://github.com/jisaacks/GitGutter/blob/master/Main.sublime-menu#L3-L56

These menu entries add blank top-level menus on OS X with ST3 build 3095.

**Comment by jisaacks** [comment]
Thanks for pointing this out, Will. I am currently on 3083 it appears to be working in this build. I Wonder what has changed. I will update ST and take a look when I can.

**Comment by rchl** [comment]
@wbond Do you still see this problem? I don't see anything like that on macOS Sierra. The file you pointed to doesn't seem to have any problems to me. But then it always points at master so it might not longer show what you tried to show.
