### ISSUE TITLE
GitGutter running on non-repository files

### ISSUE THREAD

**Issue by JonathanHolvey** [jisaacks/GitGutter#266]
I've noticed that GitGutter still sets the status bar string `Comparing aginst: HEAD` even if the current file isn't in a Git repository.

**Comment by jisaacks** [comment]
Thanks for reporting. yeah #267 would most likely be the same bug/fix. There is a check for the `.git` folder, there probably just needs to be a way to short circuit and not draw or saw anything in the case it is not found.

**Comment by rchl** [comment]
Yep, will close as duplicate of #267.
