### ISSUE TITLE
Files outside git still marked as new

### ISSUE THREAD

**Issue by jcranendonk** [jisaacks/GitGutter#267]
Files in a location that does not have a .git directory in any of its parent directories are still marked as 'inserted', regardless of the value of 'show_markers_on_untracked_file'.

This is using git v2.6.2 and GitGutter v1.2.2.

My current user settings for GitGutter are:

``` json
{
    "git_binary": "/usr/local/bin/git",
    "show_status": "none",
    "show_in_minimap": false
}
```

**Comment by JonathanHolvey** [comment]
Presumably related to #266

**Comment by jisaacks** [comment]
Thanks for reporting.

**Comment by jcranendonk** [comment]
@jisaacks If there's anything I can do to help fix this issue, let me know! I'd be happy to help.

**Comment by jisaacks** [comment]
@jcranendonk yeah, I gave an idea for a possible solution in #266. I would welcome a PR. You may have to poke around a bit to figure out what is going on, but this is a good starting point: https://github.com/jisaacks/GitGutter/blob/6f3d9783aec01ac5efc8456bfe78c5fcdc6dec0c/git_gutter_handler.py#L50-L52

**Comment by rchl** [comment]
Can't really see this problem on 1.3.0. Was it maybe fixed at some point?

**Comment by rchl** [comment]
Can't even see this problem in version this was reported for (1.2.2).

**Comment by rchl** [comment]
While I don't see the 'added' mark on such files, I've looked at the code and it is indeed invoking git which is pointless. So definitively a bug.

**Comment by deathaxe** [comment]
I prepared a fix to disable git_gutter if the open file is not part of a git repository, which is published as soon as all required PRs are accepted.
