### ISSUE TITLE
Git Gutter and SVN

### ISSUE THREAD

**Issue by tcpluess** [jisaacks/GitGutter#270]
Would it be possible to make a combined plugin which also handles SVN?
Automatically detect whether a file is under svn or git version conntrol, and then update the gutter accordingly. It should be possible to implement this, but I am unsure where to start, some help would be appreciated.

**Comment by jisaacks** [comment]
There was a fork for this some time ago: https://github.com/bradsokol/VcsGutter I do not know if it is maintained anymore.
