### ISSUE TITLE
How to customize colors in editor

### ISSUE THREAD

**Issue by josecanciani** [jisaacks/GitGutter#278]
I'm using a dark theme ("theme": "Material-Theme.sublime-theme") for sidebar and tabs, but a light theme for the editor ("color_theme": "SciTE (SL).tmTheme"). because I find it easy on my eyes to use a lighter background where I'm directing my eyes the most. I've attached a file.

I find it hard to see the markers on changed lines (in the screenshots I've change the lines 2-4 and added one on line 5 for you to see). 

I there a way to configure how you can see the colors in the Editor only? I want them to popup more.

Also, please add your config to the Material theme which is great :)

Thanks!
Jose
![mysublimescreen](https://cloud.githubusercontent.com/assets/2751542/15637019/e72b3542-25e5-11e6-9552-6823597c30ad.png)

**Comment by rchl** [comment]
Please see the bottom of the Readme on https://github.com/jisaacks/GitGutter
