### ISSUE TITLE
Non-modified lines marked as new

### ISSUE THREAD

**Issue by tnq177** [jisaacks/GitGutter#280]
Hi there,

I notice this behavior recently. I'm not sure at what length of the file does this behavior start to appear, but my file is around ~1500 lines. When I add new lines in, the some part of the old lines above the new lines got marked as new too. Anyone else with this issue? It's not a big deal though, just wanna raise a voice.

Thanks

**Comment by sigod** [comment]
That's probably OK. Just a small artifact of Git's diff algorithm.

**Comment by rchl** [comment]
I agree. I think we have to live with it.
