### ISSUE TITLE
Compare against specific commit Enhancement

### ISSUE THREAD

**Issue by suiwenfeng** [jisaacks/GitGutter#281]
1. commits listed should come from file change history and order by commit time.
2. filter commit by commit id not only commit message.

**Comment by jisaacks** [comment]
@suiwenfeng makes sense. is it something you'd be interested in working on?

**Comment by deathaxe** [comment]
Should this replace the 'Compare against Commit' or is a new 'Compare against File Commit' command prefered.

As the compare target is saved per directory now, both makes sense, somehow. First solution is easer - needs only two lines of code being changed. Could be included in PR #343
