### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by deathaxe** [jisaacks/GitGutter#284]
Today I found thousands of files in my TEMP folder on Windows 10 x64. I found SublimeText 3114 and GitGutter to be the creator of all that files. As soon as I open a tracked file within a git repository, GitGutter creates two temporary files, but they are never deleted.

With a look into code I found GitGutter to make use of python's _tempfile_ object for comparison of the view's content and git.

According to pythons [documentation](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) the method being used to create the tempory files _tempfile.NamedTemporaryFile_ deletes the created temporary file as soon as it is closed.

The conclusions are:
1. At least on Windows, the function does not work as documented - files are not deleted. Even if I explicitly add the _delete=True_ argument, files are not deleted.
2. If the function would work as documented, GitGutter could not as everytime the temporary file is closed, it would be deleted, what happens after each update of the file content.
3. I guess, you should explicitly call _tempfile.NamedTemporaryFile(delete=False)_ and manually delete all temporary files eigher with on_close event or on exit of SublimeText.

I managed to handle this with `entombedvirus's` fork of GitGutter by adding:

> class GitGutterHandler: 
>     ...
>     def **del**(self):
>         try:
>             os.unlink(self.git_temp_file.name)
>             os.unlink(self.buf_temp_file.name)
>         except:
>             pass

This clears the files as soon as a view is closed.

I am not sure what your intention with the static class ViewCollection is and when to clean files here. Unfortunatelly the above mentioned patch does not work for your GitGutter.

Can you have a look onto this bug, please?

**Comment by rchl** [comment]
I've checked my temp directory and found 52000 git_gutter* files there :)

Soon hopefully the ViewCollection will be gone so we can make nicer fix for this.

**Comment by rchl** [comment]
I have tried this in S3 console and it worked fine though. File was deleted.

```
>>> import tempfile
>>> t=tempfile.NamedTemporaryFile(prefix='aaa_test_')
>>> t.write(b'foo')
3
>>> t
<tempfile._TemporaryFileWrapper object at 0x00000193069A8A90>
>>> t.close()
```

Also tried with `with` in a small "plugin":
```
import sublime
import tempfile

tt = tempfile.NamedTemporaryFile(prefix='aaa_test_')
with tt:
  tt.write(b'foo')
```
In that case file is deleted immediately by the `with` construct so this shouldn't be used in GitGutter if file is to live longer.

I think the clean solution that just calls `close()` on the file object from the on_close event should just work. But it will be easier to do with the rewrite that is currently pending.

**Comment by deathaxe** [comment]
I never made to completely solve this problem. No matter what I tried, sometimes files keep existing in the temp directory. I managed to find out why. Git ist started in the background with the tempfile name as argument. If then a view is closed before git is done, deleting the tempfile in a on_close() may fail hence the file not yet exists. As soon as git finishes it creates that file, but GitGutter doesn't know about that, as the reference to the view is no longer valid. So you would need a way to mark a view as pending, if git runs in the background to eighter cancel git or queue the temp file for deletion as soon as git has finished.

**Comment by rchl** [comment]
That should be solvable but that it is a bit of a corner case that wouldn't be as important as removing temporary files in normal cases, IMO.

**Comment by israel-oye** [comment]
> Today I found thousands of files in my TEMP folder on Windows 10 x64. I found SublimeText 3114 and GitGutter to be the creator of all that files. As soon as I open a tracked file within a git repository, GitGutter creates two temporary files, but they are never deleted.
> 
> With a look into code I found GitGutter to make use of python's _tempfile_ object for comparison of the view's content and git.
> 
> According to pythons [documentation](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) the method being used to create the tempory files _tempfile.NamedTemporaryFile_ deletes the created temporary file as soon as it is closed.
> 
> The conclusions are:
> 
> 1. At least on Windows, the function does not work as documented - files are not deleted. Even if I explicitly add the _delete=True_ argument, files are not deleted.
> 2. If the function would work as documented, GitGutter could not as everytime the temporary file is closed, it would be deleted, what happens after each update of the file content.
> 3. I guess, you should explicitly call _tempfile.NamedTemporaryFile(delete=False)_ and manually delete all temporary files eigher with on_close event or on exit of SublimeText.
> 
> I managed to handle this with `entombedvirus's` fork of GitGutter by adding:
> 
> > class GitGutterHandler:
> > ...
> > def **del**(self):
> > try:
> > os.unlink(self.git_temp_file.name)
> > os.unlink(self.buf_temp_file.name)
> > except:
> > pass
> 
> This clears the files as soon as a view is closed.
> 
> I am not sure what your intention with the static class ViewCollection is and when to clean files here. Unfortunatelly the above mentioned patch does not work for your GitGutter.
> 
> Can you have a look onto this bug, please?

The `NamedTemporaryFile()` class in Python really has odd behaviour even when delete is set to false and I run a `NamedTemporaryFile().close()`, it does not work but the boolean value, `NamedTemporaryFile().closed` is true
If I try to delete the file with the `os` module, it throws a `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:`
