### ISSUE TITLE
Git Renaming Feature

### ISSUE THREAD

**Issue by TimZaman** [jisaacks/GitGutter#292]
1. GitGutter is awesome. The most useful plugin i have installed across all my devices in ages.

Although a _very_ minor bug, if you can call it that at all, it does not account for renamed files with `git mv`. I would expect it to understand renamed and not handle it as a new file (it adds '+' before each line)

**Comment by jisaacks** [comment]
I think this is just the way git works. When you do a `git mv` then do a `git diff` doesn't it still show all lines as new? I could be wrong.

**Comment by TimZaman** [comment]
Yes, you are right in that a `git diff` will not show you anything.. _at all_ when a file as been `git mv`-ed. There are some options to see force it to show you the diff but they might up mess other things if you'd incorporate those. (this would show it: `git diff HEAD^ HEAD`).
