### ISSUE TITLE
Plugin doesn't work after git update.

### ISSUE THREAD

**Issue by kirillkostko** [jisaacks/GitGutter#293]
First of all, thank you for the great plugin. I've found that it doesn't work after I updated git to the new version. Could you please check it?

```
$ git --version
git version 2.9.2.windows.1
```

**Comment by jisaacks** [comment]
The `windows` in the version name is weird. Have you set the [git path](https://github.com/jisaacks/GitGutter#git-path)?

**Comment by sigod** [comment]
I've just updated Git and I've the exact same version now. GitGutter still works for me.

> The `windows` in the version name is weird.

That's quite standard now.

**Comment by kirillkostko** [comment]
@jisaacks @sigod thank you guys! Setting ```"git_binary"``` helped me.
