### ISSUE TITLE
Turn off MESSAGEBOX!!!!!!!!

### ISSUE THREAD

**Issue by Seraphli** [jisaacks/GitGutter#297]
After I open sublime, it just auto installed GitGutter, and message boxes KEEP COMING!!!! I can't even remove this package! It stop me from inputting any command, and after I delete the local package, it installs AGAIN!!!!! What the hell?! Damn this stupid thing!

**Comment by Seraphli** [comment]
I had it removed by setting "ignored_packages".

**Comment by absay** [comment]
It seems the package was upated today and it broke Sublime's functionality. I can't even uninstall it.

**Comment by sigod** [comment]
How bizarre. OS? Sublime's version?

**Comment by Seraphli** [comment]
Windows, Sublime Text 3

**Comment by sigod** [comment]
What version exactly? 3114?

It looks more like a bug in Sublime/Package Manager.

**Comment by Seraphli** [comment]
3065.

**Comment by sigod** [comment]
You've mentioned messages boxes. What was written in them?

If you unignore GitGutter will it start spamming you again? What if you update Sublime?

@absay What version of Sublime Text do you use? Also, look at the questions above.

**Comment by Seraphli** [comment]
Message about "Git Binary Path".
I just ignored it and removed it. I never tried that. But I think it will pop up until it finds git path.
It is nothing to do with Sublime.

**Comment by sigod** [comment]
Probably. But I don't get this message boxes. It just silently reports in the console.

**Comment by Seraphli** [comment]
Really? Look at this!
https://github.com/jisaacks/GitGutter/blob/7dcbbfa201c0c96d2497fce0e152f8a02848416d/git_gutter_handler.py#L291
And

> error_message(string)	 Displays an error dialog to the user.

https://www.sublimetext.com/docs/3/api_reference.html

Now, do you still think that way?

**Comment by sigod** [comment]
Oh, I see. For some reason it doesn't get called for me.

Introduced in #242.

@jisaacks @johnburnett ping

**Comment by jisaacks** [comment]
@sigod it should only get called if it cannot find `git`, which might explain why you are not seeing it.

> Now, do you still think that way?
> You should REALLY check your code, AND REPLY!

@Seraphli gitgutter is free software, everyone who spends time working on it does so for free. I am sorry this caused you an issue but we can resolve it politely.

We probably need to either kill the message dialog, or make it a status text, or rate limit how many times it can be called, maybe once per session.

Is this something you would be willing to work on @Seraphli ?

**Comment by sigod** [comment]
> it should only get called if it cannot find git, which might explain why you are not seeing it.

Yes, I guessed that because now GitGutter works even without setting `git_binary`. I tried setting incorrect path, but it just silently dumps error messages into the console.

**Comment by Seraphli** [comment]
Once per session is really a good idea.

**Comment by jrappen** [comment]
@jisaacks The problem that people are angry about isn't the error message itself, the problem is that once you click `OK` on the error message popup, it comes up again right away. Sublime Text is unresponsive that way and updating `ignored_packages` takes a couple times getting rid of that popup. Maybe you could disable the plugin until Sublime Text starts the next time instead when git isn't found?

**Comment by Seraphli** [comment]
@jrappen That's right! You can't get away from error message dialogs.

**Comment by jisaacks** [comment]
Just cut a release to fix this. If you update please report back if it is resolved for you :)

**Comment by nicbou** [comment]
I'm dealing with the same problem. I cannot open Package Manager or do anything in the 3 second window between popups, so it effectively rendered Sublime unusable for me.

Is there something I can do to at least disable the plugin while waiting for an update? For the record, I am using Sublime Text 3 on OS X.

Thanks for your work @jisaacks

**Comment by nicbou** [comment]
It seems to have silently updated on start this morning, so the issue is not happening anymore. Thank you!
