### ISSUE TITLE
Small typo in release notes

### ISSUE THREAD

**Issue by leesavide** [jisaacks/GitGutter#299]
![tem.jpeg](https://i.ytimg.com/vi/_YTOtjEk6ks/maxresdefault.jpg)
See [GitGutter/release_messages/src/messages/1.2.3.txt](https://github.com/jisaacks/GitGutter/blob/master/release_messages/dest/1.2.3.txt):
- Better cleanup of `{~~temfiles~>tempfiles~~}`

**Comment by rchl** [comment]
Fixed by linked pull request.
