### ISSUE TITLE
Ads in my editor

### ISSUE THREAD

**Issue by KishCom** [jisaacks/GitGutter#300]
This isn't cool at all. Changelogs by default popup in Sublime and do so because they may contain breaking changes that you might want to know about. It's not OK to use them to post ads for other products and services.

https://github.com/jisaacks/GitGutter/blob/master/release_messages/dest/1.2.3.txt#L18

(_At least_ ensure the changelog is not 50%+ an ad, maybe lose the ASCII banner)

**Comment by jisaacks** [comment]
I am sorry this upsets you. I did a lot to make sure that the message is always on the bottom of the change log and only shows up once per update (it will always be in the last x.x.x file.) I tried to make this as unobtrusive as possible. Also I don't cut releases that often, this was the first time in months. If this is still unacceptable to you, feel free to look into alternatives to GitGutter.
