### ISSUE TITLE
GitGutter popup appears every few seconds making Sublime Text 3 unusable

### ISSUE THREAD

**Issue by Daedalon** [jisaacks/GitGutter#302]
Opened my Sublime Text 3 today. It opens a text file "Package Control Messages - GitGutter - Thanks for installing Git Gutter!!!". No idea why this happens, I've had GitGutter installed for a long time. Ok, fine, I close this.

However, it's hard to even close this window, because something else makes my Sublime Text 3 now unusable: a popup by GitGutter. It says "Your Git binary cannot be found. If it is installed, add it to your PATH environment variable, or add a `git_binary` setting in the `User/GitGutter.sublime-settings` file."

This popup appears every few seconds, making Sublime Text 3 completely unusable. I tried uninstalling this by pressing Ctrl-Shift-P for Package Control, and then choosing Uninstall, and then choosing GitGutter. I don't have time to do more than 3 keystrokes after opening Package Control before the popup reappears, closing the dialog I just had opened.

I tried deleting C:\User\%user%\AppData\Roaming\Sublime Text 3\Installed Packages\GitGutter.sublime-package. After opening ST3, things appear normal for a moment, but then this package seemingly reinstalls itself, and the editor is unusable again.

Requests:

1. Advise how to get rid of this. I'll probably figure this out in a while, but as I didn't see a previous thread about this among the current 72 open issues, it's good to put this on the record.

2. Update the package to not open the popup more than once per session.

**Comment by jisaacks** [comment]
Thanks for bringing this up. This is already reported in #297 We are going to try to fix this ASAP.

**Comment by Daedalon** [comment]
Thanks for the quick reply! That #297 does not have the most descriptive title, so hadn't noticed it.

Got the package removed by closing Sublime, deleting it from the directory as mentioned above, then opening Sublime, pressing Ctrl-Shift-P and typing "Re" and selecting Remove package. This needed to be done in the 5-10 seconds before the package reinstalls itself. When that happens, it cannot be removed yet, but after closing ST and reopening it once again, Ctrl-Shift-P now shows Remove package as one of the first options (it remembers the typed "Re" from last time), and it's possible to select Remove before the popup appears. After the popup appears, it doesn't close that Remove dialog, so one just needs to find GitGutter there and click it once.

As a side note, the spamming of exclamation points ("!!!") and writing GitGutter occasionally as "Git Gutter" with an extra space did not improve the impression of the plugin. Both were written in the automatically opened "Thanks for installing" text file that then proceeded to advertise some deals. I don't mind being informed of the deals once upon install, but they might sell more and the users would be happier if the plugin does not seem to be yelling at them ("!!!") or being uncertain of itself (GitGutter or Git Gutter).
