### ISSUE TITLE
Icons after the GitGutter updating change on the default.

### ISSUE THREAD

**Issue by Kristinita** [jisaacks/GitGutter#307]
By default I have very small icons. I establish own icons as it is written in [this answer](https://github.com/jisaacks/GitGutter/issues/199#issuecomment-227016698), but after the Git Gutter updatings of an icon again change on the default. What do I have to make that custom icons didn't change on default after the GitGutter updatings?

Thanks.

**Comment by r-stein** [comment]
You are using ST2?

**Comment by Kristinita** [comment]
@r-stein, no. Sublime Text 3 Build 3114. Thanks.

**Comment by sigod** [comment]
> What do I have to make that custom icons didn't change on default after the GitGutter updatings?

Nothing. Whole package is overwritten on update. The issue ifself must be addressed.

**Comment by rchl** [comment]
This is expected behaviour. If you are modifying the package then your changes will be lost on upgrade.

As for the too small icons there is #199 specifically for it so I'll close this issues.

**Comment by Kristinita** [comment]
@sigod, @rchl , is bad behavior. GitGutter updates many times and each time I need change icons, because default icons very small.

Maybe, you add setting `icons_path_folder`? Users can write own value, for example, 

```json
"icons_path_folder": "E:\Sublime Text 3\Data\Packages\User\GitGutterIcons"

**Comment by rchl** [comment]
I'm not sure if it's possible with current API but, in any case, there is #256 for implementing support for custom icons so you might wanna watch it. I might have a look later to check if it's possible to load resources from outside the package.

BTW. Can you show a screenshot how it looks for you with default icons? I wonder if you think that default icons are too small or you have hit a bug with HiDPI where icons are abnormally small.

BTW2. Have you tried https://packagecontrol.io/packages/PackageResourceViewer to extract image resources and modify them? Using this package preserves directory structure so it might just work fine with updates this way.
