### ISSUE TITLE
Icons in new tooltip too small

### ISSUE THREAD

**Issue by braver** [jisaacks/GitGutter#308]
![screen shot 2016-08-29 at 09 52 21](https://cloud.githubusercontent.com/assets/2543659/18044460/542cd8aa-6dce-11e6-9b36-2f60b6b8860c.png)

The icons are really hard to read with the code at a not-abnormal 11px.

**Comment by r-stein** [comment]
I am looking forward to make the styling more flexible. I will also include the button styling and increase the size by default.

**Comment by braver** [comment]
Cool, the new features are pretty exciting!

**Comment by r-stein** [comment]
You can modify the font size by modifying the [css file](https://github.com/jisaacks/GitGutter/blob/1.4.0/gitgutter_popup.css#L9) in version `v1.4.0`.
