### ISSUE TITLE
`non_blocking` functionality *may* be broken in the latest release

### ISSUE THREAD

**Issue by happycollision** [jisaacks/GitGutter#310]
I work with files on a network server. My local `git` has to talk over a Samba (CIFS, actually) connection to analyze the contents of the `.git` folder in my project. Not ideal, but not my choice.

Since the last release of GitGutter, Sublime has been intermittently freezing up on me for upwards of 10 seconds at a time, after which the GitGutter symbols often update and I can type again. Seems to be the same amount of time it takes to get results from `git status` over this non-ideal setup.

I don't know exactly what is causing this issue, but since GitGutter is the only thing that changed recently that I know of, that is my guess.

FWIW: Sublime 3 build 3114, Mac OS X El Cap 10.11.6

**Comment by rchl** [comment]
Dup of #230.
