### ISSUE TITLE
No gutter icons are showing any more

### ISSUE THREAD

**Issue by oferei** [jisaacks/GitGutter#314]
They've all disappeared.  :[
Is it just me? I've recently installed Sublime build 3126. And before that 3124 (I think that's when it stopped working.)

**Comment by sigod** [comment]
Just updated. It still works on Windows 7. What's your OS?

**Comment by r-stein** [comment]
Can you check, whether GitGutter is enabled? If not just enable it again.
Several people got problems with the update disabling packages.

**Comment by oferei** [comment]
yes, it's enabled.

**Comment by r-stein** [comment]
Do you have any gitgutter related errors on the console(``ctrl+` ``), when starting sublimetext or when you input `window.run_command("git_gutter", {"force_refresh": True})`?

**Comment by oferei** [comment]
No errors.

Only this on startup:

> reloading plugin GitGutter.git_gutter
> reloading plugin GitGutter.git_gutter_change
> reloading plugin GitGutter.git_gutter_compare
> reloading plugin GitGutter.git_gutter_events
> reloading plugin GitGutter.git_gutter_handler
> reloading plugin GitGutter.git_gutter_popup
> reloading plugin GitGutter.git_helper
> reloading plugin GitGutter.view_collection

**Comment by r-stein** [comment]
You also don't have something like `Comparing against: HEAD, Inserted: 3, Modified: 4` in the status line?

Sometimes it helps to remove a package and install it again via PackageControl.

**Comment by oferei** [comment]
I have these messages, each time I switch tabs.

**Comment by r-stein** [comment]
If you see that in the status line it seems to be a problem with adding the stuff to the gutter. Not sure what the problem is though.

**Comment by eshinn** [comment]
Just had the same thing happen on mine and got it working. Steps taken:
1 Cmd+Shift+P and 'Package Control Remove Package --> GitGutter'
2 Realize sublime crashed hard...force quite restart
3 Noticed that GIT itself wasn't noticing a branch, I typed `git status` and received:
  ```
  Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
  ```
4 Run `sudo git status` and agree to the terms in terminal.
5. Cmd+Shift+P and 'Package Control Install Package --> GitGutter'
6 ¯\(°_o)/¯ 
7 Profit

**Comment by oferei** [comment]
Thanks @eshinn, that was it!    $)

**Comment by oferei** [comment]
btw, GitGutter would be even more awesome if it detected this and displayed an error to the user. or at least in the console.

**Comment by eshinn** [comment]
@oferei Welcome

**Comment by jisaacks** [comment]
> Just had the same thing happen on mine and got it working. Steps taken:
> 1 Cmd+Shift+P and 'Package Control Remove Package --> GitGutter'
> 2 Realize sublime crashed hard...force quite restart
> 3 Noticed that GIT itself wasn't noticing a branch, I typed git status and received:

>   Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
> 4 Run sudo git status and agree to the terms in terminal.
> 5. Cmd+Shift+P and 'Package Control Install Package --> GitGutter'
> 6 ¯(°_o)/¯ 
> 7 Profit

I believe this would still work without the uninstall/reinstall GitGutter steps.

**Comment by debugger22** [comment]
Hi guys,

I ran into the same issue the previous day when I updated my Sublime Text 3 on macOS Sierra Public Beta.

The symbols are not showing up anymore.

Does the following log helps?
```
>>> window.run_command("git_gutter", {"force_refresh": True})
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 496, in on_modified_async
    callback.on_modified_async(v)
  File "git_gutter_events in /Users/sudhanshu/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 47, in on_modified
  File "git_gutter_events in /Users/sudhanshu/Library/Application Support/Sublime Text 3/Installed Packages/GitGutter.sublime-package", line 93, in debounce
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 247, in set_timeout_async
    sublime_api.set_timeout_async(f, timeout_ms)
TypeError: an integer is required (got type NoneType)
```

**Comment by debugger22** [comment]
It got fixed by installing `Fix Mac Path`.
