### ISSUE TITLE
Next / previous change keyboard shortcuts not working on OSX El Capitan

### ISSUE THREAD

**Issue by incompl** [jisaacks/GitGutter#316]
They type  and Ô characters instead.

**Comment by rchl** [comment]
Which keyboard layout are you using?

**Comment by incompl** [comment]
Macbook Pro US English

**Comment by rchl** [comment]
It does actually work for me in macOS Sierra. Do you have GitGutter entries `Previous Change` and `Next Change` in Sublime's menu and do those have the same shortcuts assigned?

<img width="268" alt="git-gutter-options" src="https://cloud.githubusercontent.com/assets/153197/20247426/4882e17c-a9cc-11e6-9b9a-b1e25edcf049.png">

Also does Goto menu entry blink when you use one of those shortcuts? If not then maybe you have some application installed that takes over those shortcuts and does its own action.

**Comment by rchl** [comment]
In any case, if the problem does not affect most macs then I don't think it's worth doing anything about that. You can always just add your own shortcuts that work for you.
Just add those to your keyboard Keybindings in sublime and modify to your liking:
```
    { "keys": ["super+shift+option+j"], "command": "git_gutter_next_change" },
    { "keys": ["super+shift+option+k"], "command": "git_gutter_prev_change" },
```

**Comment by deathaxe** [comment]
The issue is caused by keyboard mapping issues related to ST itself. It's nothing GitGutter can fix.
