### ISSUE TITLE
Unable to install on ST3, build 3126, Win10

### ISSUE THREAD

**Issue by aronhelser** [jisaacks/GitGutter#317]
I was unable to install GitGutter using package manager because of this failure (from the console):
`Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' is not available
Package Control: The dependency 'python-jinja2' could not be installed or updated
`
I installed the 'Jinja2' package with package control, and then GitGutter installed successfully:
`Package Control: The dependency 'python-jinja2' is not currently installed; installing...
reloading /C/Users/me/AppData/Roaming/Sublime Text 3/Packages/User/Package Control.sublime-settings
Package Control: The dependency 'python-jinja2' has successfully been installed or updated
`

Thought you'd want to know. IDK what you might do about it, though?

**Comment by r-stein** [comment]
We essentially use the same dependencies as [BracketHighlighter](https://github.com/facelessuser/BracketHighlighter) and many more packages. Also the [Jinja2 Package](https://github.com/wbond/package_control_channel/blob/master/repository/j.json#L533) and the [Jinja2 dependency](https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json#L383) are different things. In contrast to the most other packages the jinja2 dependency is hosted on bitbucket and not on github. Therefore I would assume it was a temporary server and not an Package Control or configuration problem.
Thanks for the issue anyway :)
