### ISSUE TITLE
Does not work with SourceTree's embedded git binary (Windows 10)

### ISSUE THREAD

**Issue by silentzawr** [jisaacks/GitGutter#322]
I'm using SourceTree 1.9.6.1 with embedded git 2.8.1. I tried pointing GitGutter to SourceTree's git.exe binary via GitGutter.sublime-settings, however nothing seemed to change. SourceTree's git.exe is located under `%USERPROFILE%/AppData/Local/Atlassian/SourceTree/git_local/bin/git.exe`.  

Is `git.exe` all that is needed?

**Comment by r-stein** [comment]
Has it started to work with SourceTree or have you installed an other git binary?

**Comment by silentzawr** [comment]
Thanks, I should have clarified that. It started working after a system reboot rather than just Sublime. Nothing else was changed between restarts.
