### ISSUE TITLE
There are more instances of GitGutterSettings than one

### ISSUE THREAD

**Issue by rchl** [jisaacks/GitGutter#334]
This:
```
    from git_gutter_settings import settings
```
doesn't work like I expected. It evaluates the `git_gutter_settings.py` file in the context of the importee and thus we end up using different instances of `GitGutterSettings` in different parts of the code. That is generally not a big problem apart when using flags like `self._git_binary_path_error_shown` where we rely on there being only one instance of `GitGutterSettings`.

I'm not sure what's the typical way of creating singletons in Python but that doesn't seem to be the right way.

**Comment by r-stein** [comment]
As far I know there is one set of moduls, which is initially loaded and an other set, which is used if you reload a module (e.g. work on it and save it or update it).
This could be avoided by using `from GitGutter.git_gutter_settings import settings`, but this would be problematic with the edge version.
In addition we could try in the `git_gutter_settings.py` something like (I haven't tested it):

``` py
if "settings" not in globals():
    settings = ...
```

**Comment by rchl** [comment]
IMO we don't really need to handle case when GitGutter code is modified. That's an edge case that should only affect GitGutter developers.
It would be enough that various git_gutter_*.py files use the same instance which is currently not the case.

**Comment by rchl** [comment]
Your suggestion using global() seems to work. And the global doesn't seem to leak to other packages so it seems safe.
