### ISSUE TITLE
Unable to locate module [jinja2]

### ISSUE THREAD

**Issue by magnetikonline** [jisaacks/GitGutter#366]
Hey JD,

   love your work on this plugin - one of my "must haves" when using ST3.

But have noted since release https://github.com/jisaacks/GitGutter/commit/2cc9a1a9e780e9280480c6c17d80c214af5c1245 I'm getting a Python module error as follows:

```startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/magnetik/Library/Application Support/Sublime Text 3/Packages
state path: /Users/magnetik/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/magnetik/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.193298
using gpu buffer for window
first paint time: 0.247873
using gpu buffer for window
using gpu buffer for window
startup time: 0.302103
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin GitGutter.git_gutter
Traceback (most recent call last):
  File "/Users/magnetik/Library/Application Support/Sublime Text 3/Packages/GitGutter/git_gutter.py", line 12, in <module>
    from .git_gutter_show_diff import GitGutterShowDiff
  File "/Users/magnetik/Library/Application Support/Sublime Text 3/Packages/GitGutter/git_gutter_show_diff.py", line 2, in <module>
    from jinja2.environment import Template as Jinja2Template
ImportError: No module named 'jinja2'
```

Have tried `pip install jinja2` without success too.

Rolling back to a prior commit, e.g. https://github.com/jisaacks/GitGutter/commit/730356dc7aea280e45f0e06e9fe638671e469097 - everything springs back to life.

OS is OS X - 10.11.6

Thanks

   Pete

**Comment by r-stein** [comment]
Press ctrl+shift+p and execute the command with the entry "Package Control: Satisfy Dependencies". Which ST build are you using?

**Comment by deathaxe** [comment]
I may add a check for successful jinja2 import and temporary disable status bar text module until dependencies are satisfied. This error may occure if GitGutter is loaded the very first time without jinja2 package being installed yet.

**Comment by mlabarca** [comment]
I had the same problem on Ubuntu/ST3, rolling back to 730356d also did solve it  for me.

**Comment by r-stein** [comment]
Satisfy dependencies does not work?

**Comment by mlabarca** [comment]
Unfortunately it didn't, only rolling back solved it.

**Comment by r-stein** [comment]
Which ST build are you using?

**Comment by mlabarca** [comment]
Build 3126

**Comment by deathaxe** [comment]
For investigation I just started ST3 without any packages under Linux. After installing Package Control and GitGutter as the only packages I see `python-jinja2` and `markupsafe` dependencies not beeing installed.

It's Package Control which doesn't parse the `dependencies.json` correctly and therefore ignores the moved packages.

```js
{
    "*": {
        "*": [ // ignored by Package Control
            "markupsafe",
            "python-jinja2"
        ],
        ">=3080": [ // installed by Package Control
            "pygments",
            "python-markdown",
            "mdpopups"
        ]
    }
}
```

**Comment by r-stein** [comment]
See #368 for the fix. It is parsed correctly, but it only uses the most specific entry.

**Comment by deathaxe** [comment]
@mlabarca : We added a fix so required dependencies should install now. Can you give it a try?

**Comment by mlabarca** [comment]
@deathaxe Seems to work now straight from master. Thanks!

**Comment by magnetikonline** [comment]
Hey @deathaxe / @mlabarca seems you have been doing all the work!

I just did a `git pull` on master on my home system (Linux/Ubuntu 16.04 running ST3 b/3126), it's now working - but I no longer have the status bar at all. Which I guess is related to the try/catch check here: https://github.com/jisaacks/GitGutter/blob/f975cf2f2b22a7767f845d06b36444d80820ef45/git_gutter_show_diff.py#L4-L10

Doing a `sudo -H pip install jinja2` and restart ST3 didn't change either.

And _then_ finally installing Package Control - which I have never used with ST **ever** (yes, I'm _that_ guy!) - finally it all sprung to life. Changes to `status_bar_text` are reflected too.

Right... so then a final list of my packages installed shows: ```
magnetik:~/.config/sublime-text-3/Packages$ pwd
/home/magnetik/.config/sublime-text-3/Packages
magnetik:~/.config/sublime-text-3/Packages$ ls -l
total 48
drwxr-xr-x 6 magnetik magnetik 4096 Feb  5 06:52 GitGutter
drwxr-xr-x 3 magnetik magnetik 4096 Mar 19  2016 LineEndings
drwxrwxr-x 3 magnetik magnetik 4096 Feb  5 07:02 markupsafe
drwxrwxr-x 6 magnetik magnetik 4096 Feb  5 07:02 mdpopups
drwxr-xr-x 7 magnetik magnetik 4096 Feb 20  2016 PowerShell
drwxrwxr-x 3 magnetik magnetik 4096 Feb  5 07:03 pygments
drwxrwxr-x 3 magnetik magnetik 4096 Feb  5 07:03 python-jinja2
drwxrwxr-x 3 magnetik magnetik 4096 Feb  5 07:03 python-markdown
drwxr-xr-x 7 magnetik magnetik 4096 Mar 24  2015 SCSS
drwxr-xr-x 5 magnetik magnetik 4096 Nov  8 11:01 Theme - Flatland
drwxr-xr-x 4 magnetik magnetik 4096 Feb  5 06:52 TodoReview
drwxr-xr-x 3 magnetik magnetik 4096 Feb  5 07:03 User
```

The packages of `markupsafe`, `mdpopups`, `pygments`, `python-jinja2` and `python-markdown` are all new (via Package control). And also - that "diff viewer" from the gutter that I have _never_ seen, I'm suddenly seeing!

Seems my lack of packages (due to not using PC) has been the issue!

**Comment by deathaxe** [comment]
Yes, GitGutter needs some libraries to fully work. I also took situations in account where people might not use package control. This is what I was working like with ST2. I just copied portable version to a Linux VM to be able to test latest code changes, when I recently encountered the need to install Package Control to satisfy dependencies.

The dependencies are special ST packages created to work with Sublime Text. They are sometimes a little bit modified standard libraries to make them work with ST. So I don't know whether `pip install` can work all the time.

We could either include some basic libraries like `markupsafe` and `python-jinja2` into GitGutter package or just fallback to a basic functional state. Means status bar text without the ability to modify.

> Edit: wow, the diff viewer popup is awesome useful! 😄

Yes, I love it very much, too.

**Comment by magnetikonline** [comment]
Hey @deathaxe - some great work in these commits ☝️ - you can probably close this out, the fix being "just use package control!".

And yes, I was confused between the need of pip package `jinja2` vs. the need of the _SublimeText_ package `python-jinja2`.

Keep up the great work: 👍

**Comment by deathaxe** [comment]
Credit for the aweful diff popup goes to @r-stein.
