### ISSUE TITLE
[FR] Compare against upstream

### ISSUE THREAD

**Issue by LeszekSwirski** [jisaacks/GitGutter#371]
Instead of comparing against "origin/<branch name>", it'd be great if we could compare against the upstream branch from `git branch --set-upstream-to=foo`.

**Comment by deathaxe** [comment]
Yep. "origin" is somewhat too simple. Already have this in mind, but need to finish some ongoing bugfixes.

**Comment by johnmellor** [comment]
This works temporarily if you set `"compare_against": "@{upstream}"` in `GitGutter.sublime-settings`, but unfortunately GitGutter doesn't re-evaluate the `compare_against` expression when you switch git branch, so after switching branch it'll compare against the wrong commit. It'd be really great for GitGutter to support this, as comparing against the upstream branch is my primary use case for GitGutter :)
