### ISSUE TITLE
Blackboard Color Scheme Support

### ISSUE THREAD

**Issue by mikitl** [jisaacks/GitGutter#375]
Hi,

Can you please add the support for the color scheme 'Blackboard' that comes by default on Sublime Text?

Thanks,
Armando

**Comment by r-stein** [comment]
Unfortunately it is the other way around: The colorschemes must support GitGutter. Hence we cannot do something about this.

However you can use [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer) and edit the colorscheme and add the entries from the GitGutter README.

**Comment by mikitl** [comment]
Cool,
I will take a look with  PackageResourceViewer and try to edit the colorscheme.

Thanks

**Comment by pierresh** [comment]
Hello,

Have you found a solution for this? I also would like to have the colors with the theme Blackboard ^^.

I tried to put these lines in Blackboard.tmtheme just before the closing </plist>, but it does not work.

````
<dict>
  <key>name</key>
  <string>GitGutter deleted</string>
  <key>scope</key>
  <string>markup.deleted.git_gutter</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#F92672</string>
  </dict>
</dict>
<dict>
  <key>name</key>
  <string>GitGutter inserted</string>
  <key>scope</key>
  <string>markup.inserted.git_gutter</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#A6E22E</string>
  </dict>
</dict>
<dict>
  <key>name</key>
  <string>GitGutter changed</string>
  <key>scope</key>
  <string>markup.changed.git_gutter</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#967EFB</string>
  </dict>
</dict>
<dict>
  <key>name</key>
  <string>GitGutter ignored</string>
  <key>scope</key>
  <string>markup.ignored.git_gutter</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#565656</string>
  </dict>
</dict>
<dict>
  <key>name</key>
  <string>GitGutter untracked</string>
  <key>scope</key>
  <string>markup.untracked.git_gutter</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#565656</string>
  </dict>
</dict>
````

Thanks!

**Comment by pierresh** [comment]
For those that might be interested with Blackboard theme including support of GitGutter, I just made a repo for this purpose here: https://github.com/pierresh/Theme-Blackboard
