### ISSUE TITLE
Can popups have text-wrapping?

### ISSUE THREAD

**Issue by DmitriyK-CPKIO** [jisaacks/GitGutter#379]
I'm trying to use Git\GitGutter for text editing and track changes. The lines are not hard-breaked but wrapped in Sublime which is fine, but GitGutter popup shows one long line and does not wrap text. Can word-wrapping be enabled somehow?

**Comment by r-stein** [comment]
That is currently not possible. It would also require a change at the mdpopups library, where I requested it to be unbreakable https://github.com/facelessuser/sublime-markdown-popups/issues/14.

**Comment by deathaxe** [comment]
Yes they can.

**Comment by jisaacks** [comment]
@deathaxe can you please elaborate? is what @r-stein said incorrect? Or has something changed since then?

**Comment by deathaxe** [comment]
The popup module basically handles 2 lists: 

1. list of all deleted lines in the hunk (old content from git database)
2. list with all added lines (new content from the view)

List 1 is used ...
a) to show the content of the popup in "default" mode.
b) as source for 'revert' and 'copy to clipboard' functions.

List 1 and 2 are both used to create the content to show in "diff" mode.

I recently found other packages to use the `textwrap` library to `textwrap.dedent()` code snippets. The `textwrap` is part of python's stdlibs and thus available by default.

It can replace @r-stein's `_get_min_indent()` function and is 10..25% faster.

This library also provides a `wrap()` function, which can be used to create a new `deleted_lines_to_display` list whose items contain correctly wrapped text content to be displayed.

This way diff popup can wrap text nearly the same way as ST does (always/never/auto). If the scope of the first character of the hovered line contains `source.` wrapping is disabled in `auto` mode.

It works very well in "default" mode but still needs some work to wrap "diff" correctly.

I am thinking about two new settings to control this feature. I am not yet able to automatically calculate wrap width from popup max_width, but maybe I'll learn how to.

```JavaScript
  // Limit the line length in diff popup to avoid horizontal scrolling.
  // Possible values are:
  // true: always wrap text.
  // false: disable word wrap.
  // "auto": disabled for source code.
  "diff_popup_word_wrap": "auto",

  // The desired line length in characters.
  "diff_popup_wrap_width": 80,
```

**Comment by jisaacks** [comment]
Thanks for explaining all that. :) @deathaxe

**Comment by r-stein** [comment]
Is there any advantage of using the `textwrap.wrap()` method to just using the default popup wrap and just omit the non-breakable spaces between the words?
In the inside diff you can just change the `_to_html`, which explicitly inserts `&nbsp;` to avoid wrapping. 
Manually wrapping something and making it not able to wrap afterwards, instead of just keeping the default wrap ability, just doesn't look like a good idea to me.

**Comment by deathaxe** [comment]
I removed all those `nbsp;` replacements but the text does not wrap in popup anyway. So if I don't miss something the advantage is - it works. ;-)

**Comment by r-stein** [comment]
Okay, that seems to be buggy in build 3131 and in 3126 it wraps bad, such that you need two scrollbars (where this version may be better?).

**Comment by r-stein** [comment]
I have created two issues for that:
https://github.com/SublimeTextIssues/Core/issues/1686
https://github.com/SublimeTextIssues/Core/issues/1687

**Comment by deathaxe** [comment]
Text wrapping is supported by diff popup with GitGutter 1.7.0+ and mdpopups 2.0.0+.

Diff popup uses the `"word_wrap"` from _Preferences_ to decide whether to enable or disable the feature. The default value `"auto"` disables wrapping for all kinds of "source." .
