### ISSUE TITLE
On Windows, all lines are marked as different due to mismatch in line-endings

### ISSUE THREAD

**Issue by rahul-ramadas** [jisaacks/GitGutter#389]
I've left a [comment](https://github.com/jisaacks/GitGutter/commit/527f9019c52baf05497772b63232e2328beec62e#commitcomment-21312660) on what I think is the offending commit.

**Comment by r-stein** [comment]
Possible duplicate of #381.

**Comment by rahul-ramadas** [comment]
My bad. The issue does not occur with the latest master.
