### ISSUE TITLE
[Enhancement] Add atom style git gutter theme.

### ISSUE THREAD

**Issue by ooJerryLeeoo** [jisaacks/GitGutter#392]
Is it possible to add `atom` style git gutter theme ?

![image](https://cloud.githubusercontent.com/assets/20783502/24318741/0cb332a6-1145-11e7-8d05-899dfb1f78ed.png)

**Comment by r-stein** [comment]
We can only use icons (png images) for that, but if you want to use line icons it is possible.

**Comment by ooJerryLeeoo** [comment]
Yes, I want the line icons.

**Comment by ooJerryLeeoo** [comment]
Can you add the vertical line icon into this package?

**Comment by deathaxe** [comment]
I already thought about such a style, too. 2 things to care about:

1. GitGutter shows deleted regions between 2 lines. From screenshot I see Atom uses row 25 only, to mark it display deleted regions. We would need to add "deleted" icons which show on row 24/25 or 25/26 with half size maybe.
2. If someone adds icons to GitGutter package **please** ensure to remove all EXIF/META/color profile data from the png files. As you'll see current icons are only 100 to 200 bytes of size. With color profiles they would have 2..4kB (or even more) of size - a waste. I used XnviewMP to create clean copies.

**Comment by ooJerryLeeoo** [comment]
So you mean you can add such vertical line icon?

**Comment by deathaxe** [comment]
Yes of course,

it's not a big deal.

---

Just to have shouted out: Everyone is able to create its own packages which provide GitGutter themes.

The only thing you'll need to do is to 
1. add a folder with the icons named like in GitGutter's "themes/Default" folder
2. add an empty (json) file called `My Own Theme.gitgutter-theme` to that folder.

**Comment by ooJerryLeeoo** [comment]
I was thinking about create my own git gutter theme, but my image editing skill is terrible.

**Comment by deathaxe** [comment]
Those icons are not very hard to create. They are 32x32 in size and must have transparent background with few pixels brushed white on the right. 

The only possible issue with this icon style might be the color as all icons look the same way. It is essential that your color scheme defines the gitgutter scopes with different colors for inserted/modified/deleted rows. Otherwise you are not able to see the difference.

**Comment by deathaxe** [comment]
Depending on your line spacing settings, the bar icons won't be connected.

I use following settings, so icons will be displayed using spaces, too.

```js
{
	"line_padding_bottom": 5,
	"line_padding_top": 5,
}
```

**Comment by ooJerryLeeoo** [comment]
@deathaxe Thanks for helping, I think I'll just use the default git gutter theme, I don't have time to learn and create my own git gutter theme.

**Comment by ge0pan** [comment]
This is simply achievable if you change `g:gitgutter_sign_added` (and 3 others) to this one 
`┃` 
from [Unicode Characters](https://unicode-table.com/en/2503/) (your terminal should support unicode btw).
Also, you may want to change `GitGutterAdd`(and 3 others) `ctermfg` highlighting, which will affect sign's color (I left `ctermbg` to nothing for a clean look).
This is what I got at the end:
<img width="46" alt="screen shot 2018-04-11 at 20 46 56" src="https://user-images.githubusercontent.com/5871409/38634422-1d4a8426-3dcb-11e8-912c-79647a4294dd.png">

**Comment by deathaxe** [comment]
You are welcome to create a PR if it is so easy. I can't currently imagine how to use unicode characters as icons in the gutter area. The bars of the _Bars_ themes already cover the whole height of the image resources.
