### ISSUE TITLE
Is GIT 2.12.0 acceptable as a requirement?

### ISSUE THREAD

**Issue by deathaxe** [jisaacks/GitGutter#395]
I recently found latest versions of git (2.12.0+) supporting

`git status --porcelain=2 -b -u --ignored`

This command provides all information required to handle a file.

It provides:
- branch name,
- tracking remote branch
- file state (modified, staged, commited, untracked, ignored)
- the object id of the file in the database and staging area

This command could replace several git commands, which need to be invoked today to collect all those required information:

- `git ls-files --ignored` to check whether a file is ignored
- `git ls-files -u` to check whether a file is untracked
- `git rev-parse HEAD`  to get the commit id of a branch or HEAD, we compare against
- `git rev-parse --abbrev-ref HEAD` to get the current's branch name

**PRO**
- could help to make things more resource efficient
- less number git invokations
- maybe reduce latency
- would help to track changes when comparing against staging area without reading the whole file repetitively

**CON**
- makes git 2.12.0 or higher a requirement to use GitGutter.

So on the one hand this command would make things easier to implement, but on the other hand it might require everybody to update git to the latest release. 

I am not sure whether this is a step we can go in the near future or if there are too many people out there who need to keep using an older version of git for some reason.

I would be pleased to get some feedback on this question.

**Comment by jisaacks** [comment]
Anyway for graceful degradation? Theres half a million installs of GitGutter. I have no clue how many are on 2.12 and don't want to break it for that many people. Ideas? cc. @r-stein

**Comment by r-stein** [comment]
I think the requirement of git version `2.12` is too much for the advantages, because that is the *newest* version of git and many people will use older ones. We may support both and check the git version if that is not too much overhead.

**Comment by jisaacks** [comment]
I tend to agree with @r-stein

**Comment by deathaxe** [comment]
Ok, thanks for your feedback so far.

**Comment by r-stein** [comment]
Do you see the possibility to support both with reasonable effort?

**Comment by deathaxe** [comment]
I am thinking about it.

I started playing around with `git status` last year with the default `porcelain=1` as this will enable GitGutter to omit creating temporary files and calling diff at all for untracked/ignored/commited files and be able to check for the file being staged.

With the information of a file being staged or not we could decide to compare against the index or the database - what some users asked for. But I never found a way to efficiently check the index (staging area) for changes without reading the whole file content. I'd like to use the object id of staged files to track changes the same way I do with commit id's today. When I saw the `git status porcelain=2` providing both object ids for the working file and staged file (if exist) I was happy to have a solution and a possible way to reduce number of required git calls.

All other information (branch name, upstream, file state) can be read from old `git status`, too. It only misses the object IDs and is a bit more tricky to parse. So I am not sure whether supporting both versions is worth the possibly added complexity.

Making use of git status to optimize work on current branch and support staging area already comes with some extra effort to handle the Compare against ... system as the output of `git status` is not valid when comparing against different commits or branches. I need to emulate `git status` somehow in those cases, so the user doesn't see a difference.

I don't want to bloat GitGutter, but only add requested functions with minimal set of code and best possible performance.

**Comment by magnetikonline** [comment]
I'm all for this!

Could the plugin issue a `git --version` during it's bootstrap and determine which way to go? Would mean new/old git version code paths have to be maintained - which would be a negative I guess.

But for me personally I run latest versions always (compile from source on OS X and use a very often updated PPA for Ubuntu) - so would love to have this running as a single command if possible.

**Comment by deathaxe** [comment]
I am thinking about using `git --version` on startup to check, whether git is working well. GitGutter checks for an entry in the settings or `PATH` right now, but even if they point to a valid git binary, it might not work properly. This repetitively raised issues like #388 in the past.

**Comment by septagram** [comment]
I also think that if you'd choose not to conditionally choose whether to use new Git features or not (and thus whether to maintain the code interacting with an old Git version), it'd be reasonable if GitGutter could somehow at least inform the user they have an old version.

**Comment by gerardroche** [comment]
I'm on Ubuntu 17.04 and it only has Git 2.11.0 so I'm gonna say that 2.12.0 is probably a bit too much of a stretch. 

I really don't want to figure out how to install the latest version of Git just for GitGutter.

**Comment by deathaxe** [comment]
As issue #416 proved it is not acceptable.
