### ISSUE TITLE
Setting live_mode is no longer honoured

### ISSUE THREAD

**Issue by magnetikonline** [jisaacks/GitGutter#399]
Just a quick one - it seems the `live_mode` setting is no longer read/acted upon.

It seems this regression has come about since commit 2269332ac52d0db61fe3718d1fb41b3bbbccf431.

To be honest, on the projects I'm using right now - being live all the time isn't actually a hindrance at all (probably due to the improvements made with EventListener?). So maybe the option of `live_mode` just needs to be removed entirely?

Cheers.

**Comment by deathaxe** [comment]
Yes it got lost at some point, but it is included in PR #397 again.

I honestly never touched this setting, so I didn't realize it's gone. I kept `live_mode` and `focus_change_mode` for backward compatibility. Maybe there is still somebody who needs it. Not sure. For all the other people it doesn't hurt.

**Comment by magnetikonline** [comment]
Thx @deathaxe - see how it pans out :+1:

**Comment by magnetikonline** [comment]
Just to add - this is now fixed in `master` from c9876cad0fe75978a398109fc43051d88aa683ec (or some commit around there). Live mode can be turned on/off once more.
