### ISSUE TITLE
No Icons since April 21, 2017 update

### ISSUE THREAD

**Issue by cwpetrich** [jisaacks/GitGutter#403]
GitGutter Icons are no longer displayed when files are changed within git repository since the latest update 3 or so days ago. I'm working on Windows 10, sublime text 3 Build 3126, git executable is properly set within my PATH, and GitGutter settings file is referencing the correct location for git's executable with the git_binary option. I removed the package and reinstalled. I'm not sure what the next step is to try and make it work besides reporting the issue.

[GitGutter.zip](https://github.com/jisaacks/GitGutter/files/952241/GitGutter.zip)

**Comment by deathaxe** [comment]
I am running Windows 10 x64 with ST3 3126 (and 3131) and git for windows 2.12.2 installed on _C:\Program Files\git\\_.

Remarks: If git is available on PATH (running git from command line works), you don't need to setup the "git_binary" explicitly.

I removed my repository and installed GitGutter with Package Control as ordinary user and tried successfully with your settings file. Everything working as expected here.

1. Which git version do you use?
   a) The latest commits didn't introduce any changes related to git version, but just to be sure.
   b) Another user had issues with "eol" and older git versions.

2. Please add `"debug": true,` to your GitGutter.sublime-settings file to enable printing git error messages to Sublime Text's console.

3. Does the console show any _Traceback_ or error messages?

4. What does the statusbar show?
    Something like `In Repository on branch, File is modified, 1+ 2-`

5. Make sure %APPDATA%/Sublime Text 3/Installed Packages/GitGutter.sublime-package is the only instance. There must be no other folder in %APPDATA%/Sublime Text 3/Packages which could override parts of the installed package.

**Comment by cwpetrich** [comment]
1. my git version is 2.9.0.windows.1.
2. I set "debug": true in GitGutter.sublime-settings.
3. The only message for GitGutter in the console is as follows:
    GitGutter: "git diff" failed with "fatal: invalid diff option/value: --indent-heuristic"
4. Status bar says:
    In MyRepository on MyBranch, File is commited, ...
But the file is not committed and there are several changes that are not yet staged.
5. There is no GitGutter.sublime-package in either location.

**Comment by deathaxe** [comment]
Thanks for your information.

>The only message for GitGutter in the console is as follows:
GitGutter: "git diff" failed with "fatal: invalid diff option/value: --indent-heuristic"

A short search in git's docs show the `--indent-heuristic` parameter is supported by git 2.11 and above, only. Added this parameter as it seemed to improve the diff results.

Will remove it.

**Comment by deathaxe** [comment]
Fixed in release 1.6.0
