### ISSUE TITLE
Bar Themes not working on ST3.

### ISSUE THREAD

**Issue by bgrrtt** [jisaacks/GitGutter#404]
On a fresh install of ST3 3131, everything seems to be working except...

**These themes work**
- "theme": "Default.gitgutter-theme"
- "theme": "Default HiDPI.gitgutter-theme"

**These themes do not work**
- "theme": "Bars.gitgutter-theme"
- "theme": "Bars Thin.gitgutter-theme"

Is this just me? Is there a common solution I'm missing?

**Comment by deathaxe** [comment]
"Bars" are available with GitGutter 1.6.0-rc.1 So I guess you are still using GitGutter 1.5.1 ?

**Comment by r-stein** [comment]
Open *Preferences > Package Settings > Package Control > Settings - User* and insert at a reasonable (correct JSON syntax) position: 

``` js
    "install_prereleases": ["GitGutter"],
```

**Comment by bgrrtt** [comment]
Awesome! Thanks guys!

**Comment by deathaxe** [comment]
Fixed with release 1.6.0
