### ISSUE TITLE
GitGutter doesn't work anymore

### ISSUE THREAD

**Issue by septagram** [jisaacks/GitGutter#408]
Since yesterday, all of sudden, GitGutter ceased showing any changes: there aren't any icons to the left of the changed/added/deleted lines anymore.

I tried to open settings, but every item in the GitGutter's menu is greyed out:

![image](https://cloud.githubusercontent.com/assets/5250951/25802089/06c46178-341b-11e7-8748-c269834c288c.png)

Sublime 3, build 3126. Git version 1.9.4.msysgit.2. Tried updating GitGutter and Sublime, no joy.

Any idea what can be wrong?

**Comment by r-stein** [comment]
1. have you tried to restart Sublime Text?
2. Does any errors appear in the ST console ``ctrl+` ``?

**Comment by septagram** [comment]
Oh my... Restarting helped. I'm terribly sorry. Thanks, and even more thanks for GitGutter, it's the best ^_^

**Comment by JemarJones** [comment]
Yea i don't know what caused this, but had the same issue and restarting helped. 👍

**Comment by r-stein** [comment]
GitGutter imports stuff from submodules, which is not always perfectly handles by Sublime Text (module is reloaded, but not all submodules and so on). Hence it is somethings necessary to restart ST after major updates to have all modules and submodules in the up-to-date version.

**Comment by septagram** [comment]
@r-stein Might it be possible to watch for the updates and force reload of GitGutter?

**Comment by deathaxe** [comment]
> Might it be possible to watch for the updates and force reload of GitGutter?

GitGutter uses package control's event API to handle the "after upgrade" event and reload all of its submodules then. Unfortunately python seems to keep some old globals after module un- and reloading which causes issues if the module structure changes heavily.

The new structure is required to avoid some more serious issues, which caused several modules being instantiated twice or more times in the past.

**Comment by jayzyaj** [comment]
Hi I am having the same error. I restarted my sublime but still didn't work for me.
Btw I am having this error in my console below

> GitGutter: "git --version" failed with "[WinError 193] %1 is not a valid Win32 application"
