### ISSUE TITLE
When git is not installed, plus icons show in all lines

### ISSUE THREAD

**Issue by oferei** [jisaacks/GitGutter#411]
I do not have git installed on my Windows PC. GitGutter shows plus (+) icons on all lines in all git-managed files.
Expected behavior: show some error, or do nothing at all.
Versions: GitGutter 1.6.0. Windows 10.

The console log shows many errors such as:
    GitGutter: "git rev-parse" failed with "[WinError 2] The system cannot find the file specified"
    GitGutter: "git ls-files" failed with "[WinError 2] The system cannot find the file specified"

**Comment by deathaxe** [comment]
> I do not have git installed on my Windows PC. 

In this case GitGutter might not be the correct plugin for you.

> Expected behavior: show some error, or do nothing at all.

It shows the error messages compared to other packages which throw exceptions and sometimes even make ST unusable in this situation.

It is not useful to do nothing as even if git is not found it might be back on any time. You can leave ST, install git and switch back to ST. GitGutter will find git and run normally without any other interaction.

**Comment by oferei** [comment]
Of course GitGutter requires git and it makes no sense to use it without git. But it should handle this error case more gracefully, communicating it better to the user: a message perhaps, not plus signs.

It happened to me because I use SourceTree which was using an embedded/walled installation of git that was not accessible from command line. I was in the process of setting up a computer, and it took me a while to figure out the problem - I did not see any error message, only the Plus signs.

**Comment by deathaxe** [comment]
An error dialog is a bit tricky as GitGutter tries to run normally each time a view gets active. This is necessary to allow changed settings ("git_binary") to take effect immediately. Same with git binary. It could possibly be unavailable temporarily, which should not disable evaluation until restart of ST or requiring to reopen a file.

I am aware of this edge case and GitGutter used to act much worse in the past.

I am thinking about calling `git --version` each time a view gets activated to check whether git is working properly. I already have an version offline, which disables GitGutter in case of invalid output then. Need to finalize it.

**Comment by oferei** [comment]
That's what I meant by "doing nothing". Even if displaying an error message is not possible, at least detect git availability and do not show any (plus) signs if it's missing.

I see we are aligned.
