### ISSUE TITLE
all lines in already commited files marked as new

### ISSUE THREAD

**Issue by RafalSkolasinski** [jisaacks/GitGutter#417]
## Description

Today morning sublime updated GitGutter, since that moment whole files under git control are marked as new. 

git version 2.9.4, Fedora Linux

## Support Info

- Sublime Text 3126
- Platform: linux
- Arch: x64
- GitGutter GitGutter version could not be acquired!
- Install via PC: False
- git version could not be acquired!
- mdpopups 1.13.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Enter directory with git repositiory
2. subl some_file
3. cry that every line is new, when it isn't

**Comment by StefNijenhuis** [comment]
Same here, opened an existing project and all the already committed work was marked as new lines.

### Info ###
Sublime Text 3126
Ubuntu 14.04 x64
Git version: 1.9.1
GitGutter version, latest I assume
Installed via PC: true

### Other packages: ###
BracketHighlighter version 2.24.1
SublimeLinter

**Comment by r-stein** [comment]
Please see https://github.com/jisaacks/GitGutter/issues/416#issuecomment-304572606

**Comment by amrutjadhav** [comment]
I am also getting same issue.

**Comment by StefNijenhuis** [comment]
Cheers!

**Comment by RafalSkolasinski** [comment]
indeed bug already reported in https://github.com/jisaacks/GitGutter/issues/416
closing
