### ISSUE TITLE
Highlight modified files in project tree

### ISSUE THREAD

**Issue by lnr** [jisaacks/GitGutter#426]
Is it possible?

**Comment by r-stein** [comment]
No there is no API for that.

**Comment by cmalard** [comment]
Looks like this is possible on ST3 with file icon :-)

Not sure there is a way to do it in the "open files" zone, but that's still a start :+1:

**Comment by r-stein** [comment]
Is it possible to set the icon per file? I though it was only per file type/extension.

**Comment by cmalard** [comment]
Well... you're almost right :+1:
>Currently Sublime Text requires syntax definitions to apply icons. This means that you need to have the right syntax package to be able to see icons associated with the language. However we can abuse syntax definitions in order to provide different icons to files with the same underlying syntax but different semantics (Gulpfile.js, package.json & etc.).
https://github.com/ihodev/a-file-icon/blob/develop/.github/CONTRIBUTING.md#settings

Not so sure we can do it, how far can we abuse syntax definitions ? :thinking:

**Comment by jisaacks** [comment]
I looked into this before and it seemed like a rabbit whole to me. Others are welcome to try but I would rather not add a feature that relies on hacks.

**Comment by deathaxe** [comment]
Hacking around with files to display dynamic states is just bullshit. Furthermore the link above only describes a way how _A File Icon_ can provide plenty icons for file types which are not known by ST as a file icon requires a scope. 

It is just not possible with current API to do that. That's it.
