### ISSUE TITLE
Gutter annotations and most palette commands missing

### ISSUE THREAD

**Issue by bradharms** [jisaacks/GitGutter#428]
## Description

At random times, Git Gutter stops showing markers in the gutter, and commands related to Git Gutter no longer appear in the command palette except for "Git Gutter: Support Info" and options that begin with "Preferences: ..."

No errors or warnings are reported to the console.

Edit: I forgot to mention that whenever this issue pops up, then sometimes when I start Sublime Text, it won't auto-load my last project and the console is blank. After 5-10 seconds, Sublime crashes. If I then start Sublime again, the last project DOES load and I see the usual console output, BUT git gutter still isn't working.

## Support Info

- Sublime Text 3126
- Platform: linux
- Arch: x64
- GitGutter 529e30e
- Install via PC: True
- git version 2.13.0
- mdpopups 2.1.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

I am unable to consistently reproduce the problem. As stated, it appears to be totally random. In the past I was able to temporarily resolve the issue when it happened by "cleaning out" my Sublime install, ie. clearing all the caches I could find, deleting all project workspaces, reinstalling GitGutter, etc. but now nothing I do seems to get it working again.

**Comment by bradharms** [comment]
I discovered that this was caused by issues on my work station and is probably not relevant to GitGutter.

**Comment by deathaxe** [comment]
GitGutter is disabled and would show Preferences and Support Info command only in following situations:

- `"git_gutter_enabled" : false` is set in preferences or view settings
- `"enabled" : false` is set in GitGutter.sublime-settings
- view is read only
- view is marked as scratch
- view has now window()
- view is a "repl" view
- view has "hexadecimal" encoding
- `"is_widget": true` is set in view settings

A crashing event handler of any package can cause none of the following packages in the list being informed about events. Therefore they can't handle them.

**Comment by bradharms** [comment]
None of the stated scenarios apply to my situation. The preference options mentioned are `true`, I'm just using normal views on normal version-controlled source code files in my project. Not using ConvertToUTF8.

I don't know how Sublime manages plugins, but I looked at the Sublime Text process tree and saw a sub-process called "plugin_host", with another "git" sub-process running inside of that. No matter how long I waited, that sub-process would never end and my repo stayed in a locked state (due to the presence of `.git/index.lock`). This suggested that Git itself was stuck on something and it was causing a Sublime plugin to be stuck waiting on it. I resolved the issue on my system that was causing Git to hang, which immediately resolved the issue I was having with GitGutter.

**Comment by deathaxe** [comment]
_plugin_host_ is running the python VM with all the ST packages. All external processes such as git are called by python's `subprocess` module and will block the whole plugin_host during execution.  GitGutter uses a timeout of 30s to wait for git to complete before killing it. It is the way of executing external processes suggested by python 3 docs. 

Are there other packages present, which may have been calling git concurrently?  Or is GitGutter the only one?

**Comment by bradharms** [comment]
I disabled every plugin related to git except for git gutter and restarted
sublime text. Immediately I did indeed see improvements, and the git
subprocess stopped hanging. The culprit seems to be GitStatusBar.

**Comment by deathaxe** [comment]
It also runs git process on an event driven base, which might cause several instances being started at the same time, trying to read from same database. I already tried running several git instances in parallel threads for several views in the past, too, without such issues (on Windows).

From my point of view git must be able to handle such situations. I guess this is something none of the ST packages can handle somehow.

**Comment by deathaxe** [comment]
If the database is already locked by one git instance, I would expect all other ones to wait for it to complete or return an error after some timeout (or immediately). 

I guess the first instance didn't remove the lock file correctly, which caused the second instance to wait forever. This is expected a bug of git itself. It must be able to handle concurrent database access correctly.
