### ISSUE TITLE
Bar theme, increase bar height

### ISSUE THREAD

**Issue by Swift-R** [jisaacks/GitGutter#433]
Is it possible to increase the bar height to fill the entire line? If not, this is a suggestion.

Example, make this (Sublime):

<img width="88" alt="screen shot 2017-08-04 at 11 59 29" src="https://user-images.githubusercontent.com/358114/28968117-fd9e8014-790d-11e7-85b3-97d0319785ad.png">

look like this (Atom):

<img width="76" alt="screen shot 2017-08-04 at 12 00 31" src="https://user-images.githubusercontent.com/358114/28968122-06d7771c-790e-11e7-8f04-596e379ba879.png">

I can't change the color either by adding the color scheme entries from this README into my theme. Is it updated?

**Comment by jisaacks** [comment]
The icon are just image files and they do not scale with the font size. So if your font is larger they will not take up the entire row. This is how they are implemented in Sublime and not something git gutter can change. If you decrease your font, you should get the appearance you want.

**Comment by deathaxe** [comment]
Line padding also adds gaps between the icon rendering areas. There is no way to fix that.

**Comment by deathaxe** [comment]
Scope names in the README are up to date and do work. I modified the _AYU mirage_ color scheme to make deletions render red.

**Comment by gerardroche** [comment]
> Line padding also adds gaps between the icon rendering areas. There is no way to fix that.

Is there an open issue on https://github.com/SublimeTextIssues/Core for this? I see https://github.com/SublimeTextIssues/Core/issues/1713, is that the same issue?

It's a shame the bar has gaps. Decreasing the font size is not an option, it's too small. And the gaps just ruin the bar theme.

**Comment by deathaxe** [comment]
This topic was discussed several times, but can't remember it to have dedicated issue. The most related topic might be something like "dedicated gutter area for changes". Users requested multiple icons per line several times to be able to somehow see information from SublimeLinter, ColorHelper, GitGutter at a glance rather than each plugin fighting for priority.
