### ISSUE TITLE
Gutter annotations disappear on save

### ISSUE THREAD

**Issue by myessail** [jisaacks/GitGutter#436]
## Description
Every time I save my file, the gutter annotations disappear. If I select somewhere in the file and press the spacebar and delete the space, they all show up again as they were before.

## Support Info

- Sublime Text 3126
- Platform: osx
- Arch: x64
- GitGutter 1.7.3
- Install via PC: True
- git version 2.11.0 (Apple Git-81)
- mdpopups 2.1.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue
1. Make changes to a file. The annotations will still be showing up.
2. Save the file. The annotations should disappear.
3. Type in the file. All previous annotations should reappear.

**Comment by deathaxe** [comment]
Gutter icons are removed in 2 situations:

1. The package is disabled and therefore all the GitGutter python objects are deleted.
2. GitGutter is disabled by a setting or the state of the view (see: https://github.com/jisaacks/GitGutter#gitgutter-keeps-completely-quite)

I can reproduce icons to temporarily disappear when saving a python file within a Sublime Text package. Reloading the file deletes and recreates the GitGutterCommand. But the icons reappear as evaluation is triggered by the POST_SAVE event.

Saving a text file or any source outside Sublime Text folder doesn't cause icons to disappear at all here.

Reason 2 might be triggered by another package which sets the view to read-only or scratch state or something like that.

**Comment by myessail** [comment]
I think there was a problem with one of my other packages. I uninstalled and reinstalled them and the problem has gone away. Thanks!
