### ISSUE TITLE
Stopped Working after Update - Recognizes untracked files but diffs no longer work

### ISSUE THREAD

**Issue by pts-sergiomartins** [jisaacks/GitGutter#437]
## Stopped Working after Update to v1.7.3

Worked fine before package control updated it. Nothing else changed as far as I'm aware.
![support-info](https://user-images.githubusercontent.com/23078889/29323380-b6904514-81ae-11e7-846b-f902e3c9bdc7.png)
The version doesn't appear for some reason. Package control says it's 1.7.3

I noticed it does recognize untracked files but never shows diffs anymore (lines added/removed/changed). Running `git diff` myself from the project dir works as expected.
![gitgutter-debugging](https://user-images.githubusercontent.com/23078889/29324226-613d5766-81b1-11e7-8ded-bd252cc14113.png)

Settings are default. I tried restarting sublime and reinstalling GitGutter. No luck.

Any idea what could be wrong?

**Comment by r-stein** [comment]
Do you have any output in the ST console ``ctrl+` ``? Have you tried to restart Sublime Text?

**Comment by pts-sergiomartins** [comment]
Yes I've restarted the editor. I've had this problem for a few days before posting.
There's nothing really in sublime's concole (except a lot of noise from other plugins): https://pastebin.com/FS2MRLht

**Comment by svenmuennich** [comment]
I'm experiencing the same issue on macOS.

**Comment by deathaxe** [comment]
Commit https://github.com/jisaacks/GitGutter/commit/e194745e561e8719719bc36b973df8b2c9fa0b67 fixes it. I wanted to wait for possibly required changes to help fixing #435 (if caused by GitGutter) and than create a 1.7.4. But as there have not been progress on it for some days now, I might do without it.

**Comment by pts-sergiomartins** [comment]
I encourage you release #435 as 1.7.5. I really miss GitGutter :)

**Comment by pts-sergiomartins** [comment]
Thank you good sir.

**Comment by svenmuennich** [comment]
👍
