### ISSUE TITLE
GitGutter icons filling gutter

### ISSUE THREAD

**Issue by cdloh** [jisaacks/GitGutter#438]
Not sure if this is an issue with GitGutter of the theme I'm using but for some reason the gutter changes are all combining creating this weird gutter.

I'm using - https://github.com/jonschlinkert/sublime-monokai-extended

- Sublime Text 3126
- Platform: osx
- Arch: x64
- GitGutter 1.7.4
- Install via PC: True
- git version 2.10.1 (Apple Git-78)
- mdpopups 2.1.1
- markdown 2.6.6
- pygments 2.1a0
- jinja2 2.8

![](http://i.imgur.com/oc3oxYg.png)

**Comment by cdloh** [comment]
Hmm a further restart or two of Sublime Text appears to have fixed this. Not sure what's going on.

**Comment by deathaxe** [comment]
This graphical glitch happens, if the icon resources are not found. Saw something like that during development several times. If this happens restarting ST is the only solution, as the icon paths are cached somehow with the invalid resource.
