### ISSUE TITLE
Add option to disable auto update of git-gutter

### ISSUE THREAD

**Issue by AnwarShah** [jisaacks/GitGutter#439]
## Description

Please add options to disable auto updates of git gutter. Currently it checks for updated version at sublime startup and auto downloads and install updates. I want to make the download and updates manual

**Comment by r-stein** [comment]
The updates etc are handled by Package Control. If you want to do it manually you should [install it manually](https://github.com/jisaacks/GitGutter#manual-installation) and set the `ignore_vcs_packages` to `true` in your package control settings.
