### ISSUE TITLE
GitGutter no longer works for SublimeText 3.0 Build 3143

### ISSUE THREAD

**Issue by tombusby** [jisaacks/GitGutter#444]
At least, this is the case with the apt-get installed version of SublimeText.

It no longer appears in the list of available package manager packages, and it fails when I do a manual install.

**Comment by fessard** [comment]
I managed to get it to work by removing the package (sublime text became non responsive and I killed it), reinstalling it (it was in the list of packages for me) and restarting Sublime text 2 or 3 times. Same for my colleague.
Installed via apt-get, stable branch.

**Comment by tombusby** [comment]
interesting, I'll look into it.

**Comment by ybentz** [comment]
I'm on the latest macOS, didn't have GitGutter in the list of packages, managed to get it to work by going to `/Users/{username}/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages`, deleting `GitGutter.sublime-package` and then restarting Sublime. Once it reopened the gitgutter change log opened and it's working again. Hope it helps.

**Comment by tombusby** [comment]
Got it working. Thanks guys.

**Comment by deathaxe** [comment]
Sublime Text 3143 seems to have some trouble with dependencies during the first couple of startups. I encountered nearly or even all dependency packages to raise exceptions during startup. This caused several packages not to start correctly. I guess its the same case with GitGutter

**Comment by agungyuliaji** [comment]
in my case (MacOSx machine), after update simply do `force close` the sublime (then the icon changed), then start again, and its works

**Comment by lexilya** [comment]
I just hit the "Upgrade/Overwrite all packages" option, then restarted Sublime, and it worked again. A simple restart didn't work on its own. On MacOS btw.

**Comment by deathaxe** [comment]
If you come from 3126 it might be a good idea to delete the `Data/Cache` folder. Not sure whether it helps with this particular issue, but found others caused by obsolete cache entries.

**Comment by fskhalsa** [comment]
Steps that worked for me:

- remove package via package control (sublime text became non-responsive and I killed it, same as @jfessard )
- remove gitgutter _and_ package_control_loader from ignored_packages in user settings (no idea how those got there - but they weren't there before ST updated)
- reinstall gitgutter via package control (will now work, as gitgutter _and_ package control's own package loader aren't being ignored)

No idea why the ST upgrade did that, but it had me baffled for a while...

**Comment by deathaxe** [comment]
I think the main issue was/is the ignored `package_control_loader`.  It is responsible to add all the dependency packages to pythons `sys.path`. If this package is ignored none of the dependencies is found which crashes all packages, depending on them.

**Comment by jsieler** [comment]
Still not working on windows. I'm using portable version of ST3.

Did all the steps mentioned here, installed and reinstalled GitGutter multiple times, removed all stuff from "cache" folder. Restarted multiple times. Still nothing.

I don't see any "package_control_loader" within installed packages. "package_control_loader" and "GitGutter" are not within ignored setting.

**Comment by deathaxe** [comment]
The package used py PC to load dependencies is actually named "0_package_control_loader.sublime-package".

You should find a line like `reloading plugin GitGutter.plugin` anyway. GitGutter starts without dependencies being available, too. I checked that earlier this day.

Any other messages beginning with GitGutter in console? Maybe it's just disabled, because of any reason.

You could add `"debug": true` to the GitGutter.sublime-settings to possibly get more detailed information what goes wrong.

**Comment by aarohmankad** [comment]
For me, GitGutter works fine, but I'm having to enable it for every file I open.

**Comment by deathaxe** [comment]
In this case, please check whether you find

`"enabled": false` in _Packages/User/GitGutter.sublime-settings_ (may use: `Preferences: GitGutter Settings`)

or

 `"git_gutter_enable": false` in _Packages/User/Preferences.sublime-settings_ (may use: Preferences Settings)

The later setting may also be part of project specific settings or may be caught in the session file somewhere.

GitGutter provides `true` for that value by default.

**Comment by jemhuntr** [comment]
GitGutter stopped working for me too. Sublime Text 3143, running on Windows 10.

There are no options that disable GitGutter (_Packages/User/GitGutter.sublime-settings_ nor _Packages/User/Preferences.sublime-settings_).

When I type `view.settings().get("git_gutter_enable")` on the console, it doesn't output anything.

**Comment by deathaxe** [comment]
> When I type view.settings().get("git_gutter_enable") on the console, it doesn't output anything.

Even after a restart of ST?

With a look into code it may happen just right after update as the default value provided in the _GitGutter/Preferences.sublime-settings_ file will be loaded by ST upon startup only.

**Comment by jemhuntr** [comment]
Nevermind, I didn't see this error before, but apparently GitGutter just wasn't able to find my git binary. Everything's working fine now.

**Comment by frsnic** [comment]
I had fix it. When I listen @deathaxe suggestion add "debug": true to the GitGutter.sublime-settings 
I find this in console.
```
GitGutter: "git --version" failed with "Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command."
GitGutter: git is back on duty!
```
And I open my xcode and agree the license, I can use GitGutter right now.

**Comment by khink** [comment]
For me (on Mac OSX), deathaxe's comment about git_gutter_enable made it work me: 

```
>>> view.settings().get("git_gutter_enable")
>>> 
```

After setting it to `true` in `/Users/$USER/Library/Application\ Support/Sublime\ Text\ 3//Packages/User/GitGutter.sublime-setting` *and restarting*, it worked.

**Comment by deathaxe** [comment]
In order to support enabling/disabling GitGutter via main menu or command pallet for single views, I moved the "enabled" setting to a Preferences.sublime-settings file which is located in the GitGutter package. This file is read by ST upon startup only. This means, if you just updated GitGutter without restarting ST, the value does not yet exist in memory. Therefore `view.settings().get("git_gutter_enable")` returns `None` which is the empty output. This return value is interpreted as "disable GitGutter". Sorry I wasn't aware of that issue. 

A simple restart of ST should fix that issue. I modified the code on master to handle the None value as True, so GitGutter will be enabled by default if the setting was not found for any reason.

**Comment by maxis1718** [comment]
Reinstalling package and then `GitGutter: Enable/Disable` works for me

**Comment by deathaxe** [comment]
Issues, which might have caused this issue are resolved.

**Comment by Djspaceg** [comment]
I hadn't realized that Xcode had updated which reset my agreement, which disabled the default `git` binary (until you agree to the new terms). After agreeing to the terms, git started working again and GitGutter resumed working. I had previously, unsuccessfully, tried many of the above steps.
