### ISSUE TITLE
Sort-of bug: deletion indicator is visually confusing if line above deletion end-wraps

### ISSUE THREAD

**Issue by csojinb** [jisaacks/GitGutter#448]
## Description

While writing some documentation, where an entire paragraph is treated as a single line in ST, I noticed that the deletion indicator is in a visually confusing spot. Easiest to explain with an example I think.

**Dummy starting doc:**
<img width="752" alt="screen shot 2017-09-21 at 3 26 31 pm" src="https://user-images.githubusercontent.com/6509003/30714711-e111d26c-9ee1-11e7-9569-c328fb198d78.png">

I want to remove the second paragraph here, deleting Lines 2 and 3. The expected resulting behavior is that the deletion indicator will appear between Lines 1 and Line 2 (formerly Line 4). 

**Actual behavior:**
<img width="752" alt="screen shot 2017-09-21 at 3 26 42 pm" src="https://user-images.githubusercontent.com/6509003/30714875-6a7a5c5e-9ee2-11e7-9d3c-95ead8bbd7e0.png">

However, because line 1 is quite long, my visual interpretation of where line 1 "is" takes up 6 rows of text space. So, I expect the indicator to show up _below_ the "end" of line 1 and above the beginning of line 2. Instead, what happens is that the deletion indicator appears immediately under the number for Line 1, even though the number for Line 2 is 5 spaces below. At-a-glance, this gives me the incorrect impression that something has been removed from the _middle_ of that first paragraph, rather than after it.

**Desired behavior:**
<img width="752" alt="desired-behavior" src="https://user-images.githubusercontent.com/6509003/30715274-b7393bea-9ee3-11e7-8556-49bec605d313.png">
I don't know if this is actually possible, but if the betweensy deletion indicator could be anchored to the top of line number that comes _after_ the deleted section, rather than to the bottom of the line number that comes before, I think that would be significantly clearer when viewed with long, wrapped lines.

## Support Info
Not sure if this is actually needed for this request, but I'm including it for thoroughness:

- Sublime Text 3143
- Platform: osx
- Arch: x64
- GitGutter Version could not be acquired!
- Install via PC: True
- git version 2.14.1
- mdpopups 2.1.1
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

(No idea why it says that GitGutter Version couldn't be acquired, but it's working fine. List Packages says that I have v1.7.5 installed.)

## Steps to Reproduce Issue
Also not sure if this is required, but again, thoroughness:

1. Write a long line that wraps to occupy multiple rows of space (or narrow the editor with end-wrapping turned on)
2. Add text on subsequent lines and commit
3. Remove text immediately below the long end-wrapped line

**Comment by deathaxe** [comment]
Thank you for your efforts to create such a descriptive issue report!

Unfortunately this issue can't be fixed. The gutter icons are normal pictures placed right next to the line number. There is no API or setting to tell ST something about desired vertical alignment.

The second issue about the version number will be fixed. I cleaned up the internal structure so the support module tries to read it from a no longer existing path. Good catch.
