### ISSUE TITLE
Usage with WSL?

### ISSUE THREAD

**Issue by gmask** [jisaacks/GitGutter#449]
I believe this is a request. On Windows I use the [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/faq) extensively and am trying to completely migrate my tooling to it. However setting `bash.exe -c "git"` as `git_binary` does not work. Is there a way to do this?

**Comment by deathaxe** [comment]
I did not yet play around with WSL myself as it is still beta in 1703 and some of my friends already crashed their installation with it. Don't have time for such. Therefore I don't have a complete idea of the number of edge cases required.

The major issue with calling git from a shell is the necessity to quote all git arguments as `bash -c "git diff -U0 --no-color --no-index ..."`. At the moment those arguments are passed to pythons `Popen` as normal list of arguments beginning with `git`.

A quick and dirty check with `sh.exe` which is provided by Git for Windows, this could be changed with little effort.

**But** this immediately arose another issue, which might cause much more trouble in several situations: 

Windows and Linux handle paths differently. GitGutter totally relies on python's `os.path` module as OS independent abstraction layer. Therefore it uses `\\` as path separator on Windows but `/` would be required to handle bash in WSL. There are many other such differences (symlinks, environment variables, ... ).

I guess I would need to touch any piece of code which is related to paths. And what if you want to use ST with repos on pure Windows then? You use the git in WSL to access your files on Windows? 

This request ends up in something like calling git from a remote shell on a different OS using ssh or something like that.

Sorry, but I don't think I will support such weird things in soon. 

Windows is Windows Linux is Linux. The desperate act of integrating future into Windows is something special.
