### ISSUE TITLE
Monokai Pro ❤️ GitGutter

### ISSUE THREAD

**Issue by Monokai** [jisaacks/GitGutter#450]
Just letting you know that [Monokai Pro](https://www.monokai.pro) supports GitGutter with custom high definition icons and matching colors. Couldn't find another way to contact you, so that's another one for your list of supported color schemes.

Thanks for your work :)

**Comment by jisaacks** [comment]
Cool! You can make a PR updated the read me if you want?

**Comment by Monokai** [comment]
Done!

**Comment by deathaxe** [comment]
Merged!
