### ISSUE TITLE
Thicker Bar theme for readability

### ISSUE THREAD

**Issue by jathanasiou** [jisaacks/GitGutter#453]
## Description

Currently, when using certain themes/editor combinations, the **Gutter Bars theme icons** are often partially covered by adjacent frame scrollbars and very hard to notice. This makes them less obvious and almost **easy to miss/ignore** in certain resolution or colour pallets. Attached are screenshots demonstrating the issue with and without adjacent frames respectively:

>
![with adjacent](https://user-images.githubusercontent.com/8679925/30809725-656fa09e-a20b-11e7-8670-e1fb07976e86.png) ![without adjacent](https://user-images.githubusercontent.com/8679925/30809724-656e5662-a20b-11e7-829d-1c50a1b65a2f.png)

_Do note that the above pics demonstrate the "Bars" theme and **not** "Bars Thin", which makes the issue even more prevalent._

> **Thicker Bar theme(s) addition:**
>
> - A thicker Gutter Bar will help alleviate both **readability**, functionality and antithetical aspects of the plugin.
> - With **independent theme options** such as "Bar Thick", "Bar Thicker" etc. users can opt-in to have larger bar widths, while unaffected users will still be able to use the current themes with their respective properties.
>

## Reproduction
In my particular case the following conditions manifested the problem
1. Sublime Text v3, build 3143 (release)
2. Theme: Agila Origin
3. Color scheme (editor area): Agila Origin Oceanic Next
4. Theme config:
```json
	"theme": "Agila Origin.sublime-theme",
	"theme_agila_auto_complete_yellow": true,
	"theme_agila_camouflage_semi": false,
	"theme_agila_compact_sidebar": true,
	"theme_agila_horizontal_scrollbar_pink": true,
	"theme_agila_horizontal_scrollbar_thinner": true,
	"theme_agila_modified_tab_marker_pink": true,
	"theme_agila_sidebar_heading_lightblue": true,
	"theme_agila_sidebar_light_icons": true,
	"theme_agila_sidebar_mini": true,
	"theme_agila_sidebar_plus_minus": true,
	"theme_agila_vertical_scrollbar_pink": true,
	"theme_agila_vertical_scrollbar_thinner": true,
	"theme_font_options": "directwrite"
```

**Comment by deathaxe** [comment]
GitGutter themes can be created by everybody and may be contained in any package (with ST3).

Everyone is free to modify existing icons or create new ones, place them in a separate package and add an empty `<Theme Name>.gitgutter-theme` file to the icon containing folder mark it as theme folder.

GitGutter searches for the `.gitgutter-theme` file in all packages including sub directories and uses the icons of the same directory.

**Comment by jathanasiou** [comment]
Graphics generation are a non-trivial task for the average user (in spite of them being developers) and this issue is probably applicable to others users too.  

> themes can be created by everybody and may be contained in any package

By that logic any enhancement issue is pointless, so I'm not sure what the point is.

**Comment by deathaxe** [comment]
The points are:

1. Just wanted to emphasize the possibilities.
2. The existing themes besides the Default one are just some examples.
3. A theme author can add gutter themes to his package as well if he decides the default ones not to look cute in combination with his theme or color scheme. 
4. Of course GitGutter can provide dozens of themes and everyone is welcome to contribute. 
5. I tried different widths of bars and found thicker ones looking quite odd. Maybe a theme with the bars aligned centered would be a better solution?
6. I am not a graphics specialist or themer. It took quite a while for me too to create the bunch of even very simple icons. I honestly don't like fiddling with gimp and co.

**Comment by jathanasiou** [comment]
I understand.
On this point

> I tried different widths of bars and found thicker ones looking quite odd. Maybe a theme with the bars aligned centered would be a better solution?

Given the screenshots, it seems that width is, indeed, not the issue and possibly not the solution either, but rather how adjacent scrollbars overlap with these icons, possibly due to ST3's layout. Center-alignment or even right-alignment offer a better experience.
I will try and fiddle to see if I can alter the alignment and if it is a nice alternative.
