### ISSUE TITLE
Popup disappears after less then a second 

### ISSUE THREAD

**Issue by adamdavidcole** [jisaacks/GitGutter#456]
## Description

... what is the issue / request ?
When I hover over the diff icon in the gutter, the popup shows up for an instant and then disappears.

I have tried uninstalling and reinstalling via the package manager, installing the package manually, upgrading to the pre-release version, etc. 

There are no errors in my console. 

Here is a gif of it occurring: 
![gitgutter bug](https://user-images.githubusercontent.com/5685294/31205598-4097e524-a927-11e7-8ee9-95ff622e2a98.gif)
 

## Support Info

- Sublime Text 3143
- Platform: osx
- Arch: x64
- GitGutter 1.7.6
- Install via PC: True
- git version 2.13.3
- mdpopups 2.1.1
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Hover over gutter icon
2. See popup appear and then immediately disappear 

Wish I had more helpful steps! Let me know if I can provide any other context -- it happens 100% of the time for me. Thanks!

**Comment by adamdavidcole** [comment]
Did some more digging: seems like a bad interaction between GitGutter and SublimeLinter when the `tooltips` setting is `true`. 

Not sure what is feasible here, but would be great to see these two popular packages working well together.

🙇

**Comment by deathaxe** [comment]
SublimeLinter popups are nasty and buggy. See https://github.com/SublimeLinter/SublimeLinter3/issues/619

They don't check whether other popups are already open, therefore just replace them or even hide tooltips not opened by itself. The only solution is to turn off SublimeLinter popups.

It's not a bug of GitGutter and can't be solved here. As the API doesn't handle multiple instances of popup requests, to decide which popups to show or hide, this kind of popup fighting might not be solved too easily on a package level at all.

The only chance is to check whether a popup is visible and keep quite. This is what GitGutter already does. More is not possible.
