### ISSUE TITLE
Status line similar to Git prompt provided by Git

### ISSUE THREAD

**Issue by gerardroche** [jisaacks/GitGutter#457]
Git provides a git prompt for command line. It's not very well [documented](https://git-scm.com/book/tr/v2/Git-in-Other-Environments-Git-in-Bash). The comments in the [relevant code](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh) are more enlightening.

It provides a bash function you can use for a Git prompt in the terminal:

![screenshot from 2017-10-08 11-50-49](https://user-images.githubusercontent.com/44148/31316203-e4d67730-ac20-11e7-9dde-f3e5599569ef.png)

![screenshot from 2017-10-08 11-51-19](https://user-images.githubusercontent.com/44148/31316204-e4dce57a-ac20-11e7-8aa5-86a5b0a2cd49.png)

![screenshot from 2017-10-08 11-51-42](https://user-images.githubusercontent.com/44148/31316206-e4e74b1e-ac20-11e7-904c-81b9671f5691.png)

![screenshot from 2017-10-08 11-51-56](https://user-images.githubusercontent.com/44148/31316205-e4e0869e-ac20-11e7-9e41-ea8fde002b58.png)

The configuration for the screenshots is roughly:

```
    GIT_PS1_DESCRIBE_STYLE="contains"
    GIT_PS1_SHOWCOLORHINTS="y"
    GIT_PS1_SHOWDIRTYSTATE="y"
    GIT_PS1_SHOWSTASHSTATE="y"
    GIT_PS1_SHOWUNTRACKEDFILES="y"
    GIT_PS1_SHOWUPSTREAM="verbose name"

        prompt_command_callback() {
            if test "$?" = 0; then
                prompt_char="\$"
            else
                prompt_char="\[\033[41m\]\[\033[30m\]\$\[\033[0m\]"
            fi

            # void __git_ps1 {pre} {post} {git info}
            __git_ps1 "╭─ \w " "\n╰$prompt_char " "\\u2387\\u0020\\u0020%s"
        }

        PROMPT_COMMAND="prompt_command_callback"

```

https://github.com/gerardroche/dotfiles/blob/master/src/.bashrc#L67

My current ST configuration is:

```
{
	"git_gutter_status_bar_text":
	[
		"{% if inserted != 0 %}+{{inserted}} {% endif %}",
		"{% if modified != 0 %}~{{modified}} {% endif %}",
		"{% if deleted != 0 %}-{{deleted}} {% endif %}",
		"⎇ {{branch}}"
	],
}
```

It would great to be able have status line that mirrors the git prompt i.e. upstream info, character indicators `%`, `*`, etc.

**Comment by r-stein** [comment]
You can use jinja2 to create the content line you want, but if I understand you correctly you also want to have additional variables, like staged files or untracked files?

**Comment by deathaxe** [comment]
You'd need some variables with general information about the whole repository status in the end?

I already was playing around with using `git status` command to use it for several things internally. Unfortunately I ended up in using `git status --porcelain=2` which is not supported by older git versions and had to drop it. I did not yet find a proper alternative without bloating the whole Promise() structure too much.

But maybe it's not too hard to query some status vars in the background in order to just provide them as variables for jinja2.

**Comment by gerardroche** [comment]
> but if I understand you correctly you also want to have additional variables, like staged files or untracked files?

Yes. The Git prompt indicates things via characters depending on the settings:


> # In addition, if you set GIT_PS1_SHOWDIRTYSTATE to a nonempty value,
> # unstaged (*) and staged (+) changes will be shown next to the branch
> # name.  You can configure this per-repository with the
> # bash.showDirtyState variable, which defaults to true once
> # GIT_PS1_SHOWDIRTYSTATE is enabled.
> 
> # You can also see if currently something is stashed, by setting
> # GIT_PS1_SHOWSTASHSTATE to a nonempty value. If something is stashed,
> # then a '$' will be shown next to the branch name.
> #
> # If you would like to see if there're untracked files, then you can set
> # GIT_PS1_SHOWUNTRACKEDFILES to a nonempty value. If there're untracked
> # files, then a '%' will be shown next to the branch name.  You can
> # configure this per-repository with the bash.showUntrackedFiles
> # variable, which defaults to true once GIT_PS1_SHOWUNTRACKEDFILES is
> # enabled.

https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh

So for example in the screenshots you'll notice that when I add the new fizz file it was indicated via`%`. When I modified the `README.md` it was indicated via `*`

Similarly, when I committed the changes `u+1 origin/master` indicates that you're `1` commit ahead of the upstream branch.

**Comment by deathaxe** [comment]
Supported by GitGutter 1.7.7+

**Comment by gerardroche** [comment]
Fantastic!

My first pass to get a status line that mirrors the git default:

```
	"git_gutter_status_bar_text":
	[
		"{% if inserted > 0 %}+{{inserted}} {% endif %}",
		"{% if modified > 0 %}~{{modified}} {% endif %}",
		"{% if deleted > 0 %}-{{deleted}} {% endif %}",
		"⎇ {{branch}}",
		"{% if modified_files or added_files or deleted_files or staged_files %} ",
		"{% if modified_files %}*{% elif deleted_files %}*{% endif %}",
		"{% if staged_files %}+{% endif %}",
		"{% if added_files %}%{% endif %}",
		"{% endif %}",
		"{% if remote %}",
		"{% if ahead > 0 %} u+{{ahead}}",
		"{% elif behind > 0 %} u-{{behind}}",
		"{% elif ahead == 0 and behind == 0 %} u=",
		"{% endif %}",
		" {{remote}}",
		"{% endif %}"
	]
```
