### ISSUE TITLE
Improved support for NeoVintageous jump to next/prev change

### ISSUE THREAD

**Issue by gerardroche** [jisaacks/GitGutter#458]
It would be great if the `git_gutter_next_change` and `git_gutter_prev_change` commands accepted a `count` and `wrap` options. A `count` meaning jump to the nth change, and `wrap` a boolean that enables and disables wrapping of results i.e. `git_gutter_next_prev_change_wrap`.

Ultimately the new API would allow (where `count` defaults to `1` and `wrap` defaults to whatever the global setting `git_gutter_next_prev_change_wrap` is.

```
self.view.run_command('git_gutter_next_change', {'count': 1, 'wrap': False})
self.view.run_command('git_gutter_prev_change', {'count': 3, 'wrap': False})
```

## Reason

[NeoVintageous](https://github.com/NeoVintageous/NeoVintageous) provides GitGutter support for jumping forward and backwards through changes.

From the NeoVintageous [documentation](https://github.com/NeoVintageous/NeoVintageous/tree/15d1bd553a94ef34f9b54af0492936aab7693a8a#documentation):

Command | Description | Documentation | Dependencies | Notes
------- | ----------- | ------------- | ------------ | -----
`[c` | Jump backwards to the previous start of a change. | [diff](https://neovim.io/doc/user/diff.html#[c) | [Git Gutter] | Disable wrapping: set `git_gutter_next_prev_change_wrap` to `false` (Preferences &gt; Settings)
`]c` | Jump forwards to the next start of a change. | [diff](https://neovim.io/doc/user/diff.html#]c) | [Git Gutter] | Disable wrapping: set `git_gutter_next_prev_change_wrap` to `false` (Preferences &gt; Settings)
 
The commands allow you to jump to the next or prev change with `]c` and `[c`. 

The [relevant code](https://github.com/NeoVintageous/NeoVintageous/blob/15d1bd553a94ef34f9b54af0492936aab7693a8a/lib/cmds/vi_motions.py#L2119) looks like this:

```
# https://neovim.io/doc/user/diff.html#[c
class _vi_left_square_bracket_c(ViMotionCommand):
    def run(self, mode=None, count=1):
        for i in range(count):
            self.view.run_command('git_gutter_prev_change')

# ...

# https://neovim.io/doc/user/diff.html#]c
class _vi_right_square_bracket_c(ViMotionCommand):
    def run(self, mode=None, count=1):
        for i in range(count):
            self.view.run_command('git_gutter_next_change')
```

The counts work by prefixing the commands with a number e.g. `3]c` jumps to the 3rd change from the cursor.

An issue when using counts is that wrapping the results is confusing e.g. imagine your at the 3rd last change and you hit `4]c`, if it wraps you don't know where you are in the document. Ideally you want it to stop at the end and display a status message. 

You can disable wrapping via `git_gutter_next_prev_change_wrap`, but that's a global setting and the user may not want to disable that globally. So optional `wrap` argument to the commands would be useful.

**Comment by deathaxe** [comment]
Not a big deal to extend the commands with those arguments.

**Comment by r-stein** [comment]
I would say wrap is by default `null`/`None` to use the global setting and can be `true`/`false` to explicitly set it.

**Comment by deathaxe** [comment]
... and count argument defaults to 1 if not present.

**Comment by gerardroche** [comment]
> I would say wrap is by default null/None to use the global setting and can be true/false to explicitly set it.

Yes. It should default to the global setting `git_gutter_next_prev_change_wrap`, which is equivalent to the current behaviour.

> ... and count argument defaults to 1 if not present or < 1.

I think the count should default to `1`, which is equivalent to the current behaviour i.e. the `git_gutter_next_change` command jumps to the next change and `git_gutter_prev_change` jumps to the prev change. Passing `2` to `git_gutter_prev_change` would jump backward twice, which is the same as calling `git_gutter_prev_change` twice.

For example these are the commands internal to NeoVintageous:

```
# https://neovim.io/doc/user/diff.html#[c
class _vi_left_square_bracket_c(ViMotionCommand):
    def run(self, mode=None, count=1):
        for i in range(count):
            self.view.run_command('git_gutter_prev_change')

# https://neovim.io/doc/user/diff.html#]c
class _vi_right_square_bracket_c(ViMotionCommand):
    def run(self, mode=None, count=1):
        for i in range(count):
            self.view.run_command('git_gutter_next_change')
```

**Comment by deathaxe** [comment]
You can try the change. It's already merged to master. You can therefore simplify your functions soon. Need to check whether to work on the status issue before deciding when to make a next release.

**Comment by deathaxe** [comment]
Supported by GitGutter 1.7.7+
