### ISSUE TITLE
GitGutter hides Anaconda gutter marks

### ISSUE THREAD

**Issue by AlexLamson** [jisaacks/GitGutter#467]
## Description
Even when not in a git repo, Git Gutter takes precedence over the Anaconda linter in the gutter bar.

## Support Info
- Sublime Text 3143
- Platform: windows
- Arch: x64
- GitGutter 1.7.8
- Install via PC: True
- git version 2.8.1.windows.1
- mdpopups 3.0.3
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue
1. Install git gutter from package control
2. Install anaconda from package control
3. open a python file with lint errors
4. None of anaconda's gutter marks show up on the lines with lint errors

**Comment by deathaxe** [comment]
See: https://github.com/jisaacks/GitGutter#protected-regions
