### ISSUE TITLE
Branch name with dot cannot be showed correctly on status bar

### ISSUE THREAD

**Issue by ParadiseDS** [jisaacks/GitGutter#468]
## Description

macOS 10.12.2, sublime 3143 and GitGutter 1.7.8.

When status bar text is configured to show the branch name with `{{branch}}`, a branch name with dot in it cannot be showed correctly. 

e.g. Branch `release-1.2` will be showed as `release-1`, the `.2` text is missing.

## Support Info

- Sublime Text 3143
- Platform: osx
- Arch: x64
- GitGutter 1.7.8
- Install via PC: True
- git version 2.14.1
- mdpopups 3.0.3
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Configure gitgutter status_bar_text setting as following:

```
"status_bar_text": [
	  "{{state}}->{{branch}}",
	  "{% if compare not in ('HEAD', branch) %}, against {{compare}}{% endif %}",
	  "{% if deleted != 0 %}, {{deleted}}-{% endif %}",
	  "{% if inserted != 0 %}, {{inserted}}+{% endif %}",
	  "{% if modified != 0 %}, {{modified}}≠{% endif %}"
]
```

2. Enter a git repo, create a branch whose name is `release-1.2` and switch to it.
3. Open a file tracked in the repo in sublime.
4. The status bar text is showed as `committed->release-1`, while `committed->release-1.2` is expected.

**Comment by deathaxe** [comment]
Fixed in 1.7.9
