### ISSUE TITLE
sh

### ISSUE THREAD

**Issue by dpleskac** [jisaacks/GitGutter#470]
Before creating an issue, please check whether ...

_1. TROUBLESHOOTING section in README can help to solve your problem._

_2. an open issue exists for your problem._

**If not, please read and fill out this template by replacing the instructions with appropriate information.**

---

## Description

... what is the issue / request ?

>
> **For feature requests or proposals:**
>
> - Clearly define in as much detail as possible how you imagine the feature to work.
> - Examples are also appreciated.
>
> **For bugs and support questions:**
>
> - Describe the bug/question in as much detail as possible to make it clear what is wrong.
> - Provide errors from console (if available).
> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.

## Support Info

...

> Run the following command from the menu: 
> 
>   `Preferences->Package Settings->GitGutter->Support Info`.
> 
> or from the command pallet:
> 
>   `GitGutter: Support Info`
> 
> Paste the result here.

## Steps to Reproduce Issue

1. First step...
2. Second step...
3. Third step...

> In case of a bug report, please provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**Comment by deathaxe** [comment]
No information provided
