### ISSUE TITLE
bug: {{branch}} text mangled by color escapes

### ISSUE THREAD

**Issue by rivy** [jisaacks/GitGutter#474]
## Description

"{{branch}}" text is mangled by color escapes, or just missing, when git config contains "color.status=always".

## Support Info

- Sublime Text 3154
- Platform: windows
- Arch: x64
- GitGutter 1.7.9
- Install via PC: True
- git version 2.14.1.windows.1
- mdpopups 3.2.0
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. enable status colors on shell command line (the first line is the key line):

    ```
    git config --global color.status always
    git config --global --unset color.status.header
    git config --global color.status.added "bold green"
    git config --global color.status.deleted "bold red"
    git config --global color.status.updated "bold yellow"
    git config --global color.status.changed "green"
    git config --global color.status.untracked "bold magenta"
    git config --global color.status.nobranch "bold red bold black"
    ```

1. Using SublimeText (with GitGutter installed/working), open a tracked git repository file.

1. "{{branch}}", which is displayed by default on the status line, will contain color escape codes, eg, "[32mmaster[m".

1. Additionally, if `git config --global color.status.header "bold blue"` is used, parsing completely fails and "{{branch}}" will be "unknown".

## Fix

Using the git option "-c color.status=never" will definitively disable color for the `git status` command, fixing both issues.

PR #475 contains a fix.

*Note:* the fix has only been tested on my machine.

**Comment by deathaxe** [comment]
Fixed in 1.7.10
