### ISSUE TITLE
GitGutter treats all files in a subfolder as untracked, Git itself does not

### ISSUE THREAD

**Issue by Drakim** [jisaacks/GitGutter#478]
## Description
GitGutter treats all the files in one of my subfolders named "prg" as untracked, even though they are all tracked. Every single line in the files is marked with a * star, and at the bottom status bar of sublime it says "File is untracked".

Files at my project root, and files in other subfolders are not experiencing this bug, it only happens in this particular subfolder. Doesn't matter which branch I'm sitting on.

If I open a random file in the affected subfolder and edit it, GitGutter still treats it as untracked, while my shell's git detects the change just fine. [Image to demonstrate](https://i.imgur.com/yoxPl0P.png).

This started happening a little bit after I was rebasing a bunch to clean up my history. Not using any gitignore.

My GitGutter settings are:
`
{
    "diff_popup_default_mode": "diff",
    "git_binary": "C:/Program Files/Git/bin/git.exe"
}
`

I've tried changing what commit GitGutter should be comparing to, it doesn't matter if I point it to HEAD or any other commit.

I tried copying my entire project to another location, and the bug still happens there. I deleted the .git folder and inited a new git repo, and now the subfolder files were being tracked again. So it seems like the bug only manifests under certain conditions present in my git repo (maybe because of my rebasing?)

## Support Info
- Sublime Text 3143
- Platform: windows
- Arch: x64
- GitGutter 1.7.10
- Install via PC: True
- git version 2.12.0.windows.1
- mdpopups 3.3.0
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue
Not sure how to help you reproduce it, other than to just give you my entire project folder, warts and all, and hope you get the same issue on your side.

[project.zip](https://github.com/jisaacks/GitGutter/files/1539442/project.zip)

(The git repo is in the "src" folder as opposed to project root.)

**Comment by deathaxe** [comment]
GitGutter shows the files in the `prg` folder as untracked as git is not able to read those files. As it seems not to exist in your database it is displayed as untracked.

Debug log:
```
GitGutter: "git cat-file" failed with "fatal: Not a valid object name 035a596ff46f1c32666235f52929b9fae5e13340:prg/prg001.asm"
GitGutter: "git diff" failed with "usage: git diff --no-index <path> <path>"
```

GutGutter uses the plumping `git cat-file` command to read file content for some reasons, but the highlevel `git show object:prg/prg001.asm` fails as well - also from console.  It says `fatal: Path 'prg/prg001.asm' exists on disk, but not in 'object'.`

Seems you somehow broke your database.

**Comment by Drakim** [comment]
Huh... that's bizarre. I can still use those files just fine in vanilla git, I tested just now by editing one, staging it and committing. Whatever I broke somehow doesn't bother git itself.

Do you know if there is some sort of "scan and repair" command built into git, or do I need to start a new repo entirely?

**Comment by deathaxe** [comment]
I ran the following to  commands to try to cleanup the repo, but without success. 
```
git reflog expire --expire-unreachable=now --all
git gc --prune=now --aggressive
git fsck --full
```

Maybe just this one snapshot which got broken. Not sure. Wasn't faced to such an issue up to now.

My GitExtensions can read the folder, too, even though it takes a while. Don't know which command is used to do so.

**Comment by Drakim** [comment]
I'll just bite the bullet and redo the repo from the ground up, I only had a few commits anyways.

Thanks very much for the help, GitGutter is amazing!

**Comment by Drakim** [comment]
For anybody who encounters this problem in the future, I discovered that the issue was caused by a mismatch in uppercase/lowercase between the repo and history.

Git had the folder stored as "PRG" while the actual folder was "prg". Windows is insensitive to file & folder case, which git kinda tries to work around normally.

**Comment by deathaxe** [comment]
The git database is per design always case sensitive. All `--icase-pathspecs` arguments and settings don't apply to commands directly working with tree objects.
