### ISSUE TITLE
Version for another ed?

### ISSUE THREAD

**Issue by Alexey-T** [jisaacks/GitGutter#490]
Hi. Very useful addon for ST. Thanks. Can you port (make new) for CudaText editor? I may give some donate for it.
Py API is http://wiki.freepascal.org/CudaText_API

**Comment by r-stein** [comment]
There are already similar packages for other editors as stated int the readme: https://github.com/gitgutter

Porting a package to an other editor is a lot of work and should be done by people using the editor.
