### ISSUE TITLE
Sublime Test 2 + GitGutter UI bugs

### ISSUE THREAD

**Issue by pmn4** [jisaacks/GitGutter#494]
## Description

I have used GitGutter for years (can't thank you enough!) but recently there seems to be an error causing some issues with the ST2 UI. I wish I could pinpoint the commit, but it started within the last few months, I'd say? Not really sure.

Here is my Sublime before installing:
<img width="493" alt="gitgutter-before" src="https://user-images.githubusercontent.com/1158287/39258994-5f8e6f7e-4883-11e8-9966-b5b51002ba66.png">

Here is the same code after installing:
<img width="558" alt="gitgutter-after" src="https://user-images.githubusercontent.com/1158287/39259010-68568e8e-4883-11e8-86bf-854e8a33050b.png">
(red box: the tabs UI is broken)
(red arrow: the highlighted text is not highlighted)
(yellow box: GitGutter indicators are missing)

I am seeing these errors in the console:
```
GitGutter: "git cat-file" failed with "fatal: Not a valid object name a8b053244d59c9f37281940b18479deb40ab1181:imports/plugins/core/catalog/server/methods/catalog.app-test.js"
GitGutter: "git diff" failed with "usage: git diff --no-index <path> <path>"
```

Lastly, I have several ST2 projects/windows open at any given time, and this issue is _not_ always present. It makes me think there is some particular file state (like a deleted cached file, perhaps?) which triggers it.

Please let me know what other information I can provide!

## Support Info

```
- Sublime Text 2221
- Platform: osx
- Arch: x64
- GitGutter Version could not be acquired!
- Install via PC: True
- git version 2.14.3 (Apple Git-98)
- mdpopups not installed!
- markdown not installed!
- pygments not installed!
- jinja2 2.8
```

## Steps to Reproduce Issue

1. No special steps, I get this when I install GitGutter (although, not _always_)

**Comment by deathaxe** [comment]
I have no idea why GitGutter should prevent the selection or tabs to be rendered, but after having a closer look into it, I found the `TempFile` class to use an ExceptionClass, which is not supported by python 2.6. 

Maybe the resulting uncaught exception causes the rendering issues on MacOS, even though it does not on Windows.

Please check, whether the patched version from https://github.com/jisaacks/GitGutter/tree/pr/fix-temp works for you.

**Comment by pmn4** [comment]
wow, that was an incredibly fast response. I'll check it out now

**Comment by pmn4** [comment]
@deathaxe looks like that resolved it. thanks again for hopping on this so quickly

**Comment by deathaxe** [comment]
Fixed in 1.7.14

**Comment by pmn4** [comment]
Hi @deathaxe, I'm not sure if anything has changed, but this issue started happening again today after my Sublime crashed and reopened.
This time I do not see anything in the console to help. What information can I give you?

**Comment by pmn4** [comment]
checked out `master`, now seeing this in the console:
```
Reloading plugin /Users/pmn/Library/Application Support/Sublime Text 2/Packages/GitGutter/release.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./release.py", line 84
    obj={v: MESSAGE_DIR + '/' + v + '.txt' for v in version_history},
                                             ^
```

**Comment by deathaxe** [comment]
you can delete that file. It is meant for quickly cutting releases and is not part of the normal package.

It is not compatible with py2. As I never used ST2, I am not interested in compatibility of that internally used dev script.
