### ISSUE TITLE
Add windows WSL

### ISSUE THREAD

**Issue by vivl4725** [jisaacks/GitGutter#500]
Please add a WSL😢

**Comment by deathaxe** [comment]
I basically managed to create a first implementation to run git via wsl.exe but I guess you won't like the results very much.

1. git over WSL is about 2 to 3 times slower. Commands which take 7ms on Linux, 60ms on Windows now take 160 or even 200ms. Windows' interprocess communication itself is fucking slow, but the WSL shit ...
2. The killer is WSL truncating output of git in many situations. GitGutter reads the file content of a committed file by calling `git cat-file`. If a file is larger than 1...2kB the content is very often truncated, which causes all following lines to be marked changed or inserted.

Googling about this issue reveals it to be some kind of bug or limitation of WSL or the way Windows communicates with the linux layer. While there seem to be some workarounds for VS Code and nodeJS I did not manage to find approaches for python. 

Not sure whether its worth putting more effort in it. Honestly, I can't recommend WSL.

**Comment by vivl4725** [comment]
I am very happy. In fact, I'm an ardent user of ArchLinux ... But, because of the university, I'll have to use windows. On git for winodws I do not watch as it already stands in WSL on ArchLinux :)

**Comment by deathaxe** [comment]
Support added in 1.8.0
