### ISSUE TITLE
How to change color of the Gutter

### ISSUE THREAD

**Issue by nikitavoloboev** [jisaacks/GitGutter#502]
I would like to change the color of the Gutter from `#1C222C` to `#212733`. 

This one here where the + is shown:

![2018-06-08 at 14 01](https://user-images.githubusercontent.com/6391776/41157054-a1d64974-6b24-11e8-9ed7-6f56d3551db0.png)

I use [Ayu theme](https://github.com/dempfi/ayu) for Sublime and it's annoying to have it be a different color.

**Comment by deathaxe** [comment]
The colors are defined in the color scheme (ayu-...tmTheme).

If you are using ST3176 you can create an _ayu-mirage.sublime-color-scheme_ in your user directory with the following content.

```
{
    "rules":
    [
        {
            "scope": "markup.deleted.git_gutter",
            "foreground": "#F92672"
        },
        {
            "scope": "markup.changed.git_gutter",
            "foreground": "#967EFB"
        },
        {
            "scope": "markup.inserted.git_gutter",
            "foreground": "#A6E22E"
        },
        {
            "scope": "markup.ignored.git_gutter",
            "foreground": "#565656"
        },
        {
            "scope": "markup.untracked.git_gutter",
            "foreground": "#565656"
        }
    ]
}
```

If you select that _Packages/User/ayu-... .sublime-color-scheme_ ST will overload the color definitions from the original one with those you defined there.

**Comment by nikitavoloboev** [comment]
> If you select that Packages/User/ayu-... .sublime-color-scheme ST will overload the color definitions from the original one with those you defined there.

I am not sure how to do this step. I do have ST3176 build.

**Comment by deathaxe** [comment]
The Command Palette contains a command called _UI: Select Color Scheme_

It lists all available color schemes. It will list ayu-mirage twice if you created the file in your User directory. One of them shows _User/_ in the second line (I use Theme Switcher which displays the second line better)

![screenshot](https://user-images.githubusercontent.com/16542113/41166242-15a038b8-6b40-11e8-9839-77c23f3edf8e.png)

**Comment by nikitavoloboev** [comment]
I did that [here](https://github.com/nikitavoloboev/dotfiles/tree/master/sublime).

However I only have one theme shown to me:

![2018-06-08 at 17 28](https://user-images.githubusercontent.com/6391776/41166769-6b9af270-6b41-11e8-8c07-f496ecee9b3d.png)

I did restart Sublime Text.

**Comment by deathaxe** [comment]
Looks like ST's default UI module hides color schemes of the same name located within the User directory. This makes sense for sublime-color-scheme files as they are merged without respect of their location, but does not work for the "old" tmTheme format. 

You'd need to manually set the "color_scheme" setting in your preferences to "ayu-mirage.sublime-color-scheme" or use Theme Menu Switcher package

**Comment by nikitavoloboev** [comment]
But the theme is only four rules.  

I tried to do this: `"color_scheme": "Packages/ayu/ayu-mirage.sublime-color-scheme",`

But that doesn't work. It made Sublime all white. Is that what you meant?

**Comment by deathaxe** [comment]
You point to the wrong path.

Use `"color_scheme": "Packages/User/ayu-mirage.sublime-color-scheme",` as your custom file is located there.

**Comment by deathaxe** [comment]
Not needed (and not recommended). One of the charming features of the new `sublime-color-scheme` format is it works just the same way as the `Preferences.sublime-settings` do. So you just define the stuff you want to modify in a short readable file within your User package.

If the original color-scheme is updated the changes are applied normally.

Moving the whole color scheme to the User file was the way you had to do it in the past as the `tmTheme` format doesn't support merging several files. The disadvantage is updates of the original file not to apply anymore.

I just do exactly what I described above. Wrote a short `ayu-dark.sublime-color-scheme` with the stuff I wanted to change, selected it and that's it.

**Comment by nikitavoloboev** [comment]
Yeah but when I do this change it forgets about me using Ayu completely. 

And when I go to change the theme back to `Ayu Mirage` from the command palette it overwrites the setting in preferences. I can't get both themes work side by side.

**Comment by deathaxe** [comment]
Therefore I use _Theme Menu Switcher_ which shows the user file.

**Comment by deathaxe** [comment]
Added a section to the docs about it. See: https://jisaacks.github.io/GitGutter/coloring/
