### ISSUE TITLE
Feature Request: Which files are under version control?

### ISSUE THREAD

**Issue by tilo** [jisaacks/GitGutter#504]
GitGutter is super useful! Thank you for writing this!

One thing I'm missing in the overall flow is that there is no way to see in the sidebar
which files are under version control. (yes, I shouldn't make such a mess in the first place)

I know this is not really the core of this extension, but if that could be solved, it could help a lot.

**Comment by deathaxe** [comment]
There is no API in Sublime Text to mark or highlight tree items at all. So I guess there is no way to implement this feature at the moment.

**Comment by tilo** [comment]
thank you for your reply @deathaxe !
