### ISSUE TITLE
Gitgutter writes to .git/index.lock any time I change tabs

### ISSUE THREAD

**Issue by pineapplemachine** [jisaacks/GitGutter#506]
## Description

Sublime overwrites `.git/index.lock` when I so much as switch tabs as long as the gitgutter plugin is enabled (v1.8.0). It also happens if I focus a window other than Sublime, and then focus the open Sublime window for a file in my git repository. I am _pretty_ sure this only started happening recently, since I don't recall my file watcher for a project I'm working on being triggered by tab switching when I was working on it before.

It's trivial to make the watcher ignore changes to this particular file, but I still ideally would like to disable the apparently unneeded disk writes. How can I stop this behavior? If I can't currently, I would appreciate a configuration option to disable it.

I tried assigning `focus_change_mode` in the user settings to false, and this did not affect the behavior.

edit: I tried a few earlier GitGutter releases and the behavior occurred for them too. If this behavior only started recently, it wasn't because of a version upgrade.

## Support Info

- Sublime Text 3176
- Platform: osx
- Arch: x64
- GitGutter 1.8.0
- Install via PC: True
- git version 1.9.3 (Apple Git-50)
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by deathaxe** [comment]
GitGutter does not write to that file at all.

GitGutter does nothing else but running normal git commands like `git cat-file`, `git ls-files`, ... .
It's git which sets/resets locks each time it accesses the index to ensure only one git running instance to alter the index at a time.

Therefore GitGutter sets the environment variable `"GIT_OPTIONAL_LOCKS": 0` to tell git to omit as much unneeded locks as possible. But this behavior was added in one of the recent >2.14 versions and therefore is ignored by your quite old one.

**Comment by pineapplemachine** [comment]
I updated git and the watcher no longer sees changes to index.lock after switching tags or window focus. Thank you for your help!
