### ISSUE TITLE
Modified line GitGutter color is similar to Sublime Text3 GitHub color scheme

### ISSUE THREAD

**Issue by PriyathamKommula** [jisaacks/GitGutter#509]
## Description

  GitGutter modified lines color and  the Sublime Text 3 **GitHub Color Scheme** are almost similar.

- How to change the color for the GitGutter modified lines because right now I get the following issue

> Here is a picture of the issue

<img width="40" alt="screen shot 2018-08-07 at 4 23 08 pm" src="https://user-images.githubusercontent.com/8453037/43800468-658ff0d2-9a5e-11e8-897a-fa7f88b2cd45.png">

Lines between 25 and 26 are removed

Lines 27, 29 and 30 are modified (The color is very hard to differentiate)

Line 33 is a new line added

## Support Info

- Sublime Text 3176
- Platform: osx
- Arch: x64
- GitGutter edca21e
- Install via PC: True
- git version 2.18.0
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Install GitGutter Sublime Text3 Package
2. Install DA UI Sublime Text3 Package
3. Install GitHub Color Theme Sublime Text3 Package
4. Select Theme... Open Command Pallet > UI: Select Them > DA.sublime-theme
5. Select Color Scheme... Open Command Pallet > UI: Select Color Scheme > GitHub  
6. Modify code which is integrated with Git which shows the similar gitgutter modified lines color and 
    Color Scheme

**Comment by deathaxe** [comment]
The colors are defined in the color scheme. So this is what needs to be modified. [GitGutter's Documentation](https://jisaacks.github.io/GitGutter/coloring/) contains a dedicated section describing briefly the way how to modify the gutter icon coloring.
