### ISSUE TITLE
GitGutter doesn't work on windows

### ISSUE THREAD

**Issue by linusr** [jisaacks/GitGutter#510]
## Description

... what is the issue / request ?
GitGutter doesn't work as expected. Console shows error 'git not found or working!'.
Tried configuring git_binary with default 'git' or git from cmder with no luck.
git works from Command Prompt/Power Shell.
Somehow VCSGutter works, so assuming it could be problem in Gitgutter. Have not specified any git path for VCS Gutter.

## Support Info

...

> Run the following command from the menu: 
> 
>   `Preferences->Package Settings->GitGutter->Support Info`.
> 
> or from the Command Palette:
> 
>   `GitGutter: Support Info`
> 
> Paste the result here.

- Sublime Text 3176
- Platform: windows
- Arch: x64
- GitGutter cb59a4a
- Install via PC: True
- git version 2.8.0.windows.1
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by deathaxe** [comment]
As the support info display the correct git version, I wonder why it should not work.

The error message you see is displayed if calling `git --version` wouldn't return a valid version string which can be matched with a regex. This normally means git was not found or the command points to something else.

If you can run git from command prompt it is not required to configure the `git_binary` setting.

`GitGutter cb59a4a` says you directly pull from master? Is it in sync with upstream?

I honestly never tried with git older than 2.10 on Windows. Maybe some decoding issue of git's output. No idea. I always run git for windows without any special setups.

**Comment by linusr** [comment]
Tried with latest portable version of Git for Windows,

`GitGutter: C:/Users/XYZ/Apps/Git-2.18.0-64/bin/git.exe not found or working!`

Git works fine from cmd,
`C:\Users\XYZ\Apps\Git-2.18.0-64\bin
λ .\git.exe --version
git version 2.18.0.windows.1`

**Comment by deathaxe** [comment]
Could you try to add `"debug": true` to your _GitGutter.sublime-settings_ file and have a look for some maybe more detailed error messages in the console?

**Comment by linusr** [comment]
With debug enabled below two lines gets printed,
`GitGutter: C:/Users/XYG/Apps/Git-2.18.0-64/bin/git.exe not found or working!
GitGutter: disabled for "File" because git is not working`

**Comment by deathaxe** [comment]
Just added a little bit more debug info printing. Can you please pull from master and restart ST? Let's see what it says, then.

**Comment by linusr** [comment]
Timeout!!

`Traceback (most recent call last):
  File "C:\Users\XYZ\Apps\Sublime Text Build 3176 x64\sublime_plugin.py", line 914, in is_enabled_
    ret = self.is_enabled(**args)
  File "C:\Users\XYZ\Apps\Sublime Text Build 3176 x64\Data\Packages\GitGutter\modules\commands.py", line 105, in is_enabled
    elif not self.git_handler.version(validate):
  File "C:\Users\XYZ\Apps\Sublime Text Build 3176 x64\Data\Packages\GitGutter\modules\handler.py", line 131, in version
    proc.wait(0.5)
  File "./python3.3/subprocess.py", line 1163, in wait
subprocess.TimeoutExpired: Command '['C:/Users/XYZ/Apps/Git-2.18.0-64/bin/git.exe', '--version']' timed out after 0.5 seconds`

Went ahead and modified handler.py to increase time out and voila it worked. But still puzzles me why `git --version` should take 2 seconds.

`proc.wait(2.0)`

**Comment by deathaxe** [comment]
I was faced to such an issue last year ago. Suddenly it took `git --version` 5s to return the version. It should not take longer than 50 or 100ms. _(On linux it takes only 2 .. 7ms!!)_ As `git --version` must be called synchronously as the TextCommands rely on it. ST freezes until the process call returns, which is the reason for the timeout. I hesitate to increase the value too much.

Seems to be a Windows and/or AntiVirus issue. I updated AV software and everything was fine again.

**Comment by deathaxe** [comment]
Increased the timeout to 1 second. More would be too annoying. Git must return a version within 50 to 100ms on Windows in normal situations. Maybe we find a better solution to check for git working properly in the future, but at the moment nothing more can be done.

Therefore I close the issue.
