### ISSUE TITLE
New Blame feature interacts poorly with search highlighting

### ISSUE THREAD

**Issue by howardjohn** [jisaacks/GitGutter#512]
## Description

When using the new Blame annotation feature, the annotations popping up conflict with search.

Steps:
1. Ctrl + F some word.
2. It gets highlighted from the search.
3. Annotation pops up a few ms later, which causes the word to no longer be highlighted by the search.

The matched word is still selected, just not highlighted by search. Because of this, I don't think it changes the functionality of search, just cosmetically removes the highlight
 
## Support Info

- Sublime Text 3176
- Platform: linux
- Arch: x64
- GitGutter 1.9.0
- Install via PC: True
- git version 2.18.0
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by howardjohn** [comment]
Got it. That is what I figured, but thought I would bring it to attention anyways

**Comment by indirectlylit** [comment]
Bummer - I like the annotation, but will probably turn it off due to this.

I filed a Sublime issue: https://github.com/SublimeTextIssues/Core/issues/2422 - feel free to add details or upvote.

**Comment by indirectlylit** [comment]
improved by GitGutter 1.9.5:

* Disable line annotation if multiple cursors are visible
* Disable line annotation if selection is not empty

(thanks for the tip @BenjaminSchaaf)
