### ISSUE TITLE
show_line_annotation toggle does not work

### ISSUE THREAD

**Issue by dougc84** [jisaacks/GitGutter#513]
Recently, GitGutter was auto-updated, and now inlines blame annotations.  As I usually have either two or three split panes open at once, this causes wrapping on files, making it awkward to navigate around, as it pushes lines up and down as I move with my keyboard.

I have gone in my user settings and set:

```json
"show_line_annotation": false,
"line_annotation_text": ""
```

and done the same in project settings under the `settings` key.  I'm sure the latter key (`line_annotation_text`) isn't explicitly necessary, but I gave it a shot and it made no change, even after closing out of Sublime and reopening.

I've had to disable GitGutter because I found this too annoying to use in any capacity.

If this new "feature" isn't line annotation, I'm not sure what this new feature is - the documentation doesn't show any other keys that could indicate what this might be.

Thank you.

---

Support info:

- Sublime Text 3176
- Platform: osx
- Arch: x64
- GitGutter 1.9.0
- Install via PC: True
- git version 2.15.2 (Apple Git-101.1)
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by dougc84** [comment]
A little more digging revealed this shouldn't be set in the user settings file, but, instead, in the package settings file.  However, that still means this toggle doesn't work per-project, which is something that looks to be indicated in the documentation.

**Comment by deathaxe** [comment]
### About word wrap

It is a known issue of phantoms to not play correct with that feature.

Therefore the line annotation is set to `"auto"` by default, which should disable it if word wrap is enabled in your document. Maybe this logic does not work in your setup?

### About user-/project-/syntax-/view-specific settings

Please refer to the first paragraphs of http://jisaacks.github.io/GitGutter/settings/ to learn how to handle user-settings, project-settings or per-view-settings.

You can also use _PackageDev_ to automatically receive completions for valid settings keys.

_All settings need to be prefixed with `git_gutter_` to be placed in user-/project-/syntax-/view-specific settings._
