### ISSUE TITLE
Add an option to filter out "not committed yet" line annotations?

### ISSUE THREAD

**Issue by vdh** [jisaacks/GitGutter#517]
## Description

I've found that the line annotation feature got too distracting while editing code and I had to disable it, since it would always be popping in with an unhelpful `You (just now) · not committed yet` on areas I was working on.

I think it could be more useful if there was an option to only show annotations for committed lines. Something like a `committed` option that behaves like `auto`, or some other way to filter the annotations.

## Support Info

- Sublime Text 3176
- Platform: osx
- Arch: x64
- GitGutter 1.9.2
- Install via PC: True
- git version 2.18.0
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by squallstar** [comment]
@deathaxe I do have the `draw_centered` mode enabled, I guess that's what causing the error then. Note that this wasn't happening a few days ago so the issue must have been recently introduced.

**Comment by squallstar** [comment]
@deathaxe the issue seems to happen even when the `draw_centered` is disabled:

![image](https://user-images.githubusercontent.com/574210/45440438-8669fd00-b6bc-11e8-968c-b0c4d2a157d5.png)

**Comment by deathaxe** [comment]
Just found looking at the wrong settings object. Therefore the `draw_centered` is not working as expected. Will fix that.

If you open the console with this view being open and enter the following commands one after the other, what do they return?

```
view.settings().get('word_wrap')

view.scope_name(0)
```

The phantom mast be displayed in the same line.

**Comment by vdh** [comment]
@squallstar @deathaxe Um sorry, but did you two just hijack my issue and then close it based on a separate and mostly unrelated bug? ☹️

**Comment by deathaxe** [comment]
Yes and no.

Yes - the issue was hijack by @squallstar and I answered his question.

No - the issue was not closed because of the hijacked issue to be fixed but because I completely disabled line annotation for uncommitted lines for now. Sorry but I am too lazy to add another option for it now.

**Comment by squallstar** [comment]
@vdh sorry at first I thought it was related and only realised it's a different bug when @deathaxe replied (and then promptly fixed) the bug.

**Comment by vdh** [comment]
Okay, well it's good to know the closing was related then.
