### ISSUE TITLE
[feature request] allow styling of line annotations

### ISSUE THREAD

**Issue by maplebed** [jisaacks/GitGutter#518]
## Description

Line annotations (in my editor at least - I don't know if this is actually a default) appear in the same styling (color, italics) as comments. When working with many comments, this makes the line annotation confusingly similar to actual content in the file. 

I would like to be able to have the line annotation be a slightly different color (a little darker) to fade out of view just a bit more.  

This might be possible by modifying the overall color styling palette, this is annoyingly far away from the rest of the git gutter configs. I would love to have a config option to set the style for the line annotation in the git gutter config itself.

Thanks!

## Support Info

- Sublime Text 3176
- Platform: osx
- Arch: x64
- GitGutter 1.9.3
- Install via PC: True
- git version 2.15.1
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by Calvein** [comment]
:+1: this is a great feature but for some reason my lines are 1 or 2 pixels bigger when the annotation is displayed, which makes the editor to jump and it's a bit distracting.

**Comment by deathaxe** [comment]
Please refer to http://jisaacks.github.io/GitGutter/coloring/#user-defined-color-scheme to learn how to change the color of the annotation.

Annotations are scoped as a special kind of comments - `"comment.line.annotation.git_gutter"`. The color and font-style is to be defined by a color scheme by adding a rule for this scope.

Other styling via CSS wouldn't make any sense as basically anything would break the inline text.

**Comment by deathaxe** [comment]
> my lines are 1 or 2 pixels bigger when the annotation

I guess you've set `line_padding_bottom` and `line_padding_top` to 0?

Can reproduce the issue with these settings. Seems like ST's default CSS adds some padding/margin, which cause the phantom to be higher than the line.

Will fix it.
