### ISSUE TITLE
Disable update changes popup

### ISSUE THREAD

**Issue by hazcod** [jisaacks/GitGutter#519]
## Description

Whenever GitGutter is updated, a tab opens with the latest changes.
For some (like me), we would like to disable this behavior.

**Comment by deathaxe** [comment]
GitGutter provides the update message to briefly announce changes, new features or provide some infos about possible breaking changes, which might require a user to change settings etc.

The messages can't be disabled by GitGutter without completely dropping that feature for all users. You'd therefore need to open a feature request to _Package Control_ to ask for a setting to disable update messages.
