### ISSUE TITLE
Popup text about who made commit is distracting

### ISSUE THREAD

**Issue by HashRocketSyntax** [jisaacks/GitGutter#520]
Hey there. Love the library. Is there a way to turn off the popup feature that appears in today's update?

When I click anywhere on my code - text appears in my code telling me who made the commit (it's a solo project haha) and when and then commit message. This sounds like a really useful feature in general, but I can see it already in bottom tray, and I don't need to see it every time I click.

https://i.imgur.com/TCQ5FQ2.png

**Comment by deathaxe** [comment]
The update message of the release which introduced that feature clearly described the setting to disable this feature.

Usage, settings, ... are described at http://jisaacks.github.io/GitGutter. 

The link to that doc can be found in the README of this repo.

Line annotation settings are described here:

http://jisaacks.github.io/GitGutter/settings/#line-annotation
