### ISSUE TITLE
Support short/abbreviated Git commit ID in line_annotation_text templates

### ISSUE THREAD

**Issue by curtisgibby** [jisaacks/GitGutter#521]
## Description

I like the idea of adding `{{line_commit}}` to my `line_annotation_text`, but the long commit hash kind of gets in the way. It would be nice to have an option to show just the "short" (`--abbrev-commit`) version of the commit ID. Since that's only 8 characters long, I can remember it for long enough to find the commit elsewhere, i.e. by typing it into GitHub or Sublime's "Git: Show Commit By Hash". Would it be possible to add a `{{line_commit_short}}` template (or similar) to pull in the short hash ID?

## Support Info

- Sublime Text 3176
- Platform: linux
- Arch: x64
- GitGutter 1.9.4
- Install via PC: True
- git version 2.7.4
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

**Comment by deathaxe** [comment]
This can be achieved easily with the power of jinja2 already. Just enter `{{line_commit[:7]}}` to get only the first 7 chars printed.

**Comment by curtisgibby** [comment]
Works for me! Thanks!
