### ISSUE TITLE
"deleted" icon no longer centered

### ISSUE THREAD

**Issue by leonklingele** [jisaacks/GitGutter#522]
One of the previous releases broke the alignment of the deleted icon.
I'm on 1.9.4 and this is what I'm seeing (notice the alignment of the red icon):

<img width="108" alt="bildschirmfoto 2018-10-02 um 10 32 58" src="https://user-images.githubusercontent.com/5585491/46337812-c9b9ea80-c62e-11e8-818e-d1a47c463190.png">

**Comment by deathaxe** [comment]
Nope. Icons havn't been changed for ages.

According to the screenshot I'd guess the actual (small) value of the `line_padding_top`, `line_padding_bottom` and a maybe small `font_size` settings causes GitGutter to use the "space-saving" alternative delete icon.

If the line height drops below 16px (in 96dpi) a smaller icon is used automatically as the normal arrows might not fit into the line or would leave too few space. This behavior was introduced years ago.

**Comment by leonklingele** [comment]
It worked just fine not too long ago. I'll do a bisect.

**Comment by leonklingele** [comment]
Hmm, apparently also broken with older releases of this plugin. Maybe the issue is caused by Sublime Text itself? I'm running Version 3.1.1, Build 3176 (the most recent one).

**Comment by leonklingele** [comment]
BTW: The theme was not touched in the last year.

**Comment by leonklingele** [comment]
@deathaxe are you running ST Version 3.1.1, Build 3176 by chance? It might be an incompatibility issue with the current release.

**Comment by deathaxe** [comment]
I always run the latest versions. The displayed icon is not bug, there is nothing broken, it is just an alternative icon, which is used for deleted hunks if the line height is too small (<16) to show the centered arrows.

The following settings e.g. will result in the line height to drop below 16 and cause the small deleted icon . It works with any `ui_scale` value the same way.

```
	"font_size": 10,
	"line_padding_bottom": 0,
	"line_padding_top": 0,
```

If this behavior has changed for you with recent builts of ST3 without changing any settings it must be related with ST's change to use "logical pixel sizes" which were introduced by the recent high-dpi changes. They might result in the line height being calculated logically correct for any screen resolution now.

**Comment by leonklingele** [comment]
This is how it looks using those three config values, something fishy with the icon is going on:

<img width="72" alt="bildschirmfoto 2018-10-13 um 16 46 47" src="https://user-images.githubusercontent.com/5585491/46906706-02e43b80-cf08-11e8-8d73-7df2c3a460ef.png">

**Comment by leonklingele** [comment]
Also, both icons are not centered vertically. Can you please reopen the issue?

**Comment by deathaxe** [comment]
1. To repeat myself another time: Those icons (in the screenshots) are not meant to be centered!
2. Your most recent screenshot shows an core issue with not correctly scaled images, which a plugin (GitGutter) can't fix. A plugin provides just a set of images for different resolutions: (16x16px for 96dpi, 32x32px for 4k, 48x48px or 8k screens). It is ST's task to scale the images correctly to avoid overlapping, which seems not to work for certain combinations of screens and values for the already mentioned settings.

It is possible that icons even have a gap, which is not meant to be there.

![image](https://user-images.githubusercontent.com/16542113/46907036-c535e180-cf0c-11e8-9ef5-cd58b4dc010a.png)

Things get even worse with word wrapped lines.

![image](https://user-images.githubusercontent.com/16542113/46907058-2067d400-cf0d-11e8-8208-3fd2d3891ea9.png)

_Note: settings provide enough vertical space to display the centered "\_arrow" icons!_

This is no GitGutter issue and there is no solution from plugin side.
