### ISSUE TITLE
Prioritise bookmarks in gutter

### ISSUE THREAD

**Issue by safield** [jisaacks/GitGutter#524]
Currently, gitgutter overrides sublime booksmarks icons in the gutter.

I think the booksmarks should be given a higher priority than the gitgutter icons.

Or come up with a create solution to have a single icon convey both the bookmark state along with the git state.

**Comment by deathaxe** [comment]
GitGutter already priories bookmarks by the `protected_regions` setting, which contains all scopes which GitGutter should not overwrite gutter icons for.

If a line is occupied by a region (e.g. bookmark), GitGutter does not add another region to it, which would probably 2 icons to fight against each other.

If a bookmark is added to a line, which is already occupied by GitGutter, the behavior is undefined. In some cases the new bookmark gutter icon wins and is rendered, in some others it not. As GitGutter can't handle other plugin's functions and interactions with the regions API there is no way to work around that issue.

Gutter icon priority e.g. by region name or something like that was requested and discussed a couple of times in the past already.

Gutter icon fighting is a general issue for all plugins making use of it.
