### ISSUE TITLE
Cannot load: broken key bindings?

### ISSUE THREAD

**Issue by michaelblyons** [jisaacks/GitGutter#530]
## Description

GitGutter does not appear to load. Console says this:

>reloading plugin GitGutter.plugin
> Unable to parse binding {command: , keys: [, ]}

I notice that if I try to open the Key Bindings setting from Preferences > Packages > GG > Key Bindings, that the empty User file has `{}` instead of `[]` like a Key Bindings file should. Also, it wants to name the file something very... generic.

## Support Info
 
- Sublime Text 3180
- Platform: osx
- Arch: x64
- GitGutter 8120211
- Install via PC: True
- git version 2.17.2 (Apple Git-113)
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8

## Steps to Reproduce Issue

1. Load a project that has Git tracking.
2. Edit a file.
3. Nothing in gutter.

**Comment by deathaxe** [comment]
Fixed in 1.10.0
