### ISSUE TITLE
GitGutter crashes when opening file in untracked directory

### ISSUE THREAD

**Issue by arasmussen** [jisaacks/GitGutter#532]
## GitGutter crashes when opening file in untracked directory

I just created a new directory in my git repo. There are two JS files in there, and whenever I open either of them, GitGutter crashes which causes all of my packages to stop working. I then have to restart ST3, and it'll crash again unless I disable GitGutter.

After running `git add .` from repo root, the crash stops happening. This leads me to believe that GitGutter is having issues with files in untracked directories.

Here are 100% reliable repro steps (for me):

```sh
cd repo
mkdir foo
touch foo/bar.js
open foo/bar.js
# plugin_host crashes (see screenshot)
```

Then the following fixes the issue:

```sh
# restart ST3
cd repo
git add .
open foo/bar.js
# plugin_host doesn't crash
```

Here's a screenshot of the error:

![image](https://user-images.githubusercontent.com/969540/50361381-35b63b80-0518-11e9-86ff-5f871ae8445c.png)

Support Info:

```
- Sublime Text 3176
- Platform: osx
- Arch: x64
- GitGutter 1.9.5
- Install via PC: True
- git version 2.9.3 (Apple Git-75)
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8
```

This only started happening recently, so I wonder if the issue was introduced in 1.9.5? I don't consciously update my ST3 packages, or understand how updating packages works / if they auto-update.

**Comment by deathaxe** [comment]
Does ST's console tell you anything else? Some traceback messages etc.?

I personally never experienced this issue - not on Windows not on Linux. Don't know anybody who has a Mac by hand. No matter which folders/files I create - untracked or not - everything is fine.

I wonder which kind of issue could crash the whole plugin_host.

Your git is quite outdated. Did you consider updating?

The oldest version I personally tried GitGutter with was 1.10.0. Never had an older one in use.

**Comment by arasmussen** [comment]
ST's console didn't say anything more than the error message in the pop-up.

How did you use GitGutter 1.10.0? It looks like the latest version is 1.9.5.

I updated git to 2.20.1 (previously 2.9.3) and am now unable to reproduce the issue! Good shout.

**Comment by deathaxe** [comment]
Meant 2.10.0
