### ISSUE TITLE
Statusbar infos: add class and function names

### ISSUE THREAD

**Issue by Kraymer** [jisaacks/GitGutter#533]
## Description

Add current class/function name of the current scope in statusbar (in the same vein as https://github.com/akrabat/SublimeFunctionNameDisplay does)

Infos displayed in statusbar are currently : 

~~~
repo/branch, File is modified X+, Commit  infos, Line L, Column C
~~~

It would become  : 

~~~
repo/branch, File is modified X+, Commit  infos, Line L, Column C  Class::method
~~~

## Support Info

~~~
- Sublime Text 3184
- Platform: linux
- Arch: x64
- GitGutter 269acdc
- Install via PC: True
- git version 2.20.1
- mdpopups 3.3.3
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.8
~~~

**Comment by deathaxe** [comment]
1. The infos provided by GitGutter are:

   ```
   repo/branch, File is modified X+, Commit  infos
   ```

   The `Line L, Column C` is added by Sublime Text, which makes it impossible for my knowledge to add anything else behind.

2. GitGutter is meant to display information about the git repo. Can't see how the current class method is related with that task or why it conflicts with `SublimeFunctionNameDisplay` or any otherplugin used to provide infos about the current context. The linked plugin just uses ST's scopes to identify the context, which is not related with git in any way.

**Comment by Kraymer** [comment]
You're right. Don't know if it conflicts  with `SublimeFunctionNameDisplay`, I figured two plugins writing to the status bar would conflict, I'll try that.

**Comment by Kraymer** [comment]
> I figured two plugins writing to the status bar would conflict, I'll try that.

I was wrong, it works great.
