### ISSUE TITLE
Option to disable gutters now that Sublime Text 3.2 provides them

### ISSUE THREAD

**Issue by dnicolson** [jisaacks/GitGutter#537]
Sublime Text 3.2 introduces dedicated markers in the gutter:

![Screenshot 2019-03-13 at 15 23 03](https://user-images.githubusercontent.com/2276355/54286327-ed04a080-45a3-11e9-8188-26712d34daa4.png)

Perhaps there should be an option to disable the gutters while still being able to use the other features of GitGutters. Perhaps it could be achieved by using `protected_regions`?

**Comment by michaelblyons** [comment]
Take a look in the recent commits, particularly https://github.com/jisaacks/GitGutter/commit/a74ed97215a6154b97ff271252fd7b4a18aea3a8. 😉
