### ISSUE TITLE
Default status bar line_author symbol is causing issues with most fonts

### ISSUE THREAD

**Issue by andreiborisov** [jisaacks/GitGutter#544]
Symbol `⟢` is not present in most fonts, so if Sublime theme or user himself is using custom font for status bar UI, the string is cutoff prematurely:

<img width="1185" alt="54880745-75632b00-4e59-11e9-8ddd-5dbaed784db1" src="https://user-images.githubusercontent.com/13354491/54882476-72713600-4e6b-11e9-9fea-35774236a2b3.png">

I feel like default `status_bar_text` setting should use something more neutral and versatile that would work on as many setups as possible.

**Comment by schrodincat** [comment]
Personally I'd remove it completely which would be also consistent with how `line_annotation_text` is constructed by default
