### ISSUE TITLE
Append to same line

### ISSUE THREAD

**Issue by duraki** [jisaacks/GitGutter#545]
## Description
  
When pane/text window view is lacking `horizontal space`, the lines break, and GitGutter output to new line. See image below.

![Screenshot 2019-03-24 at 22 30 53](https://user-images.githubusercontent.com/5892610/54886137-b58bd300-4e84-11e9-9929-709e8cb2450a.png)

## Info
  
**Problem**: The commit info line is added in new line.  
**Solution**: Either force through ruler settings (`"line_annotation_ruler": 1`), or append to line horizontally.
  
This may be related to #525 but I'm not sure, therefore this issue. If this is in fact a ST3/underlaying problem, let me know. 
  
Any hint/hack as a temporary solution is appreciated. Maybe horizontal scrolling enabled?
  
## Support Info
... none, not a bug
  
## Steps to Reproduce Issue
... none, not a bug
  
Thanks for the plugin @jisaacks! I'm starting to promote it over here at [duraki/sublime-packed](https://github.com/duraki/sublime-packed).

**Comment by deathaxe** [comment]
The line annotations use Sublime Text's phantoms API. Phantoms are added by character position in the text buffer with the `sublime.LAYOUT_INLINE` flag being passed to Sublime Text. It is then up to Sublime Text to decide how to render the phantom. 

It is a know issue of ST to include phantoms into word wrapping. Hence the `"show_line_annotation": "auto",` setting causes line annotations to be disabled automatically if word wrapping is detected.

**Comment by duraki** [comment]
Highly appreciate detailed response and follow-up issue, thank you. Following.

**Comment by deathaxe** [comment]
This issue is fixed for ST4 with via the new annotations API.
