### ISSUE TITLE
GitGutter not working in Ubuntu

### ISSUE THREAD

**Issue by fabiobatalha** [jisaacks/GitGutter#547]
# Description

GitGutter was properly installed using the PackageControl but the diff is not working, the icons with the changes are not being shown.

The picture bellow shows everything is properly setup.

![Capture du 2019-06-26 15-06-51](https://user-images.githubusercontent.com/504142/60207713-8c346780-9824-11e9-9d12-82172fe066d4.png)

## Steps to Reproduce Issue

1. Fresh new Sublime installed
2. PackageControl Installed
3. GitGutter installed with no errors using PackageControl

**Comment by michaelblyons** [comment]
Is [this](https://github.com/jisaacks/GitGutter/issues/543#issuecomment-473656186) your problem?
