### ISSUE TITLE
save-as change filename but gutter works against the original file

### ISSUE THREAD

**Issue by 4ndrej** [jisaacks/GitGutter#549]
## Description

When I save-as file, the filename change but the gutter works as if it is original file. Changes are displayed as changes even if the new file is not under source control.

## Support Info
- Sublime Text 3176
- Platform: linux
- Arch: x64
- GitGutter 6f4f573
- Install via PC: True
- git version 2.21.0
- mdpopups 3.4.0
- markdown 2.6.11
- pygments 2.1a0
- jinja2 2.10.1

## Steps to Reproduce Issue

1. open file "original.sh". file is under git source control
1. "save as" another file "changed.sh"
1. change something
1. save file
1. gutter acts as if I change the original file - displays the modified icons
1. the new file does not have to be under source control yet

**Comment by deathaxe** [comment]
I can reproduce the issue. Will have a look into it in the next few days, I think
