### ISSUE TITLE
Add color highlights to the mini map

### ISSUE THREAD

**Issue by CodeCommander** [jisaacks/GitGutter#55]
Is it possible to add green/yellow/red highlights of the diff lines to the Sublime Text mini map? This would make it much easier to see where changes in the file are and scroll to them quickly.

**Comment by davidfooks** [comment]
Would it be possible to highlight the entire line in the minimap? (instead of just the border). I can't really see the pixel wide line with my colour scheme "Slush & Poppies" (even if I change it to bright pink it's quite hard to spot).

**Comment by jisaacks** [comment]
@davidfooks Not that I am aware of.
