### ISSUE TITLE
Inline commit log message and file types

### ISSUE THREAD

**Issue by guy-middleton** [jisaacks/GitGutter#554]
## Description

For some file types I get a helpful git commit message listing on the selected line:

<img width="1044" alt="Screen Shot 2020-07-24 at 10 24 48" src="https://user-images.githubusercontent.com/8820869/88401594-f016c000-cd97-11ea-95f1-4a919af3a6ae.png">

But for most file types, I don't see this. Is there a way to enable/disable this feature?

## Support Info

- Sublime Text 3211
- Platform: osx
- Arch: x64
- GitGutter 1.11.2
- Install via PC: True
- git version 2.27.0
- mdpopups 3.7.1
- markdown 3.1.1
- pygments 2.1a0
- jinja2 2.10.1

**Comment by deathaxe** [comment]
The line annotations are enabled if `word_wrap` is disabled, which is the case for source code but not for text by default. It's because the phantoms don't display well otherwise.

**Comment by guy-middleton** [comment]
Excellent, thanks.
