### ISSUE TITLE
GitGutter not available to install in package control

### ISSUE THREAD

**Issue by jamadagni** [jisaacks/GitGutter#555]
## GitGutter not available to install in package control

I am using ST 3.2.2 build 3211 on Kubuntu Bionic. I open Package Control: Install package, but I am unable to find GitGutter at all to install. Is there a version compatibility problem?

Please help.

**Comment by michaelblyons** [comment]
Package Control itself has been suffering from some intermittent failures not specific to this package. Try again the next day?

There is no incompatibility problem.

**Comment by jamadagni** [comment]
I am able to install other packages. There is no connection or such failure in those cases. When it shows the box to type the package in, and I type `gitgut` or `git gut` I simply don't see this package. I see lots of others.

**Comment by michaelblyons** [comment]
Sounds like the PC internal problem was fixed. I don't know what might be causing your issue.

**Comment by jamadagni** [comment]
Sorry, seems to be some misunderstanding on my part. It's working now.
