### ISSUE TITLE
How do I make the icons show?

### ISSUE THREAD

**Issue by mrjayviper** [jisaacks/GitGutter#556]
As above.

These are the only settings I changed.

```
// GitGutter Settings - User
{
	"debounce_delay": 100,
	"git_gutter_enable": true,
	"show_line_annotation": true,
    "show_status_bar_text": true
}
```

To test, I entered some text on a newline but no icons. Thanks

**Comment by deathaxe** [comment]
Maybe https://jisaacks.github.io/GitGutter/troubleshooting/#gitgutter-doesnt-add-gutter-icons-any-more?

**Comment by snowman** [comment]
"mini_diff": false
