### ISSUE TITLE
Not work for network mount wsl2 disk

### ISSUE THREAD

**Issue by HarDX** [jisaacks/GitGutter#569]
Not work for network mount wsl2 disk

When copy all content from network disk to local ssd/hdd, all is fine - popup works and other.

## Support Info
- Sublime Text 4126
- Platform: windows
- Arch: x64
- GitGutter 1.11.7
- Install via PC: True
- git version 2.36.0.windows.1
- mdpopups 4.2.1
- markdown 3.2.2
- pygments 2.1a0
- jinja2 2.10.1

## Steps to Reproduce Issue

1.  Open file on network mount disk wsl2 (maybe using wsl2 not matter)
2.  No popup windows and info about commit

**Comment by deathaxe** [comment]
GitGutter fully relies on `git` executable to be able to access the repository. What does `git status` return, when called from a "Windows command shell"?

I've just installed a debian distro and copied a repo to `\\wsl.localhost\Debian\home\user\repo` and opened that folder in ST. Working normally without any issues. GitGutter displays commit status, blame info and modifications as expected.

Please note, that git may not recognize that repo to be yours and thus denies access by default as of git 2.26. You need to call `git config --global --add safe.directory '%(prefix)///wsl.localhost/Debian/home/user/repo'` first, to tell git you trust that remote location

... or just `git --global --add safe.directory *` to disable that bullshit.

**Comment by HarDX** [comment]
Thanks, add safe.directory is help for me.
