### ISSUE TITLE
Files in cloned gists don't show the inline git blame when `show_line_annotation` is set to `true`

### ISSUE THREAD

**Issue by brian6932** [jisaacks/GitGutter#571]
## Description

It definitely is working, because it shows `File is committed` in the bottom left, just `show_line_annotation` is not working

## Support Info

- Sublime Text 4143
- Platform: windows
- Arch: x64
- GitGutter 1.11.7
- Install via PC: True
- git version 2.38.1.windows.1
- mdpopups 4.2.2
- markdown not installed!
- pygments not installed!
- jinja2 2.10.1

## Steps to Reproduce Issue

1. Clone a gist
2. `subl .` into the folder
3. Open any text file

**Comment by deathaxe** [comment]
It's working fine on my end.

**Comment by brian6932** [comment]
It seems to sometimes work, and sometimes not, not sure what breaks it exactly, but gists aren't the cause
