### ISSUE TITLE
`~` is not accepted/resolved to home in `git_binary`

### ISSUE THREAD

**Issue by brian6932** [jisaacks/GitGutter#572]
## Description

If `~` is supplied in the `git_binary` path, it should resolve to home, `~` should link to `C:\users\username` on Windows

## Support Info

- Sublime Text 4143
- Platform: windows
- Arch: x64
- GitGutter 1.11.7
- Install via PC: True
- git version 2.38.1.windows.1
- mdpopups 4.2.2
- markdown not installed!
- pygments not installed!
- jinja2 2.10.1

## Steps to Reproduce Issue

1. Open GitGutter settings
2. Set a path to git that contains `~`

**Comment by deathaxe** [comment]
`~` is not a valid environment variable on Windows. You should use `%USERPROFILE%` instead.

**Comment by brian6932** [comment]
`~` is not an environment variable anywhere, tons of programs expand it to `$env:USERPROFILE`, powershell/pwsh support `~` natively.
Either way, `%USERPROFILE%` works, so I'll close this.

**Comment by deathaxe** [comment]
GitGutter doesn't run git via shell but directly. Thus relation to behavior of shells (which is well known) is irrelevant.
