### ISSUE TITLE
Original data on hover over gutter icons

### ISSUE THREAD

**Issue by knownasilya** [jisaacks/GitGutter#61]
Feature request.

Would be very helpful to see the original code (before the modification) when hovering over the relevant change icon in the gutter. Eclipse Git plugin does this very well, where it overlays the original change over the current change, so you can see it inline with the rest of the code. This could be a setting, specifying where/how the data is displayed.

![sublime2-gitgutter-overlay](https://f.cloud.github.com/assets/34726/228134/2be06f02-8677-11e2-8990-14d8d3f57a71.png)

**Comment by gwenzek** [comment]
Since build 3116, there is an "hover" api allowing to display a popup when overing over the gutter or any part of the code. See https://forum.sublimetext.com/t/dev-build-3116/21148 for more details.

This would be a really great addition to this very good plugin.

**Comment by jisaacks** [comment]
@gwenzek thanks for brining this to my attention. I do not have time to work on this feature myself right now. If anyone wants to try to tackle it, go for it.

**Comment by rchl** [comment]
Hovering over the gutter to show the changes is already implemented.

**Comment by gwenzek** [comment]
Just to be clear, it wasn't possible when the issue was opened 3 years ago.
Now it is thanks to PR #296.
