### ISSUE TITLE
Show icons on the file tab

### ISSUE THREAD

**Issue by jpavon** [jisaacks/GitGutter#71]
Feature request.

Would be great to have a little feedback on what type of changes have you made to each file, examples:

![tab-icons](https://f.cloud.github.com/assets/1493505/256578/5a606d20-8c2e-11e2-88ec-81d8b9ae8e49.jpg)

or

![tab-icons2](https://f.cloud.github.com/assets/1493505/256577/5a5d5d88-8c2e-11e2-9046-e00d4d2ca398.jpg)

**Comment by flowerett** [comment]
Is it possible to change folder colors instead of icons (like in Atom)?
![atom-folder-colors](https://cloud.githubusercontent.com/assets/2693127/8397883/2c77ccfa-1df4-11e5-91ef-e5d426d60694.png)

**Comment by jisaacks** [comment]
As far as I know, that cannot be manipulated in the way necessary for gitgutter to work. If someone can show me an API that allows it, I would love to add the functionality. Until then I am going to close the issue.
