### ISSUE TITLE
Add the ability to disable evaluation on network files

### ISSUE THREAD

**Issue by michal-m** [jisaacks/GitGutter#79]
I regularly work on network files over VPN. This means that the connection isn't great and I noticed GitGutter slows down SublimeText3 considerably then, even though it's in `non_blocking` mode.

**Comment by zxqfox** [comment]
Is it possible to run `git diff` in different thread? It could remove this lag.

**Comment by deathaxe** [comment]
With GitGutter 1.5.0 the file from git index is read once after loading or changing compare target. All diff operations are performed using local temporary files and thus don't depend on network speed any longer. All commans are run in the plugin_host using `sublime.set_timeout_async()` if available.

**Comment by deathaxe** [comment]
Will be fixed together with Issue #161
