### ISSUE TITLE
Sublime text lagging when git binaries ain't found

### ISSUE THREAD

**Issue by SBoudrias** [jisaacks/GitGutter#94]
Hi,

I got a pretty annoying bug related to this plugin. The plugin wasn't able to find the git binaries, and this made sublime text ultra laggy. Took me a while to figure out where this lag came from.

Maybe it should disable itself when git binaries ain't found or trying to save some resources to prevent this from happening?

**Comment by deathaxe** [comment]
GitGutter 1.5.0 is disabled at all, if git binary was not found on PATH or settings.
